### ISSUE TITLE
CELERYBEAT_SCHEDULE samples are misleading

### ISSUE THREAD

**Issue by tko** [celery/celery#1027]
http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#entries

With the sample celerybeat schedules named very generically like "runs-every-30-seconds" with no reference to the task being run it gives the impression if you have multiple tasks to be run in same schedule you could and should group them under the same entry. But how exactly you'd do that is not documented so you end up trying to move "task" and "args" in a sub-dictionary or lists or something, which still won't work.

IMO it would be less ambiguous if the sample schedule entry naming would avoid implying different tasks can be grouped in same schedule if it's not possible (or show a sample if it is) and rather include the task name into the schedule entry name as well, e.g. "add-every-30-seconds" would be less suggestive to allow tasks to be grouped in same schedule.

**Comment by pzrq** [comment]
http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#entries
Agree this is still valid and confusing. The example suggests you repeat the `schedule` info to create the `CELERYBEAT_SCHEDULE` dictionary keys, but that seems to be against [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) because you may very well change the `crontab` or `timedelta` scheduling as your project evolves.

The closest thing I could find to documentation of what one convention for the `CELERYBEAT_SCHEDULE` key names could be is actually in the deprecated PeriodicTask class: https://github.com/celery/celery/blob/3e3d03f83d34310344216af7e44f74ad82e557f6/celery/task/base.py#L262-L264

Considering the two sources are both quite different, I hope it's reasonably safe to expect you can use whatever key names you want to, as long as they key names are not repeated.

It would be nice to get some confirmation from someone who understands the internals and direction of the project, ideally in the documentation.

**Comment by pzrq** [comment]
Simplified example of what we now have in production with our main Django project in case anyone else stumbles across this:

```
CELERYBEAT_SCHEDULE = {
    # Keys can probably be anything, so we do as celery.task.PeriodicTask does
    # and reuse the name of the task which is at least more likely to get found in 
    # string replacement refactoring than repeating the crontab info
    'trigger_email_user_export_csv': {
        'task': 'myproject.app1.tasks.trigger_email_user_export_csv',
        'schedule': crontab(day_of_week='sunday', hour=23, minute=50),
    },
    'trigger_start_calculating_dependency_matrix': {
        'task': 'myproject.app2.tasks.trigger_start_calculating_dependency_matrix',
        'schedule': crontab(day_of_week='sunday', hour=0, minute=30),
    },
    'trigger_process_commitments': {
        'task': 'myproject.app3.tasks.trigger_process_commitments',
        'schedule': timedelta(hours=1),
    },
    ...
}
```
