### ISSUE TITLE
Redis backend and socket_timeout default

### ISSUE THREAD

**Issue by msgre** [celery/celery#1221]
Hello,
I use Redis as Celery backend on AWS EC2 instances. I have several machines there -- on first is webapp, on second Celery workers, on third Redis broker. After some time (1-2 days) my workers suddenly stop processing tasks. I investigated this situation, and I think that problem is in Celery code, exactly at this line: https://github.com/celery/celery/blob/master/celery/backends/redis.py#L109

It seems, that sometimes AWS drop net connection, and socket connection die. Because there is no `socket_timeout` argument in `ConnectionPool` constructor, no exception occurs and my workers wait until I restart them (my workers run as supervisor processes).

I modified Celery code on line 109, so now I have there `socket_timeout=10` and there was no problem with workers hanging for more than 3 weeks.

Could you please add some settings variable to override `ConnectionPool` `socket_timeout` default please?

**Comment by joshma** [comment]
@ask this is many years later but I think still relevant - socket_timeout is still None, by my understanding of https://github.com/celery/kombu/blob/v4.1.0/kombu/transport/redis.py#L404

Is there a reason there shouldn't be some default timeout set instead? (Asking because our team's about to do so, in order to resolve https://github.com/celery/celery/issues/4453)
