### ISSUE TITLE
Celery management commands for SQS

### ISSUE THREAD

**Issue by utsengar** [celery/celery#1291]
The celery management commands for SQS are not implemented. Is there a plan to do one?
This causes flower not to work: https://github.com/mher/flower/issues/65

Any pointers on the existing implementation of the management commands would also help, I can try to see if I can implement it.

**Comment by gnarlyfactory** [comment]
@mher @utkarsh2012 @ask I'm trying to get some better visibility into celery tasks I have running connected to an SQS broker. Wasn't sure if I should post this here or on the Flower issue tracker instead.

I believe the issue is that the get_manager function is not implemented on the SQS transport class (as it is here [in ampqlib](https://github.com/celery/kombu/blob/master/kombu/transport/amqplib.py#L405)) am I correct in my assumption? I'd really love to get flower running to be able to manage what resides within the SQS broker.
Any other tips/pointers would be greatly appreciated

**Comment by thedrow** [comment]
@gnarlyfactory You just need to create dedicated queues in SQS for the events and allow to publish/subscribe to them. You also need to publish the events to those queues.
