### ISSUE TITLE
Message being acknowledged on WorkerLostError when CELERY_ACKS_LATE=True

### ISSUE THREAD

**Issue by siddharth96** [celery/celery#1628]
When using celery v3.0.24, with `CELERY_ACKS_LATE = True` , if the OOM killer kills the celery worker, then the worker acknowledges the message.
As per [this](https://github.com/celery/celery/commit/e810420c) commit. The `exc_info.internal` comes in as `false`, which means it is not a internal error, due to which the message is acknowledged.
The desirable behaviour, in such a case would be to not acknowledge the message (and be able to know, whether its a OOM error), so that some other worker can pick it up. 
As a workaround, I've commented out the [code](https://github.com/siddharth96/celery/commit/427695d1b23034dadda85fd7a48f7367831be4fa), where celery acknowledges the message, because in such a case, message will be lost.

**Comment by mpermana** [comment]
https://github.com/celery/celery/pull/2840

**Comment by mpermana** [comment]
@ask Added configuration option for not acking terminated tasks

**Comment by ask** [comment]
We have an option for this in master now

**Comment by siddharth96** [comment]
I was just trying this set of changes, and when I raised an error in the consumer, the message didn't even went through this flow. ```on_failure``` defined in ```celery/worker/jobs.py``` got called, while the change here is at another place.
Should we re-open this?

**Comment by thedrow** [comment]
@siddharth96 Can you provide a test case that reproduces the problem?

**Comment by odedfos** [comment]
Acknowledging the task on WorkerLost is very misleading, when acks_late=True.
Processes get killed for numerous reasons, and even when OOM, the conditions on the machine could be that the memory issue isn't related directly to the killed process.

At the least, I think this behaviour should be configurable, and allow for the task not to be acknowledged.
I find myself implementing a watchdog searching for lost workers and requeueing those tasks instead of having the framework do as it suggests (according to documentation)

**Comment by Adamantish** [comment]
:+1: for configurability

**Comment by thedrow** [comment]
I think we can accept a configuration knob which implements this but I'm not sure it's worth it.
Perhaps there should a hook instead which you can configure to customize acknowledgment behavior.
@celery/core-developers What do you think?

**Comment by galCohen88** [comment]
Not sure how this can be implemented, if there is a power shutdown there will be no guarantee for acking acks late message. 
The problem originates from non-idempotent tasks

**Comment by shubham088** [comment]
Hello, i have this use case.
i am reading some messages from sqs (amazon queue service ) and celery jobs are receiving these messages . upon receiving the msg from queue i am doing some processing and if prcoessing is not complete i am pushing the msg back to queue .
But if i stop the celery manually , i am noticing that it is killing the process in between because of which i am not able to push the msg back to queue which leads to data loss.
Any solution how to solve this issue.
Kindly , tell me the solution and can contact me on shubhamsharma0296@gmail.com
