### ISSUE TITLE
Systemd service file is invalid

### ISSUE THREAD

**Issue by moggers87** [celery/celery#2131]
Output of `systemctl status celery` after installing the service file and reloading systemd's configs:
```
Jul 08 21:55:05 localhost.localdomain systemd[1]: [/etc/systemd/system/celery.service:11] Executable path is not absolute, ignoring: ${CELERY_BIN} multi start $CELERYD_NODES      -A $CELERY_APP --pidfile=${CELERYD_PID_FILE}      --logfile=${CELERYD_LO..."      $CELERYD_OPTS
Jul 08 21:55:05 localhost.localdomain systemd[1]: [/etc/systemd/system/celery.service:12] Executable path is not absolute, ignoring: ${CELERY_BIN} multi stopwait $CELERYD_NODES      --pidfile=${CELERYD_PID_FILE}
Jul 08 21:55:05 localhost.localdomain systemd[1]: [/etc/systemd/system/celery.service:13] Executable path is not absolute, ignoring: ${CELERY_BIN} multi restart $CELERYD_NODES      -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE}      --logfile=${CELERY..."      $CELERYD_OPTS
Jul 08 21:55:05 localhost.localdomain systemd[1]: celery.service lacks ExecStart setting. Refusing.
```

I've tried using this service file on both CentOS 7 and Fedora 20 with the same results.

**Comment by jxstanford** [comment]
A little late to the party, but here's what I did to get workers and beat going under CentOS 7.  It seems to be working fine:

/etc/sysconfig/celery:
```
DJANGO_SETTINGS_MODULE="goldstone.settings.production"
CELERY_APP="goldstone"

# Worker settings
CELERYD_NODES="w1"
CELERYD_OPTS="--time-limit=300 --concurrency=8"
CELERYD_LOG_FILE="/var/log/goldstone/celery-%N.log"
CELERYD_STATE_DIR="/var/run/celery"
CELERYD_PID_FILE="/var/run/celery/goldstone-%N.pid"
CELERYD_LOG_LEVEL="INFO"

# Beat settings

CELERYBEAT_LOG_FILE="/var/log/goldstone/celerybeat.log"
CELERYBEAT_STATE_DIR="/var/run/celerybeat"
CELERYBEAT_PID_FILE="/var/run/celerybeat/goldstone-celerybeat.pid"
CELERYBEAT_LOG_LEVEL="INFO"
CELERYBEAT_SCHEDULE="/var/run/celerybeat/goldstone-schedule"
CELERYBEAT_WORK_DIR="/opt/goldstone"
```

/usr/lib/systemd/system/celery.service
```
[Unit]
Description=Celery workers
After=network.target redis.target

[Service]
Type=forking
User=apache
Group=apache
EnvironmentFile=-/etc/sysconfig/celery
WorkingDirectory=/opt/goldstone/
# run ExecStartPre as priviledged user and set up /var/run
PermissionsStartOnly=true
ExecStartPre=-/usr/bin/mkdir ${CELERYD_STATE_DIR}
ExecStartPre=/usr/bin/chown -R apache:apache ${CELERYD_STATE_DIR}
ExecStart=/bin/celery multi start $CELERYD_NODES \
    -A $CELERY_APP --pidfile=${CELERYD_PID_FILE} \
    --logfile=${CELERYD_LOG_FILE} --loglevel="${CELERYD_LOG_LEVEL}" \
    $CELERYD_OPTS
ExecStop=/bin/celery multi stopwait $CELERYD_NODES \
    --pidfile=${CELERYD_PID_FILE}
ExecReload=/bin/celery multi restart $CELERYD_NODES \
    -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
    --logfile=${CELERYD_LOG_FILE} --loglevel="${CELERYD_LOG_LEVEL}" \
    $CELERYD_OPTS

[Install]
WantedBy=multi-user.target
```

/usr/lib/systemd/system/celerybeat.service
```
[Unit]
Description=Celery beat scheduler
After=network.target redis.target

[Service]
Type=simple
User=apache
Group=apache
EnvironmentFile=-/etc/sysconfig/celery
WorkingDirectory=/opt/goldstone/
# run ExecStartPre as priviledged user and set up /var/run
PermissionsStartOnly=true
ExecStartPre=-/usr/bin/mkdir ${CELERYBEAT_STATE_DIR}
ExecStartPre=/usr/bin/chown -R apache:apache ${CELERYBEAT_STATE_DIR}
ExecStart=/bin/celery beat -A ${CELERY_APP} \
    --workdir=/opt/goldstone \
    --pidfile=${CELERYBEAT_PID_FILE} \
    --logfile=${CELERYBEAT_LOG_FILE} \
    --loglevel=${CELERYBEAT_LOG_LEVEL} \
    --schedule=${CELERYBEAT_SCHEDULE}
ExecStop=/bin/systemctl kill celerybeat.service

[Install]
WantedBy=multi-user.target
```

Then fire things up:
```
systemctl enable celery.service
systemctl enable celerybeat.service
systemctl start celery.service
systemctl start celerybeat.service
```

I got unexpected failures when I tried to reference vars within vars in the conf file.  For example, this causes a service to fail to start:
```
CELERYBEAT_STATE_DIR="/var/run/celerybeat"
CELERYBEAT_PID_FILE="${CELERYBEAT_STATE_DIR}/goldstone-celerybeat.pid"
```

**Comment by inducer** [comment]
Just to emphasize: The sample config file for starting workers on the (by now) dominant Linux process launcher that you provide here:

https://celery.readthedocs.org/en/latest/tutorials/daemonizing.html#usage-systemd

is completely broken, and it fails with a non-obvious error message:

```
[/etc/systemd/system/celery.service:22] Executable path is not absolute, ignoring: $CELERY_BIN multi stopwait $CELERYD_NODES      --pidfile=$CELERYD_PID_FILE
```

You should either remove that snippet of the docs, or fix the example.

**Comment by fxer** [comment]
As inducer mentioned, you can't have a variable as the executable path. Stolen from stackoverflow:

> From the "Command lines" section in systemd.service(5):
> > Note that the first argument (i.e. the program to execute) may not be a variable.

However another problem I've run into is that 'systemctl reload celery' fails, and takes celery offline:

>[root@imperial conf.d]# systemctl status celery.service 
celery.service - Celery workers
   Loaded: loaded (/etc/systemd/system/celery.service; enabled)
   Active: active (running)

> [root@imperial conf.d]# systemctl reload celery

> [root@imperial conf.d]# systemctl status celery.service 
celery.service - Celery workers
   Loaded: loaded (/etc/systemd/system/celery.service; enabled)
   Active: inactive (dead)

Looking in the systemd logs shows me:
>Sep 20 21:20:03 imperial systemd[1]: Reloading Celery workers.
Sep 20 21:20:04 imperial celery[20457]: celery multi v3.1.13 (Cipater)
Sep 20 21:20:04 imperial celery[20457]: > Stopping nodes...
Sep 20 21:20:04 imperial celery[20457]: > worker@imperial: TERM -> 20218
Sep 20 21:20:10 imperial celery[20457]: > Waiting for 1 node -> 20218.......
Sep 20 21:20:10 imperial celery[20457]: > worker@imperial: OK
Sep 20 21:20:11 imperial celery[20457]: > Restarting node worker@imperial: OK
Sep 20 21:20:12 imperial celery[20476]: celery multi v3.1.13 (Cipater)
Sep 20 21:20:12 imperial celery[20476]: > worker@imperial: DOWN
Sep 20 21:20:12 imperial systemd[1]: Reloaded Celery workers.

But the workers never come back up, until I issue a 'restart' celery sits there dead

**Comment by ask** [comment]
Please submit a pull request, as I have no way of testing this on OS X

**Comment by temoto** [comment]
http://boot2docker.io/ is a way to test Linux related things on OS X.

**Comment by joesanford** [comment]
Is a new .service file needed? I can have a PR in sometime today if so.

**Comment by inducer** [comment]
I believe that, yes, a new `.service` file is still needed.

**Comment by joesanford** [comment]
For #2131 thanks for catching the missing `--`. However, this is a file that is working in production on CentOS 7 boxes and does not need `/bin/sh` called, nor should `.service` files contain absolute paths that are not driven by an external configuration. Additionally, the `celery` binary is a Python, not shell script. There may be something wrong with @arthru's environment, but `/bin/sh` may actually lead to more confusion, as well as making that call can lead to security concerns.

**Comment by arthru** [comment]
I've been trying to keep the CELERY_BIN variable as I know it is useful to change that sometimes. But using that variable as the executable in ExecStart led to an error like "executable must be an absolute path".
 
So in order to keep the possibility to use CELERY_BIN from the environment file and use that variable in ExecStart, I just used the default shell to launch an executable that came from the config... Please also note that shell uses the hashbang line at the top of the file to know how to execute it.

My OS is ArchLinux with Systemd 229. I guess that Systemd 219 shipped in Centos7 allowed the behavior with a variable as executable... but I was not able to find anything in documentation...

**Comment by vosamo** [comment]
@joesanford Hi,I have the same problem when I use systemd.Have you solved it?

**Comment by timstaley** [comment]
@joesanford @arthru Just wanted to reiterate comments from further up this thread, since this had me tearing my hair out for about an hour. (As it turns out, I was looking at the r3.1 branch - the [current master examples](https://github.com/celery/celery/blob/73d447318d6e38ae9e8f56719fe8053573038fcc/extra/systemd/celery.service)  work OK).
From https://www.freedesktop.org/software/systemd/man/systemd.service.html
> For each of the specified commands, the first argument must be an absolute path to an executable.

and
> Note that the first argument (i.e. the program to execute) may not be a variable.
Hence the requirement for slightly weird `/bin/sh` prefixes if e.g. you're using celery as installed into a virtualenv.

**Comment by arthru** [comment]
@timstaley Thanks for pointing out the doc from systemd !

**Comment by gdubicki** [comment]
I am having issues with systemd service on Centos 7 too.

This is my service file:

```
[Unit]
Description=Celery Service
After=network.target

[Service]
Type=forking
User=myservice
Group=myservice

WorkingDirectory=/srv/myservice

ExecStart=/srv/myservice/venv/bin/celery multi start myservice-worker-1 -A myservice.celery.config.configured_app --logfile=/var/log/celery/%n.log --pidfile=/var/run/celery/%n.pid "-P gevent -Q celery -l INFO"

ExecStop=/srv/myservice/venv/bin/celery multi stopwait myservice-worker-1 --pidfile=/var/run/celery/%n.pid

ExecReload=/srv/myservice/venv/bin/celery multi restart myservice-worker-1 -A myservice.celery.config.configured_app --logfile=/var/log/celery/%n.log --pidfile=/var/run/celery/%n.pid "-P gevent -Q celery -l INFO"

[Install]
WantedBy=multi-user.target
```

...so as you can see I am using virtualenv, if that matters. So `ExecStart` command is working like a charm when run directly from `myservice` user shell. But when I run it using systemd I get the following in the journald:

```
Sep 19 13:05:55 hostname systemd[1]: Started Celery Service.
Sep 19 13:05:55 hostname systemd[1]: Starting Celery Service...
Sep 19 13:05:56 hostname python[17723]: celery multi v3.1.23 (Cipater)
Sep 19 13:05:56 hostname python[17723]: > Starting nodes...
Sep 19 13:05:56 hostname python[17723]: > myservice-worker-1@hostname: OK
Sep 19 13:05:56 hostname python[17738]: celery multi v3.1.23 (Cipater)
Sep 19 13:05:56 hostname python[17738]: > myservice-worker-1@hostname: DOWN
```

Can someone help?

**Comment by gdubicki** [comment]
UPDATE: I got it working, but it's strange. See https://github.com/celery/celery/issues/3459

**Comment by temoto** [comment]
- It's widely adopted (and for good reasons) practice to install Python applications in virtualenvs anyway, so you know where celery is located, no need for environment variables for that.
- And you don't have to use `celery multi`. Can't imagine how it could be useful, but if somebody has so large Celery farm to justify `multi`, they probably able to setup their deployment too.

Here's what works on several machines (cut some obvious and some private lines):
`app-task.service`
```
Type=simple
KillMode=control-group
PrivateTmp=true
Restart=always
RestartSec=5
TimeoutSec=30
Nice=5
ExecStart=/app/bin/run-task
# permissions, limits
```

`/app/bin/run-task`
```
#!/bin/bash -e
# prod/devel/etc environment settings
set -a
source .env
set +a
flags=(
    --beat
    --config=celeryconfig
    --loglevel=INFO
    --workdir=/app/project
)
exec /app/bin/newrelic-admin run-program \
    /app/bin/python /app/src/package/manage.py celery worker ${flags[@]}
```

**Comment by MrYoda** [comment]
@jxstanford I'm trying to use your ```/usr/lib/systemd/system/celerybeat.service``` and systemctl could not detach beat process and timed out after 90 seconds when I try to start celerybeat. If I append --detach to ExecStart - celerybeat die.
Do you know what is it?
Celery 4.0.1 (latentcall) on Python 3.5.2 on Ubuntu 16.04.1 LTS

**Comment by MrYoda** [comment]
@jxstanford Oh, solved. I changed /bin/sh to /bin/bash in ExecStart and it works well.

**Comment by ArsenePadthai** [comment]
i have the following .service but it does not work as expected,
`[Unit]
Description=Celery beat scheduler
After=network.target

[Service]
Type=simple
User=neocu
Group=neocu
EnvironmentFile=/etc/neocu_notification_service/common.conf
EnvironmentFile=-/etc/neocu_notification_service/celery.conf
WorkingDirectory=/usr/share/neocu_notification_service
#PermissionsStartOnly=true
ExecStartPre=/bin/bash -c 'mkdir -p /var/run/neocu_notification_service; chown neocu:neocu /var/run/neocu_notification_service'
ExecStart=/bin/bash -c '/usr/share/neocu_notification_service/venv/bin/celery beat -A sender --pidfile=${CELERYBEAT_PID_FILE}'


[Install]
WantedBy=multi-user.target`

And I checked the status, as below:
● neocu-notification-beat.service - Celery beat scheduler
   Loaded: loaded (/usr/lib/systemd/system/neocu-notification-beat.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

2月 28 18:53:44 neocuqa-controller bash[139239]: celery beat v3.1.23 (Cipater) is starting.
2月 28 18:53:44 neocuqa-controller bash[139239]: __    -    ... __   -        _
2月 28 18:53:44 neocuqa-controller bash[139239]: Configuration ->
2月 28 18:53:44 neocuqa-controller bash[139239]: . broker -> amqp://neocu_notify:**@localhost:5672//
2月 28 18:53:44 neocuqa-controller bash[139239]: . loader -> celery.loaders.app.AppLoader
2月 28 18:53:44 neocuqa-controller bash[139239]: . scheduler -> celery.beat.PersistentScheduler
2月 28 18:53:44 neocuqa-controller bash[139239]: . db -> celerybeat-schedule
2月 28 18:53:44 neocuqa-controller bash[139239]: . logfile -> [stderr]@%INFO
2月 28 18:53:44 neocuqa-controller bash[139239]: . maxinterval -> now (0s)
2月 28 18:53:44 neocuqa-controller systemd[1]: Started Celery beat scheduler.

Does anyone know where the problem is? thx!
