### ISSUE TITLE
Protocol 2 headers are not decoded from bytes on Py3

### ISSUE THREAD

**Issue by jbg** [celery/celery#2157]
Although a task called `core.tasks.get` is registered (confirmed that it is listed on Celery startup), Celery does not find it when protocol 2 is used to call it. It appears to be because the headers are not decoded from `bytes` and therefore will not compare `True` against an equivalent `str`:

```
[2014-07-17 20:50:54,153: WARNING/MainProcess] Received and deleted unknown message. Wrong destination?!?

The full contents of the message body was: body: [[], {'key': 'o.Sale'}, {}] (15b)
{content_type:b'application/x-msgpack' content_encoding:b'utf-8'
  delivery_info:{'delivery_tag': 2, 'routing_key': 'romeo-api', 'consumer_tag': '4', 'exchange': 'romeo', 'redelivered': False} headers={b'task': b'core.tasks.get', b'id': b'A70C67FF-FE5D-44EB-9451-3A6818CA84D7', b'lang': b'py'}}
```

**Comment by ask** [comment]
@jbg Thanks, for gathering that.  I guess we're in trouble considering we always encode strings in tables (hence also headers) as longstr :(

I'm not sure what decision went into that since it's inherited from amqp, makes sense of course since Python doesn't use arrays for data, but maybe it'd be faster for us to use shortstr for strings < 255

**Comment by ask** [comment]
inherited from amqplib*

**Comment by ask** [comment]
But I think this can be closed now as we currently encode everything into utf-8.  I guess as soon as someone needs to encode as bytes we will need to add some option to py-amqp.
