### ISSUE TITLE
Qpid Transport Deadlock

### ISSUE THREAD

**Issue by bmbouter** [celery/celery#2199]
It's possible that in some circumstances the Qpid transport could deadlock due to the use of threads within the Qpid transport. As a workaround, restarting the stuck worker should resolve the issue when it occurs. This issue is created to track the resolution of the bug, and document users who have experienced it.

**Comment by thedrow** [comment]
There isn't much to go on here.
Which circumstances? How to reproduce?

**Comment by bmbouter** [comment]
I don't think it can be reproduced. It was identified theoretically based on the fact that a thread is spawned.

To resolve this issue we need to eliminate the thread. I'm planning to do that with this fix [0]. I am waiting on the Qpid team to push an updated version of the qpid.messaging library to PyPI. That version is needed before I can merge my work into upstream Kombu. I've tested the prototype [0] locally and it works for me.

[0]:  https://github.com/celery/kombu/compare/3.0...bmbouter:qpid-transport-remove-threads?expand=1

**Comment by bmbouter** [comment]
@ask As I understand it a celery parent process that spawns children (ie: 1 child process with c=1) will only spawn them once, and will not spawn a new one for each task. Is that right?

Also regarding the potential deadlock, if it would occur do you expect it to occur immediately in the child after it is spawned, or could it happen randomly later?

Finally, I remember trying to use the --no-execv option to help prevent fork safety issues in the past, but I remember it not working. How is that related to this issue? Also, do you believe --no-execv is working currently?

**Comment by ask** [comment]
>@ask As I understand it a celery parent process that spawns children (ie: 1 child process with c=1) will >only spawn them once, and will not spawn a new one for each task. Is that right?

That's depending on the `--maxtasksperchild` option / `CELERYD_MAX_TASKS_PER_CHILD` setting.
It will also spawn a new process any time a process terminates for any reason. 

>Also regarding the potential deadlock, if it would occur do you expect it to occur immediately in the child >after it is spawned, or could it happen randomly later?

That depends on the cause of the deadlock!

If the transport is not async capable, and a process acquires the inqueue semaphore then gets terminated, the semaphore is not release, and the rest of the processes will not be able to acquire it again.

With threads started in the parent process, it's not easy to tell what happens, sometimes there's a mutex acquired in the parent at the time the child is forked, and when the child needs to acquire the same mutex it's already taken, and it's not possible to release it because the mutex in parent is now in a different memory space.

Other deadlocks can happen, no matter if the transport is async capable, or using threads, but these will
usually happen in the parent process (which will starve the child processes of tasks eventually, but they are technically not deadlocked just waiting for work).  In this case you will usually not see any active tasks in `celery -A proj inspect active`.

>Finally, I remember trying to use the --no-execv option to help prevent fork safety issues in the past, but >I remember it not working. How is that related to this issue? Also, do you believe --no-execv is working >currently?

The no-execv option does not help the case where the semaphore is acquired when a child process is killed, and I don't think the path of the worker using async-capable transports supports no-execv.

**Comment by bmbouter** [comment]
@ask Thanks for the response. I've got more questions ;-)

Qpid is an async capable transport so the first concern shouldn't apply. What is the `inqueue semaphore` is that a Celery semaphore?

Regarding the threading, that is a concern that applies so I want to understand it better. Say there are two threads in the parent process and it calls `os.fork()`. The "active" thread in the parent process will become the MainThread of the child process. Is that right? I expect that to be the thread whose code actually calls `os.fork()` based on an assumption that `os.fork()` is thread safe and therefore won't allow a thread switch to another thread until the call to `os.fork()`. Is that the case?

Can you more clearly explain the third case of deadlocks will would happen in the parent process? If its just waiting for work I don't consider that a deadlock. Is it just waiting for work?

**Comment by ask** [comment]
I don't know how forked processes start from the position of other threads, even if the thread itself didn't call `fork()`, but at least it happened often when using the multiprocessing/billiard pool.

Didn't you have a patch for removing the threads in qpid, in that case wouldn't it be better to test with that patch enabled?

The third case with children waiting for work, just means the parent is deadlocked so it's not sending the child processes any work.  The processes are working correctly, but the parent isn't.  It could be blocked (like hanging on an infinite loop, or waiting for a socket) or something else.

**Comment by bmbouter** [comment]
This has been fixed with the merge referenced above. The celery kombu code no longer spawns threads.
