### ISSUE TITLE
How to route a task to a different broker?

### ISSUE THREAD

**Issue by patrickwolf** [celery/celery#2298]
We got 5 branches and would need 5 brokers as the connection isn't always reliable.
I would like to use Redis as the broker.
What I'm missing is how to route messages/tasks between different brokers with Celery.

Is there a way to make a task which purpose it just is to forward a task to a queue on a different broker.
ie tasksRemotePEK is send of in branch LAX.
a worker in LAX picks it up and notices its for PEK
the worker forwards it to PEK
in PEK a worker finds the tasks and executes it.

How could this be setup please with Celery?
Thanks!

PS: I know that RabbitMQ supports the forwarding but it would mean deploying 5 virtual machines with RabbitMQ on them while Redis can just run as another service on our servers ie it would be much easier to deploy

**Comment by malinoff** [comment]
```
Is there a way to make a task which purpose it just is to forward a task to a queue on a different broker.
```
Sure. You can simply do exactly what [app.send_task](https://github.com/celery/celery/blob/v3.1.17/celery/app/base.py#L331) does using custom producer which may be connected to a different broker.

But this sounds like a tricky issue and I don't think I fully understand the general purpose of such setup.
If you care about high availability, you should use [clustered](https://www.rabbitmq.com/ha.html) rabbitmq as broker instead of redis. ([RabbitMQ in action](http://www.manning.com/videla/) may help with understanding its HA setup).
