### ISSUE TITLE
Celery Task priority

### ISSUE THREAD

**Issue by iT2afL0rd** [celery/celery#2372]
I'm using Celery with RabbitMQ, I have a task named 'scan', and producer named 'controller'. 
controller running at server A,and scan running on server B ~ Z. 
I use send_task('scan', [args_list]) when  I want scan to do something. 
I didn't find a way to implement task priority. I know there is one way to use two Queue, but I want something like 'send_task('scan', priority, [args_list])', the task with higher priority will be processed first. 

So how can I do it ?

**Comment by riqui99** [comment]
Hey first of all sorry for my english, and sorry for reopen the discussion.
I have the same issue, but I would need to send task in a queue with priority (rabbitMQ), but by running in a remote server. 
In such case, I can not use apply_async because the real code is in another server, Is there any way to use send_task and initialize Celery similar to: 

app = Celery(broker="amqp://user:passw@server_ip:5672")
app.send_task('fun_space.funcname', args=args, queue=queue) <-- define priority

Thank you very much!

**Comment by ask** [comment]
@riqui99,

The `app.send_task` method supports the same calling arguments as `task.apply_async` (which is a simple wrapper around app.send_task after all).

```py
    app.send_task('fun_space.funcname', args=args, queue=queue, priority=9)
```

The easiest way to define these tasks is to use task stubs:

```py

app = Celery(broker='amqp://')

@app.task
def add(x, y):
    ...
```

Now you can use canvas, chains, etc, and in 4.0 the arguments to your task will be checked when
you call them.

NOTE: The ellipsis (`...`) only works in Python 3, you have to use `pass` in Python 2.x.

**Comment by riqui99** [comment]
Hi @ask,
With your solution and adding the correct config (IMPORTANT my real problem), like:
self.app.conf['CELERY_QUEUES'] = (
   Queue('images', Exchange('default'), routing_key='images', queue_arguments={'x-max-priority': 3}),
)
in my sender celery, now runs perfect!

Thanks!!!!
