### ISSUE TITLE
Workers Not Re-Spawned After Hard Timeout

### ISSUE THREAD

**Issue by Erve1879** [celery/celery#2451]
I have workers running under supervisor on EC2. Broker SQS. I'm finding that workers are not being re-spawned after a TimeLimitExceeded exception. Supervisord reports that the workers are all running, but they do not process any tasks. I'm not sure whether the error is to do with supervisor not detecting the crash correctly (and therefore not auto-restarting the worker), or whether celery isn't re-spawning correctly......

Here's a pertinent log entry (the last logging from the hung worker):

````
WorkerLostError: Worker exited prematurely: exitcode 0.
[2015-01-12 23:03:33,253: ERROR/MainProcess] Task my.task_name[5c7e7085-4cd0-4939-bf2e-950ce78cce86] raised unexpected: TimeLimitExceeded(60.0,)
Traceback (most recent call last):
  File "/home/web/workers/venv/local/lib/python2.7/site-packages/billiard/pool.py", line 639, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
TimeLimitExceeded: TimeLimitExceeded(60.0,)
[2015-01-12 23:03:33,253: ERROR/MainProcess] Hard time limit (60.0s) exceeded for my.task_name[5c7e7085-4cd0-4939-bf2e-950ce78cce86]
[2015-01-12 23:03:33,867: ERROR/MainProcess] Process 'Worker-23' pid:2301 exited with 'signal 9 (SIGKILL)'
````

**Comment by scottanderson42** [comment]
We also tripped across this. SQS as well, Celery 3.1.17, Python 2.7.6, using both the prefork and solo pools. I haven't tested other pools yet.

[2015-10-20 10:42:32,499: ERROR/MainProcess] Task processing.tasks.ProcessingTask[330bfb14-cd81-4571-afce-af7d83fc7eb9] raised unexpected: TimeLimitExceeded(300.0,)
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/sp_app/local/lib/python2.7/site-packages/billiard/pool.py", line 639, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
TimeLimitExceeded: TimeLimitExceeded(300.0,)
[2015-10-20 10:42:32,500: ERROR/MainProcess] Hard time limit (300.0s) exceeded for processing.tasks.ProcessingTask[330bfb14-cd81-4571-afce-af7d83fc7eb9]

**Comment by ask** [comment]
Please use the all new async SQS transport in the development version, by installing
these dependencies: https://github.com/celery/celery/blob/master/requirements/dev.txt

We will not be spending time working on the old one, as they are not supported.
4.0 will add actual support for SQS using the new transport

**Comment by scottanderson42** [comment]
Well, I can't use a development version in my production, for one, and secondly have you conclusively shown that this is an SQS transport problem?

**Comment by ask** [comment]
The old SQS transport is using the fallback version of the worker, which means using threads in the worker and using the stock multiprocessing.Pool implementation.

Since 3.1 only the new async transports (amqp, redis, and sqs in 4.0-dev) are officially supported,
and the rest of the transports are experimental.  E.g. see the experimental status warning here:

http://docs.celeryproject.org/en/latest/getting-started/brokers/sqs.html

Using threads in the worker leads to deadlocks, since we are combining it with `fork()`, and using the stock multiprocessing.Pool shares a single POSIX semaphore between all child processes for sequential reads from the job queue; but if a process is killed while having acquired the semaphore there is no way to release it, so that also leads to a deadlock.

So it's not an SQS transport specific problem, but it's a problem specific to the transports using the non-async fallback worker path.

You're using an experimental transport in production that does not work, so why not swap that with an experimental version that could actually work? :)

**Comment by scottanderson42** [comment]
That makes sense, with the caveat that I am using concurrency=1. 

However, the experimental version we're using in production has problems only when a hard timeout is received, vs. an unknown number of problems with a developmental version that has not yet been vetted in our environment. :-) We've sent a few hundred million messages through the current SQS driver and this is the only problem we've seen.

I worked around the problem by setting a soft timeout that triggers before the hard timeout and haven't seen the issue since making the change.

For purposes of beginning to vet the new transport, can you point me to a discussion of using the new version with existing 3.1 code? I wasn't able to find a concise discussion of the new transports. Thanks!

**Comment by ask** [comment]
Yeah, it's usually a rather rare problem, but it can suddenly happen whenever a worker child process is killed abruptly (kill -9).  If you can work around the problem, then that's good!

There's not much discussion on the new SQS transport, as it was work I did for Nextdoor.  It does close almost all of the kombu SQS issues, and even supports things like long polling, so it's a huge improvement over the old one.

The usage is the same, and it should be backward compatible, but you cannot just drop it into celery 3.1 as it requires other changes in Kombu.
