### ISSUE TITLE
_store_result() got an unexpected keyword argument 'request'

### ISSUE THREAD

**Issue by geoom** [celery/celery#2462]
I have no idea why celery suddenly stopped working, probably missing some settings but I don't think so .... and code of views that runs celery tasks is the same, sentry only shows as follows:

![](http://i.stack.imgur.com/0KWzG.png)

It works locally (develop env) but in production it doesn't, I'm using django 1.4.2, djcelery 3.0.11 and celery 3.1.9, what do you think happening?

**Comment by browniebroke** [comment]
After running into the same issue, I believe this is due to incompatible versions of celery and django-celery. If you use celery 3.1.x, you need to upgrade to djcelery to >= 3.1

https://github.com/celery/django-celery/commit/374496c36640fe853d5f8acefa952971d87315b8#diff-07ac3142c20036ec08f58749fbd90e18

**Comment by geoom** [comment]
ok .. I will try later because I have to take a workaround, thnks for your help!
