### ISSUE TITLE
InconsistencyError with Redis driver (3.1.17)

### ISSUE THREAD

**Issue by dcramer** [celery/celery#2484]
We're trying to upgrade Sentry to 3.1 and we're hitting what seemingly isn't an error on our side (though I could be wrong). We use a router through an exchange, and it seems (at least w/ Redis) its complaining about a missing queue which shouldn't be used:

```
Traceback (most recent call last):
  File "/Users/dcramer/Development/sentry/src/sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "/Users/dcramer/Development/sentry/src/sentry/event_manager.py", line 469, in _save_aggregate
    is_regression = self._process_existing_aggregate(group, event, kwargs)
  File "/Users/dcramer/Development/sentry/src/sentry/event_manager.py", line 526, in _process_existing_aggregate
    }, extra)
  File "/Users/dcramer/Development/sentry/src/sentry/buffer/base.py", line 37, in incr
    'extra': extra,
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/celery/app/task.py", line 555, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/celery/app/base.py", line 353, in send_task
    reply_to=reply_to or self.oid, **options
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/messaging.py", line 168, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/connection.py", line 436, in _ensured
    return fun(*args, **kwargs)
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/messaging.py", line 184, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 521, in basic_publish
    message, exchange, routing_key, **kwargs
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/transport/virtual/exchange.py", line 60, in deliver
    for queue in _lookup(exchange, routing_key):
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 612, in _lookup
    self.get_table(exchange),
  File "/Users/dcramer/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/transport/redis.py", line 723, in get_table
    raise InconsistencyError(NO_ROUTE_ERROR.format(exchange, key))
InconsistencyError:
Cannot route message for exchange 'counters': Table empty or key no longer exists.
Probably the key ('_kombu.binding.counters') has been removed from the Redis database.
```

Relevant settings:

https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py#L307

Router:

https://github.com/getsentry/sentry/blob/master/src/sentry/queue/routers.py

Feel free to throw this in a new ticket if it makes sense.

**Comment by dcramer** [comment]
It's not entirely clear to me why Celery won't recover from this, but this is due to our test fixtures calling flushdb on Redis after each run.

I still consider this a problem with Celery, or at the very least a pattern should be documented to deal with this in test fixtures (and likely in prod, without restarting the process).

**Comment by nickjj** [comment]
I'm seeing this issue too with Redis as a backend. Here's my versions

```
redis==2.10.3
celery==3.1.18
```
I had an uptime on Celery for 2 weeks (wish I could give you an exact time span but that's all I have in my logs) and after this point I started to get:

```
InconsistencyError:
Cannot route message for exchange 'celery': Table empty or key no longer exists.
Probably the key ('_kombu.binding.celery') has been removed from the Redis database.
```

I was able to resolve the issue by restarting Celery but that seems hacky.

**Comment by ask** [comment]
If you are sending a task with a queue argument, e.g. `task.apply_async(queue='foo')` or rely on the default queue then when sending a task celery will:

1) declare the exchange and queue
   this adds the _kombu.binding key if it does not exist
2) send the message by looking up the routing key in the _kombu.binding table

And now the queue also exists in case someone is sending a message using only exchange/routing_key pairs.

So for this error to happen someone or something must have removed the key between these steps.

It's definitely a rather quirky way to do this, but it mimics the API of the AMQP protocol.

A solution may be to use anon exchanges, which will bypass this step completely,
but that doesn't work with Celery right now so have to add that in.

**Comment by nickjj** [comment]
@ask Do you know when this patch will make it into the next release?

**Comment by ask** [comment]
That patch will only be in 4.0, as it's too risky to just put in a bugfix release.

Helping test 4.0 will get that out faster! It's in a release candidate right now

**Comment by nickjj** [comment]
@ask Ok great, I will try it out in the near future. In this case I'm not sure if it's a direct bug of Celery. In fact, if this were fixed I never would have noticed my Redis instance was compromised.

If anyone else sees this, your Redis instance may have been compromised. Please read through https://github.com/celery/kombu/issues/236#issuecomment-163071633.

**Comment by razerraz** [comment]
Redis 3.2.1 / Celery 3.1.17 / Django  1.9.8

I'm facing the same issue in my django project using celery and redis ampq 
All scheduled tasks are running well from djcelery, but after a couple of days the gunicorn server used for web frontend do not accept tasks with the same error message.

With rabbitmq, the problem doesn't occur 
Redis can't hacked, since the site is entirely running without any internet link

I have discovered that just starting a new django instance in shell and queeing a task in it solve the problem.
I just launch this script every 12 hours : 
`from __future__ import absolute_import, unicode_literals
import os, sys, django
sys.path.append(os.path.dirname(__file__))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings")
django.setup()

from core.tasks import do_nothing_task
do_nothing_task.delay()`

**Comment by hgdeoro** [comment]
Hi. I can read in the official Celery docs: 

> configure the redis-server to not evict keys by setting the **timeout** parameter to 0 in the redis configuration file

But based on official redis docs (https://redis.io/topics/clients and https://raw.githubusercontent.com/antirez/redis/4.0/redis.conf) **timeout** is not related to key eviction. What  **timeout = 0** does is disable detection and disconnection of idle clients:

> you can configure a timeout, so that if the client is idle for more than the specified number of seconds, the client connection will be closed.

So, I understand the docs are not precise, and I can use key eviction in my Redis instance.

**Comment by hedleyroos** [comment]
Unfortunately https://github.com/celery/kombu/issues/236 is locked and my observation would have been better to add there, but adding it here to avoid creating a new issue.

When running celery over a slow network, basically anything outside of a LAN, I get the error intermittently. The issue seems to be in kombu, not celery, where the response from the Redis server to the worker takes a long time to arrive. I haven't been able to pin the exact problem down yet, but I would guess it's because kombu expects callbacks to have fired when they haven't yet. I also haven't been able to simulate the failure using toxiproxy so it's quite annoying to debug because you must route traffic over the internet.

My workaround (I concede I don't know why it works) is to set `broker_heartbeat` to a ridiculously high value like 300. So far that has solved the issue for me.

Finally note that when all elements from a Redis set are removed the key is also removed. It is completely possible for the key to disappear and reappear when you have many workers. The "something" that removes the key is kombu itself.

**Comment by mabouels** [comment]
@hedleyroos Was wondering if you got any further on this issue?

We've the exact same observation when the celery workers and Redis are connected via a slow LAN. And it definitely only happens when we upgrade from 

software -> celery:4.2.1 (windowlicker) kombu:4.2.1 py:3.5.0
            billiard:3.5.0.2 py-amqp:2.1.4

to

software -> celery:4.3.0 (rhubarb) kombu:4.6.3 py:3.5.0
            billiard:3.6.0.0 py-amqp:2.5.0

We didn't change the the version of Redis (3.2.5).

**Comment by hedleyroos** [comment]
@mabouels I gave up. The code is very hard to debug, and I am still stuck on Celery 4.1.1. It is stable.

**Comment by hajarada** [comment]
Facing this issue with if and only if I have two sets of workers using different queues in redis. if I go back to celery 4.1 the problem goes away. if I use the same queue for all workers (rather than two queues) the problem goes away. the odd part is the way the problem happens. if I bring up all the workers using queue 1, they come up fine. then when i start bringing up the workers using queue 2, for every one of those workers, as soon as it comes up, a worker using queue 1 crashes.
any chance anyone is still looking into this issue?
