### ISSUE TITLE
celery 3.1.17 causes deadlock in report.py with django

### ISSUE THREAD

**Issue by shayneoneill** [celery/celery#2485]
There seems to be a report for this for an earlier version but it appears to still be the case so I gather this is a regression.

django 1.7
python 2..7
celery 3.1.17
debian linux w/virtualenv

When importing tasks.py from celery into a django process , with @shared_task decorated tasks, report.py locks up, apprarently on self._lock

Tracing it with python lands here:

      --- modulename: registry, funcname: populate
     registry.py(66):         if self.ready:
     registry.py(71):         with self._lock:

strace reports its a 'futex' that is locking. 

Am I doing this wrong?

**Comment by shayneoneill** [comment]
Note:
The import celery; celery.current_app.task('blah',args=[blah]) approach does not lock.

**Comment by Urth** [comment]
This is caused by django.setup() being called twice, once by django itself and the second time by celery. During the setup django will [populate](https://github.com/django/django/blob/master/django/apps/registry.py#L58) the registry with a non-reentrant lock and because there is no timeout the process will hang.
I've seen this happen with the master branch of django-celery (for the DatabaseScheduler) but this can happen with any project that causes celery to call [validate_models](https://github.com/celery/celery/blob/master/celery/fixups/django.py#L153) during the initial django.setup()

**Comment by shayneoneill** [comment]
Just adding a note, I probably can't assist any further following this up, as I've moved on from the job where the code in question arose. Alas.

**Comment by thedrow** [comment]
I don't really know how to resolve this since there's no flag that indicates that setup is already called.

**Comment by ask** [comment]
This seems more to be a bug in Django, as they have no protection from this happening and there's nothing we can do to protect it.

Django.setup is only called by celery 1) before importing the task modules though, and 2) after each child process forks. so are you certain that you do not call django.setup somewhere else?

**Comment by ask** [comment]
Actually, Celery itself will not call `django.setup` when you import a `tasks.py` module at all, so this call must be coming from something else.

If you still have the issue, then please monkeypatch django.setup to give a traceback.
