### ISSUE TITLE
Celery workers do not respect queue

### ISSUE THREAD

**Issue by tino** [celery/celery#2508]
I run a setup as I described here: http://stackoverflow.com/questions/28456500/celery-how-to-separate-different-environments-with-different-workers
```
$ celery -A website.celery list bindings
Queue                        Exchange                     Routing Key
----------------             ----------------             ----------------
myserver_development         celery                       celery
myserver                     celery                       celery
myserver_staging             celery                       celery
```

When I trigger a task in the development environment (with `CELERY_DEFAULT_QUEUE = 'myserver_development'`), I see the task being executed in all three queues.

**Comment by ask** [comment]
You have to set all of `CELERY_DEFAULT_QUEUE`, `CELERY_DEFAULT_EXCHANGE` and `CELERY_DEFAULT_ROUTING_KEY`.  Otherwise you will end up with three queues all bound to the same exchange and routing key.

Or use the method here which will set it up explicitly:
http://docs.celeryproject.org/en/latest/userguide/routing.html#changing-the-name-of-the-default-queue
