### ISSUE TITLE
Celery Kickstarter Ideas

### ISSUE THREAD

**Issue by thedrow** [celery/celery#2655]
In order to get this project going we're going to raise funds using Kickstarter.

**If you'd like to propose yourself as a candidate for funded work please comment here.**

List of tasks we need to do before launching the Kickstarter campain:
- [ ] Define goals.
- [ ] Define stretch goals.
- [ ] Create a video with our proposal.
- [ ] Write the proposal text.
- [ ] Estimate our required budget.
- [ ] Create issues for each goal we agree on.

List of proposed goals as discussed with @malinoff on IRC:
- [ ] Kafka broker support.
- [ ] Using Etcd for discovery of Celery workers instead of using the broker.
- [ ] Using Consul for discovery of Celery workers instead of using the broker.
- [ ] librabbitmq rewrite that will allow it to support Python 3 and PyPy. https://github.com/celery/librabbitmq/issues/13
- [ ] Bug fixes for critical bugs in Celery that cause Celery to stop consuming tasks. See the **[Worker Hangs label](https://github.com/celery/celery/labels/Worker%20Hangs)** and **[Worker Crashes label](https://github.com/celery/celery/labels/Worker%20Crashes)**
- [ ] AWS Kinesis broker support.
- [ ] Better support for our experimental brokers.
- [ ] Increasing test coverage, general refactoring, documentation improvements.
- [ ] Automatic autoscaling across the cluster when the task backlog is high or low.
- [ ] Manually increasing/decreasing the pool size of a worker for a specified period of time.
- [ ] An official Docker container for Celery.
- [ ] A deployment tool for Celery and the different brokers.
- [ ] Deprecation of the old threadpool worker pool and introduction of a billiard based thread pool (Which eventually be valuable for PyPy-STM).
- [ ] Broker health checks.
- [ ] Automatic detection if a worker might be hanging. #2668

**If you'd like to propose a goal please comment here**

**Comment by thedrow** [comment]
RabbitMQ has a healthcheck option if the management API is alive.
Performing a GET request on /api/aliveness-test/vhost will enqueue a message on a test queue and consume it in order to verify that everything works correctly.

**Comment by minuscorp** [comment]
I think another interesting goal might be the programatically spawn of new workers on-demand. Many web applications are Platform as Service oriented where the user can choose the number of workers to make some tasks. Maybe you can tag some machines as deployers of workers (with maximum workers per machine) and let the user manage how many workers and for how much time  are running to process a bunch of tasks.

**Comment by thedrow** [comment]
@minuscorp You can already use ```celery control``` to increase/decrease the pool size.
See http://celery.readthedocs.org/en/latest/reference/celery.app.control.html#celery.app.control.Control.pool_grow
However you can't configure for how long these new workers would run. That's a good idea.

**Comment by minuscorp** [comment]
@thedrow I'm not talking about about how many processes a worker can spawn, but to spawn the worker itself on demand to serve an user tasks, because you can only make a worker process an user tasks for the queues the worker is listening to.
An user has an unique ID, queue named with that ID and on demand created workers that consumes on that queue.
Changing pool size is not suitable in most cases because vertical scalability (add more processes in one machine) has a limit, but having multiple physical machines waiting to spawn workers with a fixed pool size depending on its capabilities (typically 2n+1 pool size, where n is the core number of the machine), I'm more talking about make Celery on demand horizontal scalable.

**Comment by malinoff** [comment]
@minuscorp how would Celery know on which servers it can spawn its workers? Which message bus will be used? We can't use kombu, since there are no daemons listening a broker. If that would be SSH, so how should Celery know which credentials to use? From which node this process will be initiated? What about timeouts and dead servers?
I believe this task is from another area, it's more about orchestration and virtualization. If you want to scale horizontally, you can already use AWS with autoscaling group, you can use custom images for all hypervisors that can provision a Celery worker on startup. All you need to do is to have *something* that will trigger the bootup. And in my opinion, Celery has nothing to do with it.

**Comment by minuscorp** [comment]
I've implemented in someway this behaviour doing what you say, I've got machines with spawned workers wich can spawn other workers on user needs, and using broadcast messages I can make "parent workers" spawn new workers (which uses the user) and broadcast message to kill the child workers.
I just was wondering if could be implemented a daemon or something like that which can listen certain queues and spawn workers and detatch from them. This daemon could spawn new workers on demand when there's free workers slots on the machine, like a process pool but for number of workers.

I try to give some ideas, I've been working with Celery from almost a year, I think it's a great task queue and that it could've be even better. I'm just explaining some needs I've encountered during my work with the library, maybe some ideas could be nice to add, maybe this isn't one of them.

**Comment by malinoff** [comment]
@minuscorp you didn't say which message bus you're using for that. Also, how would on-demand workers receive the code that is written by user? `git clone`?

I really don't want Celery to be a combine for everything, that's why I'm too skeptical about such proposals, and I know how to achieve that with existing tools without spending lots of time for the implementation that might not work as expected and will definitely introduce more bugs.

**Comment by minuscorp** [comment]
All machines are prepared to run the tasks because they already have the code. In my study case, the user can only choose to execute a number of tasks on data (is a real-teime distributed analysis web application). The machines just need "someone" (a daemon I think) to spawn a max number of workers, and let the tasking begin.

**Comment by malinoff** [comment]
@minuscorp sorry, but in your case you're deploying your app, and Celery is framework which shouldn't really be deployed without user-written code. And I think that your case is *very* opinionated and can't be expanded on framework level. Take a look at Jenkins and ansible instead.

@thedrow what do you think about this?

**Comment by thedrow** [comment]
I think he is talking about the celery deployment tool you're were talking on in our IRC conversation.
I'm not very fond of the idea anyway since I'd rather leave the configuration management to configuration management tools.

**Comment by PhilipGarnero** [comment]
Hey guys !
I think this is a great idea and I'm pretty sure it will success.

Celery needs to speed up and become more stable and reliable as well as attractive.
To achieve that, I think we need more organization, at least about the future.

Currently, I haven't be able to find a roadmap or anything similar.
We need to define what is our long distance vision and what we are currently working on, that's why I think two roadmaps (major and minor) would be very beneficial for the project and will encourage maintainers to help achieving goals.
We also need @ask help on this as it is his vision and he is probably already working on different subjects.

Now, for the ideas :
- Becoming an universal software: by that, I mean being able to use celery independently from the language. I saw that [some work](http://docs.celeryproject.org/en/master/internals/protocol.html#definition) already started but it is unclear how it will work and what we can do to help. This would surely attract a lot of people and celery would probably become a reference. So, making the task api and canvas available and being able to easily implement new languages support is a must.
- Walking through issues and resolve as much as possible. Currently we have like 270 issues and it is not really showing our users this is a stable project.
- :+1: Kafka and aws brokers, docker container, docs and refacto.

I'm not sure if I'll be available often but I will gladly offer my help

**Comment by thedrow** [comment]
The first thing we need to do is find someone who'll be willing to take part in implemeting the features highlighted above and to further discuss each of them to see if they are a good fit for the kickstarter project.
We haven't got the time to take paid work ourselves as of now so we need volunteers, preferably guys who worked with Celery before.

**Comment by thedrow** [comment]
Looks like this isn't going to happen. Closing.

**Comment by auvipy** [comment]
I am surprised I didn't notice this effort earlier!!!
