### ISSUE TITLE
Need binary distributions for Win64 and 32

### ISSUE THREAD

**Issue by UmAravind** [celery/celery#2717]
I am new to celery, i am looking for binary distributions for celery and pika. i have gone through this site https://pypi.python.org/pypi/celery/3.1.18, but it is very confusing. can some one help me on this?

**Comment by malinoff** [comment]
Why do you need binary distributions? You can easily install celery using
```bash
$ pip install celery
```
command.

**Comment by UmAravind** [comment]
i have to provide celery through our  application installer so. i need binary distributions

**Comment by malinoff** [comment]
Can't your application installer use `pip` to install celery?

Building binaries requires a build farm of different OSes and different architectures, and since celery is fully open-source and free and is maintained by volunteers I don't think we will ever provide prebuilt binaries unless somebody will give us such farm.

However, if you really want to have binaries, you can use tools like [pyinstaller](https://github.com/pyinstaller/pyinstaller/wiki) or tools provided by the standard library: https://docs.python.org/2/distutils/builtdist.html.
