### ISSUE TITLE
Task register vs instantiate

### ISSUE THREAD

**Issue by xBeAsTx** [celery/celery#2758]
I found logical problem for tasks class. Basically i just want catch my additional parametrs inside constructor of my task.

Something like this:
```python
class MyArgsParse(bootsteps.Step):
	def __init__(self, worker, myarg, **options):
		logger.warn('CATCH ARGS')
		MyTask.MY_ARG1 = myarg

app = Celery(name)
app.config_from_object(MyConfig)
app.user_options['worker'].add(Option('--myarg', type=str, default='test'))
app.steps['worker'].add(MyArgsParse)

class MyTask(Task):
	MY_ARG1 = None
	
	def __init__(self):
		self.my_foo_obj = Foo(MyArg1)

	def run(self, param1):
		...
		return my_foo_obj.get(param1)
```

First of all as you can see it's ton-of-code here. Secondly I obviously must store my arguments inside static properties in class - it's not so good.

But main problem is that it's not work at all. Because of celery auto-"register" function:

```python
def register(self, task):
        """Register a task in the task registry.

        The task will be automatically instantiated if not already an
        instance.

        """
        self[task.name] = inspect.isclass(task) and task() or task
```

So task registred before worker parametrs parsing and trying instantiating Task-class.
And as result MyArg1 not filed when \_\_init\_\_ was called.

So I want ask you about how deal with this problem. May be we don't need instantiate class on register, but just store Task types and instantiating on some bootstep process?

And may be we need simplify argument passing to tasks?

**Comment by malinoff** [comment]
Sorry, but it is very difficult to understand your issue.

However, I can suggest you to avoid subclassing `Task` class and trying to provide custom arguments in its `__init__`. Tasks shouldn't be used to store any user-provided state, and that's why subclassing "feature" will be removed in 3.2.

Instead I can suggest to rewrite your code like this:
```python
from celery import task

MY_ARG1 = None
def get_foo():
    return Foo(MY_ARG1)

@task
def sometask(*args, **kwargs):
    foo = get_foo()
    foo.do_something()
```

Your bootstep should change this `MY_ARG1` global variable if needed.

**Comment by xBeAsTx** [comment]
My project it's not simple celery-task like 'return 2+2' as in documentation. I think what you suggested - a bad way. And I think it's really bad idea remove sublassing task feature, because this allows use OOP in tasks design. What if I want create my "basetask" with some additional functionallity which I would use in all my tasks and more-more... It's convenient and flexible. That's why I think celery must support OOP subclassing tasks.

I think we just need fix Celery behaviour here probably.

For deep undestand problem I wrote small demo app for you:
```python
import os, traceback, time

from celery import Task, Celery, bootsteps
from celery.bin import Option

class MyArgsParse(bootsteps.Step):
    def __init__(self, worker, myarg, **options):
        print('MyArgsParse - Catch args')
        MyBaseTask.MY_ARG1 = myarg

class DefaultConfig:
    BROKER_URL = 'amqp://<user>:<pass>@<host>/<vhost>'
    BROKER_POOL_LIMIT = 20
    BROKER_CONNECTION_MAX_RETRIES = 0

    CELERY_RESULT_BACKEND = 'amqp'
    CELERY_ACKS_LATE = True
    CELERY_TRACK_STARTED = True
    CELERY_ACCEPT_CONTENT = ['json', 'msgpack', 'yaml']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'

    CELERYD_PREFETCH_MULTIPLIER = 1
    CELERYD_TASK_LOG_FORMAT = '[%(asctime)s] [%(levelname)-5s] [%(processName)-6s] [%(task_name)s %(task_id)s] %(message)s'
    CELERYD_LOG_FORMAT = '[%(asctime)s] [%(levelname)-5s] [%(processName)-6s] %(message)s'

app = Celery('demo')
app.config_from_object(DefaultConfig)
app.user_options['worker'].add(Option('--myarg', type=str, default='test'))
app.steps['worker'].add(MyArgsParse)

class Checker(object):
    def __init__(self, file_path):
        if file_path:
            self.loaded_obj = self.load_file(file_path)

    def load_file(self, file_path):
	# Emulate highload function
	time.sleep(60000)
	return None

    def check(self, param1):
	# Search in our self.loaded_obj by param1...
	return 76

class MyBaseTask(Task):
    MY_ARG1 = None

class MyTask(MyBaseTask):

    def __init__(self):
	print('MyTask.__init__')       
	print('MY_ARG1 = %s' % MyBaseTask.MY_ARG1)
	#print('------------------ TB ------------------ ')
	#traceback.print_stack()
	#print('---------------------------------------- ')
	self.checker = Checker(MyBaseTask.MY_ARG1)

    def run(self, param1):
	print('MY_ARG1 = %s' % MyBaseTask.MY_ARG1)
        return self.checker.check(param1)
```

Here is my output on start celery worker:
```
>celery worker -A demo -Q demo -c 1 --myarg=12312
MyTask.__init__
MY_ARG1 = None
MyArgsParse - Catch args

 -------------- celery@PC v3.1.17 (Cipater)
---- **** -----
--- * ***  * -- Windows-8-6.2.9200
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         demo:0x32d5c50
- ** ---------- .> transport:   amqp://.../tasks
- ** ---------- .> results:     amqp
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ----
--- ***** ----- [queues]
 -------------- .> demo             exchange=demo(direct) key=demo


MyTask.__init__
MY_ARG1 = None
[2015-08-12 13:40:21,450] [WARNING] [Worker-1] MyTask.__init__
[2015-08-12 13:40:21,450] [WARNING] [Worker-1] MY_ARG1 = None
[2015-08-12 13:40:22,479] [WARNING] [MainProcess] celery@PC ready.
```

As you can see __init__ function was called two-three times (!) and first time it was called before "MyArgsParse - Catch args" message was shown. As I said in previous bugnote it's because first time it's called when task autoregistred inside of celery. So my question is - why it's needed? May be celery don't need do that?

**Comment by malinoff** [comment]
No, you're wrong about using OOP for tasks. It is convenient from the first glance, but has enormous issues in the long run.
If you are a good programmer, you should follow SOLID principles (or at least some of them) which basically teach you that you shouldn't mix different things in one atomic piece of code (function, class or module).

What you're trying to do is to mix task handling, task invocation, task instantiation and your custom logic above all of that. According to SOLID, you're doing it wrong, and this will never be supported like you want it to be supported.

Please, stop thinking about tasks as a silver bullet (or god objects) and use dependency injection, write adapters and instantiate them in your task functions. Otherwise you will fail horribly.

**Comment by xBeAsTx** [comment]
It's not about my good programming skills. It's about your project. You put it in this way and documented it, so you must clarify things.

You really think that your code do it in a good way?
```
MY_ARG1 = None
def get_foo():
    return Foo(MY_ARG1)
@task
def sometask(*args, **kwargs):
    foo = get_foo()
    foo.do_something()
```

Some shity global vars with no multi-thread supporting? With task-method that can't have any class specified variables!? Where I must store them? In global namespace? Like in 80th? Are you crazy?

> you shouldn't mix different things in one atomic piece of code (function, class or module).

I absolutely agree with that and I don't want do that! But you don't allow me. Because you have some issues in architecture of Celery. 


>What you're trying to do is to mix task handling, task invocation, task instantiation and your custom logic above all of that.

That not I mixed. It's you mixed everything. Just clarify it and separate them. As I offering with first post in this topic.

I just want put everything on right place. Not in global namespace like you offer me with your code. But inside my special task only wich one use my "checker" object. And catch arguments inside tasks without dancing with a tambourine.

So for now I just want ping @ask here... for his opinion

**Comment by ask** [comment]
This has been discussed in the past I think, but sadly I cannot find it now.

I agree that having a global instance of the task class is confusing, and it would be nice if there was one
instance per task invocation.

But it's important to remember that a task class is dual in purpose:

1) It's used as a client for the task (e.g. sending the task with `.delay`).
2) It's used as a server for the task (`.run()`).

In hindsight composition could have been used so that you have something like `FooTaskClient(FooTask)`, where the responsibilities are separate (my toy actor framework `cell` uses
this approach).

Since `Task.__init__` is not just called in the worker, but for every client as well, you are not recommended to use it at all (unless you know what you're doing).

You don't have to rely on global variables though, usually the best solution is using `cached_property` to delay initialization of the value until you actually need it:

    class MyTask(Task):
        MY_ARG1 = None

        def run(self, param1):
            return self.my_foo_obj.get(param1)

        @cached_property
        def my_foo_obj(self):
            return Foo(self.MY_ARG1)

The recommendation is to use task classes only for shared functionality, and make concrete
tasks using the `@task` decorator:

    from celery.utils import cached_property

    class FooTask(Task):
        abstract = True

        @cached_property
        def foo(self):
            return Foo()

    @app.task(bind=True, base=FooTask)
     def something(self):
         return self.foo.something()


Also note that in this case `self.foo` will be shared across task invocations occurring in the same process,
if you want to have a separate `self.foo` for every task request, and that even cannot be used by
multiple threads at the same time you should store it on the task request instead:

    class FoTask(Task):
        abstract = True

        @property
        def foo(self):
            try:
                return self.request.foo
            except AttributeError:
                foo = self.request.foo = Foo()
                return foo


You can also argue that since the constructor of an object should never contain side effects (like opening a file, performing a network request, or glob forbid starting threads), lazy evaluation is preferred
anyway.

**Comment by xBeAsTx** [comment]
Thanks a lot for explanation @ask , now it has become much clearer
