### ISSUE TITLE
task decorator and doctests

### ISSUE THREAD

**Issue by dchanm** [celery/celery#2763]
Celery 3.1.18
Python 3.4.0

doctests don't appear to work when using the task decorator.

```python
from celery import Celery
app = Celery()

@app.task
def add(x, y):
    """
    >>> add(1, 2)
    3
    """
    return x + y

def mul(x, y):
    """
    >>> mul(1, 2)
    2
    """
    return x * y
```

Output
```
$ python -m doctest -v tasks.py
Trying:
    mul(1, 2)
Expecting:
    2
ok
1 items had no tests:
    tasks
1 items passed all tests:
   1 tests in tasks.mul
1 tests in 2 items.
1 passed and 0 failed.
Test passed.
```

I expected the add doctest to run as well. There appears to be some weird interaction between the PromiseProxy object and doctest. At first I thought the docstring wasn't preserved, but I see the docstring if I print add.\_\_doc\_\_.

The only thing I can think of is something similar to fabric/fabric#421

**Comment by ask** [comment]
I'm not sure what we can be expected to do other than having a valid  '__doc__' attribute?

Whether the object is a function, class, method or something else shouldn't really matter to doctest.

You can use `@app.task(lazy=False)` to return a concrete task instead of a proxy.
That means the app will finalize, but that is usually not a problem unless you have some sort of lazy app configuration going on.

**Comment by ask** [comment]
Closing this, as we don't have the resources to complete this task.

May be fixed in master, let's see if comes back after 4.0 release.
