### ISSUE TITLE
Task output log unreadable

### ISSUE THREAD

**Issue by satish-gathole-driveu** [celery/celery#2777]
Celery version: 3.1.18
RabbitMQ broker
I have following configuration but getting unreadable logs
BROKER_URL = 'amqp://guest:@144.55.18.33//'
CELERY_RESULT_BACKEND = 'amqp'
CELERY_TASK_SERIALIZER='json'
CELERY_RESULT_SERIALIZER='json'
CELERY_ACCEPT_CONTENT = ['pickle']

*Output:*
The full contents of the message body was: body: '\x80\x02}q\x01(U\x07expiresq\x02NU\x03utcq\x03\x88U\x04argsq\x04]q\x05U\x05chordq\x06NU\tcallbacksq\x07NU\x08errbacksq\x08NU\x07tasksetq\tNU\x02idq\nU$e5a350b8-ef08-42ea-93b7-603f247d882dq\x0bU\x07retriesq\x0cK\x00U\x04taskq\rU"communication.tasks.send_sms_asyncq\x0eU\ttimelimitq\x0fNN\x86U\x03etaq\x10NU\x06kwargsq\x11}q\x12u.'

How can I get readable output???

**Comment by malinoff** [comment]
This is a debug message used mainly to figure out any issues with malformed task bodies. However, you issue is, I believe, is that your workers configured to accept only `pickle`d content, while you're sending `json` serialized data.
Either accept `json` too, or use `pickle` serializer. Note that the latter is not the best idea due to security concerns.

Please, feel free to reopen this ticket if my suggestion doesn't work for you.
