### ISSUE TITLE
problem with big data transfer  

### ISSUE THREAD

**Issue by codepython** [celery/celery#2841]
hi:
   I have encountered a problem which is raised when I transfer larger data ,it will obviously slow the program's execution . but I can not find the reason .

Is there suggestion here?

**Comment by malinoff** [comment]
Hi, celery wasn't designed for transferring vast amount of data to workers (mostly because brokers cannot properly do that, e.g. http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2012-March/018724.html)
You should use tools designed for file transferring instead, like scp, rsync, sftp or http (via external web server).
