### ISSUE TITLE
AsyncResult.get(propagate=False) strange behaviour when calling task with soft_time_limit and retries

### ISSUE THREAD

**Issue by unikoid** [celery/celery#2846]
Hello everybody,

I'm just playing with celery (v.3.1.18) and I found some strange behavior. I have a task with soft_time_limit set which does retry if this limit has been exceeded. The task is quite simple, this is simulation of the situation whether the task that has exceeded its time limit is considered stuck and should be retried:
```python
app = Celery('worker', backend='redis://', broker='redis://')

@app.task(bind=True, soft_time_limit=5, default_retry_delay=1, max_retries=10)
def do_smth(self, x):
    try:
        sleep_time = randint(0,10)
        print(sleep_time)
        sleep(sleep_time)
        print('return')
        return x**2
    except SoftTimeLimitExceeded as e:
        raise self.retry(exc=e)
```
I have main application that just calls that task and waits for result:
```python
res = do_smth.apply_async((10,), retry=True)
print(res.get(propagate=False))
```
And this application has rather strange behaviour. Sometimes it waits until the task returned its value and prints `100`, even if task exceeds its time limit and retries. But sometimes, usually when running just after the worker startup, it returns immediately after first SoftTimeLimitExceeded event and prints `SoftTimeLimitExceeded(5,)`.

I suppose, the correct behavior is the the first one and the former one is a bug. Am I right?

Here are the logs, that demonstrate the issue:
Worker log: https://gist.github.com/unikoid/2caabc08eee18cab5be4
Main application log: https://gist.github.com/unikoid/8eda6888840dbc4cf44f

**Comment by ask** [comment]
It's not safe to retry in a soft time limit handler!

This is because not only is your task body wrapped inside this handler, but so is also the celery handlers used to send results etc.  So your task may return after 4.99999 seconds, and then storing the result will exceed the timeout.

If you want to retry on a timeout I suggest you add timeouts to the task itself instead of using --soft-time-limit, e.g. if you are performing a HTTP request, then add a timeout to that request.

This is how timeouts should be handled in general, and time limits only used as a last resort if manual timeouts fail, or to detect tasks where you are not handling timeouts manually yet.
