### ISSUE TITLE
Deprecate threadpool backend

### ISSUE THREAD

**Issue by piotrmaslanka** [celery/celery#2891]
Having encountered a hazard in #2869, I examined some other Celery backends. None of them is thread-safe enough to use with threadpool.

This raises an open question - is Celery internally thread-safe enough to warrant supporting threadpool? I know this is a borderline use case, but I think it's better to deprecate threadpool backend than risk users enabling it and getting blown up on race conditions.

Threadpool library is not maintained, and better solutions like gevent/eventlet exist.

**Comment by ask** [comment]
I haven't delved to much into it, as the thread pool is still experimental.

The result backend would only need to support a thread-safe publish operation, as consuming results is generally discouraged in a worker.

The amqp/rpc backends seem to support that, the redis backend I'm not sure of but may be depending on the thread safety of a py-redis connection pool.

The worker itself is thread safe (as long as you don't use the prefork pool), and any thread safety issue should be bug.

I definitely don't think  you should use the thread pool in production, maybe that is not communicated clearly.

**Comment by thedrow** [comment]
We should be using another thread pool library or provide one in billiard to match multiprocessing.ThreadPool. The threadpool library is old and I don't believe it's maintained anymore.

**Comment by ask** [comment]
I removed the thread pool for now.  Let's see if anyone has any ideas on making a good one in the future.

It's always been marked as experimental so is not covered by deprecation policy.

**Comment by DDevine** [comment]
I have a use-case for which threaded workers are required! 

I need to interface with an embedded system that only has 8 ports available - and other things on the network may also require ports - so I need to ensure that Celery only has a **single** connection object in use. With threaded workers I can share that connection object. I cannot use Eventlet workers due to blocking IO. I have a dodgy Rube Goldberg work-around with single-process workers, but this sucks.

I'd prefer to keep using Celery - but I'm not really up to fixing Celery internals (as in, maybe I could hack together a ThreadPool but it would likely not be suitable for inclusion in Celery). 

Any ideas?

**Comment by NicolasLM** [comment]
I have recently re-discovered many pains related to the use of `fork`. Plugging Celery into an application designed with threads in mind is somehow tricky as the result must be both thread-safe and fork-safe.

I can help develop and maintain a threaded worker for Celery. @ask would this be valuable for the project?

**Comment by thedrow** [comment]
Yes it would. The implementation has to be based on `concurrent.futures` since we plan to utilize it with asyncio in Celery 5.

**Comment by NicolasLM** [comment]
May I suggest creating a new issue with the technical requirements for this new feature?

**Comment by thedrow** [comment]
Will do.
