### ISSUE TITLE
user options not properly populated

### ISSUE THREAD

**Issue by ArminGruner** [celery/celery#2929]
As described in http://docs.celeryproject.org/en/latest/userguide/extending.html#id11,
new command line options can be added to the worker. The docs state that optparse is used to process the options, so I would assume that other mimics of optparse would also work. 

However, type conversion does not seem to work: As seen by the snippet below, a user supplied argument is not properly converted into an integer.

    from celery import Celery, signals
    from celery.bin import Option

    app = Celery()
    app.user_options['preload'].add(
        Option('-N', '--number', default=10, type="int", help='Number to use.'),
    )

    @signals.user_preload_options.connect
    def on_preload_parsed(options, **kwargs):
        number = options["number"]
        print type(number), number

$ celery worker -b redis:// -A test_celery -N 200
`<type 'str'> 200`

**Comment by ask** [comment]
These are preload arguments, and we have our own parser to handle this that is in not in feature parity with optparse.

We do this because we need some of the arguments before starting the real parser.  Not the best solution, but extending optparse was rather difficult AFAIR.

Supported options are: short opts, long opts, `action='store'`, `action=`store_true`, action=`append`,
and `dest`.

**Comment by ask** [comment]
Pull requests to extend the functionality, or to some hack to reuse optparse welcome,
but we are probably better off moving all the way to argparse for this.
