### ISSUE TITLE
Deprecating and removing --detach, --pidfile and multi in favor of using proper service managers

### ISSUE THREAD

**Issue by malinoff** [celery/celery#2961]
Hey @ask , @thedrow , @PMickael 

Nowadays it is _very_ easy to run processes in background: https://en.wikipedia.org/wiki/Operating_system_service_management

I'm suggesting to strip out `--detach`, `--pidfile` and `multi` from celery in favor of using one of tools listed in the above link.

**Comment by thedrow** [comment]
I agree. It should solve a lot of problems.

**Comment by ask** [comment]
Been there, done that: http://docs.celeryproject.org/en/latest/history/changelog-1.0.html#backward-incompatible-changes :)

You cannot actually chose one standard, every different system uses a different solution, and if someone is already using systemd it would be bad to enforce them to use e.g supervisord for celery.

Being able to daemonize workers from Python programatically in a platform independent way is useful, and I don't think any of them replace the features of `celery multi`.

The daemonization utilities are stable now, and we no longer have the problems we had pre 1.0, but deployments should definitely prefer supervisord/systemd etc, but that change starts from the documentation, guiding the users, instead of removing powerful utilities.

i.e., why are people using generic-init.d when they should be using supervisord/systemd? solve that and solve the problem without removing useful features.

**Comment by malinoff** [comment]
@ask because they can? Or maybe because `celery worker --help` is closer than man systemd.

People tend to do weird things, and using `celery worker --detach` is one of them, imo.
And I wasn't suggesting to pick one standard, I'm open to any of the tools listed on wiki.

Also, current implementation isn't very platform independent since you can't `--detach` on windows.

What kind of useful features of `celery multi` you're talking about?

**Comment by ask** [comment]
malinoff: Starting workers on demand programmatically, quickly testing different configurations, etc.

Are other tools removing detaching code, I haven't seen such a trend yet?  If they cannot be bothered to learn about systemd, adopting celery will be more difficult, not easier.

The daemonization guide currently documents the generic-init.d script, it has a brief possibly outdated recipe for supervisord but no mention of systemd or the other new daemonization tools.

That would be the first thing to fix, the documentation must be in place to guide users on proper deployment.  We cannot remove the feature without that documentation, and when we have the documentation chances are the feature will not be a source of trouble.

**Comment by malinoff** [comment]
@ask yes, definitely - I am not suggesting to remove detaching *right now*, but consider it for removal.
I'll try to spend some time on the docs.

**Comment by auvipy** [comment]
I am against removing this. documentation improvement should be the go.
