### ISSUE TITLE
`URL(...).post_async(...)` doesn't work in Python 3

### ISSUE THREAD

**Issue by kottenator** [celery/celery#2967]
I use `celery==3.1.19` in Python 3 environment. When I do:

```py
URL(...).post_async(x='1')
```

I get an error in Celery Worker: 

    POST data should be bytes or an iterable of bytes. It cannot be of type str.
    File "site-packages/celery/task/http.py", line 156, in dispatch

I think the problem is in this line:

```py
# celery.task.http.py::HttpDispatch.dispatch
params = urlencode(utf8dict(items(self.task_kwargs)))
```

Acording to Python 3 docs for `urllib` you should do:

```py
params = urlencode(utf8dict(items(self.task_kwargs))).encode()
```

**Comment by DanLipsitt** [comment]
There's been a 3.1.20 release since this was closed in `master` but this fix didn't make it in. I just read https://github.com/celery/celery/wiki#development but I can't find anything relevant about how patches are released. `master` and the 3.1 branch are pretty far diverged, so I'm assuming that patches don't flow between them frequently.
