### ISSUE TITLE
how to improve celery execute task speed?

### ISSUE THREAD

**Issue by callnothing** [celery/celery#2982]
I try many times,why celery spend about 500ms to save result(redis is my backend),a task just return a string,but use celery to get result spend me 513ms,that is unacceptable.

**Comment by feifangit** [comment]
my celery return me the result(from redis) in less than 18ms constantly, you'd better check your `redis` by  command `redis-benchmark` and check your python library by simple `get` and `set` operations.

**Comment by callnothing** [comment]
thanks,feifanggit.but maybe your answer was wrong,the get result method has a param "interval", default value is 0.5s,we can change this to get faster response speed.
and this is the reference from celery document:
http://docs.celeryproject.org/en/latest/reference/celery.result.html#celery.result.ResultSet.get

**Comment by feifangit** [comment]
@callnothing, sorry for the misleading answer. I tested in a complicated scenario. 
this is the code of method `wait_for` in `backends/base.py`
```
def wait_for(self, task_id,
                 timeout=None, interval=0.5, no_ack=True, on_interval=None):
    while 1:
            meta = self.get_task_meta(task_id)
            if meta['status'] in states.READY_STATES:
                return meta
            if on_interval:
                on_interval()
            # avoid hammering the CPU checking status.
            time.sleep(interval)
            time_elapsed += interval
            if timeout and time_elapsed >= timeout:
                raise TimeoutError('The operation timed out.')
```
we can see that the **it returns immediately if the result is ready**, otherwise sleep for the interval number and try again. 

My code looks like 
```
ar = add.apply_async([4,5])  # add simply return the sum of two parameters

time.sleep(2) # do something else, equals to time.sleep(2)

st =time.time()
ar.get(interval=0.9)
print time.time()-st 
```
the last line output  a number close to `0` regardless the `interval` you set in parameter.

If we try to get the result by `AsyncResult` after the `apply_async`, or the async task takes a longer time, we can see the delta time effected  by the `interval`.

**Comment by callnothing** [comment]
@feifangit Yes And Thanks!!

**Comment by ask** [comment]
You can subscribe to the id using the redis LISTEN pub/sub features, and you will get notified immediately.  Really it should be using this for result.get() in general, but it has never been implemented.

**Comment by ask** [comment]
Certainly there are use cases, but probably this is because mostly retrieving results like this is used when benchmarking, and rarely in production code :)
