### ISSUE TITLE
Celery 3.1.19 & SQS stops working (consumer)

### ISSUE THREAD

**Issue by jhg-tgu** [celery/celery#2999]
I have a beat and a worker with autoscale using SQS with kombu 3.0.30. It work fine when start but after a  random time (not is same time all times) the worker process is alive but process child for consume queues not work and don't consume queues. I only show "Pool process <Worker(Worker-11, started daemon)> error: BrokenPipeError(32, 'Broken pipe')" (but not all times).

Also, supervisord can't kill celery process of worker, but say that is stopped.

**Comment by ask** [comment]
The SQS transport in 3.1 is not reliable and can easily lead to deadlocks if processes are killed/terminated.

It was rewritten since and in the development version it now uses async i/o to be able to take advantage of the new async prefork pool introduced in 3.1.  To be released in 4.0, and we would be grateful for any testing you can do.

**Comment by jhg-tgu** [comment]
@ask when will be release 4.0 version?

**Comment by ask** [comment]
Missing docs, and proper beta testing
