### ISSUE TITLE
Restart command fails to start celerybeat with generic init.d on Ubuntu 14.04

### ISSUE THREAD

**Issue by pixelchutes** [celery/celery#3018]
I'm not sure why exactly, but the [restart command in generic-init.d/celerybeat](https://github.com/celery/celery/blob/ee27089030bcc3cb3e15bf373491ffe1956620a1/extra/generic-init.d/celerybeat#L300)  would stop the service, but abort before`start_beat` method was ran. 

#### Versions:
`celery-3.1.19 (Cipater)`
```
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

Below is how we ended up fixing the desired behavior in `restart` function: (~Line 303):

#### Before:

```sh
stop_beat
check_dev_null
start_beat
```

#### After:

```sh
stop_beat && check_dev_null && start_beat
```

**Comment by ask** [comment]
Please run the script via `sh -x /etc/init.d/celerybeat` restart to get some debugging output!

I would think the after version will introduce the behavior you describe :confused:

**Comment by pixelchutes** [comment]
```python
++ basename service
+ VERSION='service ver. 0.91-ubuntu1'
++ basename service
+ USAGE='Usage: service < option > | --status-all | [ service_name [ command | --full-restart ] ]'
+ SERVICE=
+ ACTION=
+ SERVICEDIR=/etc/init.d
+ OPTIONS=
+ '[' 2 -eq 0 ']'
+ cd /
+ '[' 2 -gt 0 ']'
+ case "${1}" in
+ '[' -z '' -a 2 -eq 1 -a celerybeat = --status-all ']'
+ '[' 2 -eq 2 -a restart = --full-restart ']'
+ '[' -z '' ']'
+ SERVICE=celerybeat
+ shift
+ '[' 1 -gt 0 ']'
+ case "${1}" in
+ '[' -z celerybeat -a 1 -eq 1 -a restart = --status-all ']'
+ '[' 1 -eq 2 -a '' = --full-restart ']'
+ '[' -z celerybeat ']'
+ '[' -z '' ']'
+ ACTION=restart
+ shift
+ '[' 0 -gt 0 ']'
+ '[' -r /etc/init/celerybeat.conf ']'
+ '[' -x /etc/init.d/celerybeat ']'
+ exec env -i LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ssl/bin:/usr/local/sbin:/usr/local/bin TERM=xterm-256color /etc/init.d/celerybeat restart
celery init v10.1.
Using configuration: /etc/default/celeryd, /etc/default/celerybeat
Restarting celery periodic task scheduler
Stopping celerybeat...
```

There is no subsequent start after the stop event.

NOTE: This only occurs when `celerybeat` is already running.

**Comment by ask** [comment]
Applied your fix and it's now in master

**Comment by ask** [comment]
Thanks :)

**Comment by jadkik** [comment]
There's something kind of wrong with the fix.

The `stop` command terminates with a non-zero exit code (that of the `kill -0` command), even though it does stop properly.

As seen in the comments on the commit 458d167621209654cd17cff30b43f69b06134c63, the issue is rather with the `-e` that was introduced in the shebang in the referenced commit, which is also what commit 9f7f5d17e4473b132842afa432036683abdde945 was trying to fix.

I'm still not sure how the merged fix works in the case of the `restart` command, but I believe the `stop` command should not terminate with a non-zero exit code regardless.
