### ISSUE TITLE
docs: How does .../bin/celery find app's celery.py?

### ISSUE THREAD

**Issue by rrauenza** [celery/celery#3065]
I'm a bit mystified at the magic that allows virtualenv/bin/celery find my proj/proj/celery.py file for bootstrapping my app.  Tracing through the code ... aha.  It looks like celery assumes there is an directory underneath the the current directory named after the app, and then it loads a celery module from there.   This means I always have to run celery from the top of my django directory.

Is it worth explicitly documenting this (maybe in First Steps)?  I found it confusing, and now that I understand it, a lot of things are now clearer to me.

**Comment by malinoff** [comment]
Feel free to open a PR with any words you find useful to share!

**Comment by ask** [comment]
In theory all you need to know is that,

   celery -A proj

is a shortcut to

    celery -A proj.celery:app


But it actually tries quite hard to find an app, sadly it's only documented in this location:
http://docs.celeryproject.org/en/latest/getting-started/next-steps.html#about-the-app-argument

The `proj.celery:celery` attribute name is mostly there for compatibility with the deprecated Flask-Celery.

**Comment by rrauenza** [comment]
Ah!  I think the perspective difference is I saw '-A' as the way to use an app somehow celery is already aware of, and in fact, it is used to *find* the app.  I think just a note in the first steps linking to that --app doc is enough and would be appreciated.

That's the big perspective shift I've struggled with when moving from the global Django settings.py file ...

**Comment by ShaheedHaque** [comment]
After some hacking around, I have found some interesting related information. I'm a bit of a noob here, so I'm not sure if this is already a well known thing or not...feel free to tell me I am mistaken/ot-of-order.

1. Given the standard Django directory structure of .../proj/proj/myapp, in order to find .../proj/proj/settings.py, if PWD is .../proj, then import proj.setting works naturally enough.
2. For reasons I have not tracked down, but which I think are to do with forked instances, something to do with the way that the celery command runs ALSO means that if you refer to the app from (say) .../proj/proj/myapp/apps.py, there will be import failures for proj.settings.

Now, the reason for the latter seems to be that the (presumably) forked instances end up with a sys.path which has the "..." ahead of ".../proj". Thus, the attempt to import proj.settings fails because Python ends up looking for .../proj/settings.py instead of finding .../proj/proj/settings.py.

I ended up changing the standard setup of "app" to look like this:

    #
    # The Django directory structure of .../proj/proj/app menas that attempting to
    # import the settings from .../proj/proj/settings.py fails if sys.path ends up
    # with .../proj before .../proj/proj. Which is exactly what Celery seems to
    # do...so we fix this up.
    #
    try:
        sys.path.remove(PROJ_DIR)
    except ValueError:
        pass
    sys.path.insert(0, PROJ_DIR)
    app = celery.Celery(main=__name__)
    app.config_from_object('django.conf:settings', namespace='CELERY')
    app.autodiscover_tasks()

Specifically, this allowed me to reference the app object from places where the normal result is a failure to import proj.settings.
