### ISSUE TITLE
Task.update_state in a thread

### ISSUE THREAD

**Issue by RemiDesgrange** [celery/celery#3067]
Hi, 

I'm not sure if it's me or a bug. let's imagine this code :

```python
class MyClass(celery.Task):
    def run(self, timeout):
         self.update_to(timeout)
         doSomethingUntilTimeout(timeout)
    def update_to(self, to):
        def timeout(cp_self, start_to):
        """" cp_self is a copy of self"""
            to = start_to
            while to != 0:
                time.sleep(1)
                to -=1
                cp_self.update_state(state='PROGRESS'  meta = {'timeout': to})
       t = threading.Thread(target=timeout, args=(self, to)
       t.start()
```

I have these error :

```
    self.backend.store_result(task_id, meta, state)
  File "D:\Python27\lib\site-packages\celery\backends\base.py", line 214, in store_result
    request=request, **kwargs)
  File "D:\Python27\lib\site-packages\celery\backends\base.py", line 420, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "D:\Python27\lib\site-packages\celery\backends\base.py", line 352, in get_key_for_task
    return self.task_keyprefix + ensure_bytes(task_id)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```
In my debugger i can see that task_id is indeed "None" I cannot update the state in `doSomethingUntilTimeout()` because it's a call to subprocess :-( any hint ?

**Comment by ask** [comment]
task.request is a thread local, so only the thread executing the task can call update_state.

This especially makes sense if you consider that the thread could race with the task post handler storing the result.

**Comment by ask** [comment]
You can pass the task_id to the thread:

   cp_self.update_state(task_id=task_id, state='PROGRESS', meta={'timeout': to})

But you have to make damn sure the thread is joined and stopped before the task exits (``thread.join()``).
In your example the thread can only be joined after the `while` loop exits, and since you are sleeping for 1 second the join can be delayed by as much.

You should see https://github.com/celery/celery/blob/master/celery/utils/threads.py#L37-L87
for an example of a thread that can be joined:

https://github.com/celery/celery/blob/master/celery/utils/threads.py#L37-L87

Important parts being the _is_stopped/_is_shutdown events

**Comment by RemiDesgrange** [comment]
I surely understand that request *has* to be thread local.
