### ISSUE TITLE
When chain tasks raise Error the chain always 'PENDING'?

### ISSUE THREAD

**Issue by Gwill** [celery/celery#3140]
```
@task
def t1(x):
    raise Exception

@task
def t2(x):
    return x + 1

r = chain(t1.s(1), t2.s(2))()
```

r.get() return Exception, it is right. but r.state is always 'PENDING', I think it should be 'FAILED'. Is it a bug? And what is the right way to check a chain task state?

**Comment by Gwill** [comment]
Is there anyone can help me?

**Comment by malinoff** [comment]
I don't know `canvas` well enough, @ask ping

**Comment by ask** [comment]
The result returned by chain is the result of the last task in the chain.  Calling r.get() will depend on the parent tasks in the chain, so the exception is raised by one of the parent tasks not the last task.

PENDING is the default state for any unknown task id, and since the last task was never started, it's still pending.   It could be that it would be better for the worker to set the result for enabled tasks as well, but that would be a feature request.

**Comment by dakechen** [comment]
loacl_file = excel_write.apply_async(args=(data_list, file_name),
                                         countdown=0)
 while not loacl_file.ready():    #判断任务是否完成
        time.sleep(0.01)
loacl_file.get()   # 取值
你得等这个异步任务做完了，才能get到值
