### ISSUE TITLE
All celery tasks are not consumed

### ISSUE THREAD

**Issue by acoolj08** [celery/celery#3149]
I am using celery 3.1.21 version. And redis as message broker version 3.0.7.
And I have a periodic task which runs every 1 minute.
In this periodic task, I have another task which asynchronously gets the result of three urls.
Sometimes, two urls are fetched and sometimes only one url is fetched. This is on debian machine.

But whenever I try on my macbook, all three urls are fetched.

Could somebody guide me ?

**My settings.py file:**

BROKER_URL = 'redis://localhost:6379'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379'

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'

**My celery.py file:**

from **future** import absolute_import
import os
from celery import Celery
from django.conf import settings
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mysite.settings')
app = Celery('mysite')
app.config_from_object('django.conf:settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

@app.task(bind=True)
def debug_task(self):
    print('Request: {0!r}'.format(self.request))

**My code specific part where periodic task is called from tasks.py:**

@periodic_task(run_every=(crontab(minute='*/1')), name="query_crawl_scheduler", ignore_result=False)
def query_crawl_scheduler():
    YandexSpider().start_requests()

**My YandexSpider class:**

class YandexSpider:
    start_urls  = []
    name = "yandex_crawl"
    def start_requests(self):
        requests = []
        query_crawl_parameters = { 
            constants.CommonStrings.STATUS : constants.QueryStatus.NOT_CRAWLED,
        }  
        for row in QueryCrawlStatus.get_per_status(**query_crawl_parameters):
            id_, term = row.query_id.query_id, urllib.quote(row.query_id.query.encode('utf8'))
            url = "http://yandex.com/search/xml?l10n=en&user=%s&key=%s&query=%s" % (user, key, term)
            **request = request_tsk.delay(url, id_)**
            requests.append(request)
        return requests

**My request_task method:**
@task(name="request_tsk", ignore_result=False)
def request_tsk(url, query_id):
...

This request_tsk method is not called for every "request_tsk.delay(url, id_) " call from YandexSpider class.

Thanks

**Comment by acoolj08** [comment]
From Celery Flower UI, I clicked on Cancel Consumer and now it worked fine. But I am not sure if this will reproduce in future.

Please provide guidance.

**Comment by ask** [comment]
Sounds like you have a broken worker running somewhere.

Make sure all the worker instances you have started, are stopped properly, and that no defunct workers
are left running.

**Comment by fjorgemota** [comment]
I'm testing the same stack here and, for some reason, when I run celery worker with some parameters it seems to not return pong to the "celery inspect ping" command.

For example, if I run:

```
python -Wd manage.py celery worker -A myproject -l debug
```

It does not return 'Pong' nor process tasks (but it does not finish the execution, too). But, if I use:

```
python -Wd manage.py celery worker -A myproject -l DEBUG
```

All works nicely. 

Another problem I found that's very similar to this issue is that, if I use the ```--autoreload``` option, the worker simply does not work, not responding pings nor processing tasks.

By the way, i'm using Python 3.5.2, Redis 3.2.1 and Celery 3.1.23, with the following config:

```py

BROKER_URL = 'redis://redis:6379/1'
CELERY_RESULT_BACKEND = 'redis://redis:6379/2'
CELERY_ACCEPT_CONTENT = ['json', 'msgpack', 'yaml']
CELERY_TASK_SERIALIZER = 'json'
CELERY_EVENT_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_SEND_EVENTS = True
CELERYD_HIJACK_ROOT_LOGGER = False
```

And...i'm using Docker to run all that stack.

**Comment by thedrow** [comment]
@ask What @fjorgemota is suggesting is that we have a bug parsing the logger option?
I don't have time to test this now but I'll try to get it to it.
In case I don't, ping me.

**Comment by thedrow** [comment]
@fjorgemota @acoolj08 Please provide a full test case I can run.

**Comment by ask** [comment]
I would be extremely surprised if if an uppercase `DEBUG` caused this issue, are you sure it's not a coincidence?

**Comment by fjorgemota** [comment]
Hello! Sorry for the late answer.

Well. That's what just happened at the moment of the issue.

As i'm using Docker, i'll try to publish a separate repository containing the config+django project+some example task showing the issue. But later, ok? I'll publish the link here after created the repository with the case where this bug is happening. :)

**Comment by auvipy** [comment]
I am closing this issue, if it still hits in master or new release plz report.
