### ISSUE TITLE
Does autoscale work fine with disabled prefetch?

### ISSUE THREAD

**Issue by auuron** [celery/celery#3240]
Hello, today i wanted to disable prefetch, so i changed CELERY_PREFETCH_MULTIPLIER from 0 to 1. 
Problem is that my workers which had autoscale=70,1 started processing only one task at time (i guess it might be because of min. 1 concurrency in autoscale). Rest of the task was waiting in pending state.. I wondered is it allowed? Or maybe it's a bug?

I start worker with following parameters:
celery multi restart someworker -A someapp -l info -Ofair -Q:1 somequeue -c:1 70 -P:1 prefork --logfile=/somepath/%N.log --pidfile=/somepath/%N.pid --autoscale=70,1

celery 3.1.23
kombu 3.0.35
billiard 3.3.0.23

**Comment by ask** [comment]
Sadly we don't have the resources to maintain autoscale,  so we are undocumenting the feature for 4.0 :(

**Comment by xBeAsTx** [comment]
Wow, is this really feature was removed because of this bug? Because I think it's wrong command line, you must remove `-c` option and keep only `--autoscale`. This way must work fine:

`celery multi restart someworker -A someapp -l info -Ofair -Q:1 somequeue -P:1 prefork --logfile=/somepath/%N.log --pidfile=/somepath/%N.pid --autoscale=70,1`
