### ISSUE TITLE
ERROR/MainProcess] consumer: Cannot connect to redis

### ISSUE THREAD

**Issue by kartikdanidhariya** [celery/celery#3253]
hi,
i am using celery in django 
my celery version is  3.1.23

after all set when i give following command 
"celery -A proj worker -l info"

so it return error like 

ERROR/MainProcess] consumer: Cannot connect to redis://127.0.0.1:6379/0: .

i check for that i also install redis 

how can i solve this error

**Comment by ask** [comment]
are you able to use `redis-cli` on localhost?

It pretty much says it cannot connect, so I would guess that redis is not available on localhost at that port.

**Comment by weisst** [comment]
hi,i'm have same wrong, celery version is 3.1.23,redis is 3.2.1

i test redis config file ,comment requirepass and change protected-mode yes to no

the problem is fine ,so i think celery connection redis auth have some error,please check it ,thx.

**Comment by hamishwillee** [comment]
The instructions in [Using Redis](http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html#broker-redis) explain how to install redis/celery using PIP and give the above connection. I THINK the problem is that you also have to install a separate redis server - ie the instructions are just "integration with redis" not "installation of redis". 

If correct, and I'll know when I try this, the document should be updated to note that redis server must also be installed and started.

**Comment by pattoM** [comment]
Celery on flask/django can be very sensitive to minute details. Remove the zero after the port 6370. Additionally make sure that the output from running redis-cli is what you put as your broker url. In this case, 127.0.0.1 is not treated the same as localhost//

**Comment by R7ramesh** [comment]
There is a simple solution available:
     Just install redis-server at root machine:-`sudo apt-get install redis-server`
now run the `worker -A <project-name> --loglevel=debug --concurrency=2`at same directory where your project is located.

Or You can change in the celeryconfig.py file where you need to remove the `bind` statement.

Both ways work for me.

**Comment by Saw-mon-and-Natalie** [comment]
For my setup, I had to use **`IPv6`** for the `redis_host` in `celery config`.

```
redis://[::1]:6379/0
```

**Comment by NLKNguyen** [comment]
On Windows 10 Pro with Docker for Desktop, use IPv4 instead of localhost works too `redis://127.0.0.1:6379/0`

```python
app = Celery('tasks', backend='redis://127.0.0.1:6379', broker='redis://127.0.0.1:6379')
app.conf.broker_url = 'redis://127.0.0.1:6379/0'
```

Assume that a Docker container running Redis on the conventional port number.

```powershell
docker run -d -p 6379:6379 redis
```

Example updated hello world with Celery and Redis

![image](https://user-images.githubusercontent.com/4667129/132940380-3128d4a9-d9cd-47ec-846f-8dd5357c929e.png)


On a side note on Windows, you might stumble another unrelated issue that can be solved by using `eventlet` for concurrency instead of the default which crashes on recent versions.

```
pip install eventlet
celery -A tasks worker --loglevel=INFO --pool=eventlet
```
