### ISSUE TITLE
Multiple celery config

### ISSUE THREAD

**Issue by mhipo1364** [celery/celery#3278]
Hi guys

I have a question, I have 2 `django` project in my server and I used daemon for `celery`, but celery config has just one file (in `/etc/default/celerd`), how can I add another file to daemon run them both?

**Comment by ask** [comment]
Sadly you need to create multiple init scripts.  You can symlink them so e.g:


    ln -s /etc/init.d/celeryd /etc/init.d/celeryd-projB

then copy the config:

   cp /etc/default/celeryd /etc/init.d/celeryd-projB

Then you can configure them individually.

Sadly since Django settings are global there is no sane way to have run two django projects in the
same process.
