### ISSUE TITLE
Delay memory leak

### ISSUE THREAD

**Issue by ztsv** [celery/celery#3279]
I have celery task:

```
@shared_task(bind=True, default_retry_delay=10 * 60, max_retries=20, acks_late=True)
def some_task(self, tracker_id):
    # some django logic here
    print ('before to_update: ', resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1000)
    while to_update: # to_update is list of 30000 id's (long integers)
        update.delay(to_update.pop())
    print ('after sending update tasks: ', resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1000)
    # ~update_user_info.map(to_update).apply_async()
    # some django logic here
    return True
```

And i got leak about 650mb. 

```
('before to_update: ', 165.376)
('after sending update tasks: ', 808.94)
```

**Comment by ask** [comment]
What version?

**Comment by ask** [comment]
Probably have to wait for gc.collect first?

**Comment by ztsv** [comment]
but why 650 mb after 30 000 calls of delay?

**Comment by yeago** [comment]
I don't know if its related but i have been having some pretty nasty memory leakage in 3.1.23

**Comment by roks0n** [comment]
Have been experiencing something similar. We are using SQS and are sending tasks to the queue using `apply_async()`. We've been profiling for a few days and weren't able to reproduce the behaviour in a test environment. We did however solve the problem in the end by setting [max tasks per child](http://docs.celeryproject.org/en/latest/userguide/workers.html#max-tasks-per-child-setting ). Not ideal but it did the trick.

What we were seeing is basically memory gradually increasing and a huge drop after some random time or after the task got killed because no more memory was available:

![image](https://cloud.githubusercontent.com/assets/889696/16856328/e15d9ba2-4a19-11e6-88a7-5a85028ea400.png)

We use:
celery==3.1.23
kombu==3.0.34
billiard==3.3.0.23

**Comment by roks0n** [comment]
Just wanted to follow up on this. We've managed to solve our problem ... we didn't increase CPU on our instance (:facepalm:) and we've also made some changes to the worker so that it processes  some things in several chunks.

**Comment by mkuchen** [comment]
@yeago @ask @ztsv I've been experiencing similar issues with a Django app (deployed via Heroku) with versions:
Django==1.9.6
celery==3.1.23
kombu==3.0.35
billiard==3.3.0.23

I have a task on a process that executes at a rate of approximately 1000 tasks per minute.  I've resigned to restarting this particular worker queue every 3 hours to prevent exceeding memory quotas.

Do any of you have suggestions for debugging this problem?  It's persisted for a while but I'm getting the point where restarting the worker isn't going to be feasible.  Any help is greatly appreciated!

**Comment by mkuchen** [comment]
Note that I've tried using `gc.collect()` at the beginning and end of the task in question but to no avail.

**Comment by vesterbaek** [comment]
Ref #3339

**Comment by vesterbaek** [comment]
@mkuchen did you resolve this?

**Comment by vesterbaek** [comment]
Ok, thanks for getting back. I did upgrade to Celery 4 - unfortunately with no improvement in this area.

**Comment by danqing** [comment]
Just noticed this today. On 4.1.0 with rabbit. Running a bunch of jobs and ran out of (2TB of) memory in a few hours...

**Comment by thedrow** [comment]
@danqing @vesterbaek Do you have a test case that can reproduce this issue?

**Comment by vesterbaek** [comment]
@thedrow Unfortunately not. I've been trying to provoke this in development -- but have not found a good way to achieve this. On production - when it happens - is hard for me because this is running on Heroku. For now, I'm mitigating the problem by monitoring Heroku logs for R14 (OOM) and restarting the workers when this happens.

**Comment by auvipy** [comment]
probably you could try latest master and check https://github.com/celery/celery/issues/3339 this issue

**Comment by paulochf** [comment]
My colleagues at my work were getting this problem and they solved by switching to [rq](https://github.com/nvie/rq). The `CELERYD_MAX_TASKS_PER_CHILD` setting wasn't enough.
