### ISSUE TITLE
v4.0.0 release date

### ISSUE THREAD

**Issue by khafan246** [celery/celery#3296]
any estimate here?

**Comment by ask** [comment]
There's a list of issues that needs to be triaged:
https://github.com/celery/celery/issues?q=is%3Aopen+is%3Aissue+milestone%3Av4.0

Some of these are easily closed by simple documentation changes.

Once those are fixed (or moved to another milestone) we start testing

**Comment by ask** [comment]
A preview release, celery 4.0.0rc3 is on PyPI and can be installed by doing:

    pip install -U --pre celery

The more people test it, the faster the release can happen :)

**Comment by khafan246** [comment]
thank you @ask 
keep up the good work

**Comment by thedrow** [comment]
I think this can be closed because it's more of a question than an actionable item.
We can't provide a release date on an open source project that is done on our free time other than as soon as possible.

@ask Feel free to reopen and/or reword this issue into something more actionable in case I shouldn't have closed this issue.
