### ISSUE TITLE
Topic exchange route fail

### ISSUE THREAD

**Issue by zhiyue** [celery/celery#3314]
using redis as `broker`.
I specify exchange in`CELERY_ROUTES`  , but it does not work properly, and there is no error message.
I configured as follows:
```python
from kombu import Exchange,Queue

BROKER_URL = 'redis://localhost:6379/2'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/2'
CELERY_IMPORTS = ('tasks', )

CELERY_RESULT_PERSISTENT = True
CELERY_TASK_RESULT_EXPIRES = None

CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_DEFAULT_QUEUE = 'default'
CELERY_QUEUES = (
    Queue('default', Exchange('tasks', type='topic'), routing_key='tasks.default'),
    Queue('compute', Exchange('test1', type='topic'), routing_key='tasks.compute.#'),
    Queue('add', Exchange('tasks', type='topic'), routing_key='tasks.add.#'),
)
CELERY_DEFAULT_EXCHANGE = 'tasks'
CELERY_DEFAULT_EXCHANGE_TYPE = 'topic'
CELERY_DEFAULT_ROUTING_KEY = 'tasks.default'

CELERY_ROUTES = {
    'tasks.compute': {
        'exchange': "test1",
        'exchange_type': 'topic',
        'routing_key': 'tasks.compute.test'
    },
    'tasks.add': {
        'routing_key': 'tasks.add.test',
    }
}
```
`tasks.add` can run normally,but `tasks.compute`can not match  to the queue `compute`.If I modify the configuration to:
```python
'tasks.compute': {
        'exchange': "test1",
        'exchange_type': 'topic',
        'routing_key': 'tasks.compute.#'
   },
```
then `tasks.compute` works.it can route to queue `compute`.
This situation seems to change it to `direct` mode？

**Comment by kindule** [comment]
+1 
with the same issue there.

**Comment by ask** [comment]
When using Redis and topic routing the producer also needs to declare the queue.  This was written before Redis had pub/sub capabilities.  The fanout exchange type is using pub/sub already, but since it's so uncommon to use topic routing it has not been a priority to fix, and I guess it'd completely change the delivery guarantee when topic is meant to support persistent messaging.

You can change it to:

```py

'tasks.compute': {
    'queue': 'compute',
    'routing_key': 'tasks.compute.#',
}

```

I guess the quick way to solve this would be to store the type of the exchange also in redis (i.e. you only need to declare the queue so that the in-memory type of the queue changes from direct to topic, but this could be stored in redis).
