### ISSUE TITLE
Chord raises IncompleteRead error 

### ISSUE THREAD

**Issue by cosenal** [celery/celery#3324]
I am using Celery 3.1.23 deployed on Heroku with RabbitMQ as broker.

The code I am running is a simple chord of the following kind: chord(A)(B), where A is a list of tasks chains (A1 | A2).

When the list A of tasks is small, no error arises. However, when the list is long (~45,000 tasks!), Celery behaves strangely. In some cases, in the logs I see that lots of the tasks from A succeed, but the callback B is never called. In other cases, weird errors, as the following, appear.

`Chord 'a04b2de4-aa71-408e-bfb3-2ec336707397' raised: 'IncompleteRead(155 bytes read)' `

**Comment by cosenal** [comment]
Here is all I see:
```
Traceback (most recent call last): 
  File "/app/.heroku/python/lib/python2.7/site-packages/celery/backends/base.py", line 583, in on_chord_part_return 
    culprit = next(deps._failed_join_report()) 
StopIteration 
```

**Comment by ask** [comment]
Not sure where IncompleteRead is coming from, I don't think it's a celery/amqp exception :/

**Comment by cosenal** [comment]
@ask Is it possible that Celery shows it as a chord error, but in fact it's an error raised by one of the tasks in the group A?

**Comment by cosenal** [comment]
By logging the number of tasks in A that reach the end, I can give you a better description of what happens with my code. There are two ways in which the code fails: 

Case 1) not all of the tasks from A are executed (from the logs it turns out that in one instance I run it, only ~40% of them were run), but no errors are raised (I am not hiding exceptions).
Case 2) all (or almost all) the tasks from A are executed, but an error is raised but one of them.

In both cases, the chord callback is not called. I am more worried about Case 1), where everything happens silently, no traces of errors, and Celery just looks stuck. By inspecting the code I have already double-checked that there are no race conditions.

**Comment by ask** [comment]
That's exactly what a ChordError is.  If any of the tasks in the header group fails, the result of the chord body (callback) transitions to FAILURE.  It does so at the first task that fails, so you currently don't get a list of errors (but that could be extended).

In this case it looks like it couldn't find the result that failed, since the list is so long I fear that Redis could have evicted it.  In our stress test suite Redis just drops keys when a lot of memory is used (may be so short that graphing monitors don't even detect the spike), without any evidence left in logs.

Note: The chord callback is not called when an error occurs, the callback state simply transitions to a failure state.  In 4.0 you can add an error callback receiving the actual exception instance with traceback to all the tasks in the chord using .on_error(error_handling) task: http://docs.celeryproject.org/en/master/whatsnew-4.0.html#canvas-refactor

**Comment by cosenal** [comment]
Thank you for your reply, @ask. The option for an `on_error` callback sounds like a really good addition, I am looking forward to trying Celery 4.0 ;)

It looks like setting `ACKS_LATE=True` solved the issue, but I am still investigating on what was happening (I suspect crashes of the Heroku dynos)
