### ISSUE TITLE
Celery retry entire chain

### ISSUE THREAD

**Issue by matt-snider** [celery/celery#3325]
Hi! 

I've got a situation that I've been trying to figure out for some time. I've searched quite a lot, asked in the celery IRC channel, and tinkered around to no avail. 

I've come up with the following contrived example to leave out actual details of the system. This can be envisioned as some system where connections come and go, and when a connection exists that matches the conditions (x and y) then we should run the second task.
```python
@app.task(bind=True, max_retries=None)
def find_valid_connection(x, y):
      # attempt to find connection matching x and y
      if not connection:
           self.retry(countdown=30)
      return connection

@app.task(bind=True, max_retries=3)
def use_connection(connection):
      try:
          # attempt to use connection
      except:
          # retry, but connection is now out of date
          self.retry(countdown=30)
```

Which I use in a chain:
```python
task = chain(find_valid_connection.s(1, 2), use_connection.s())
#...
```

The first task should run until a valid connection is found, and "sleep" for 30 seconds every time it searches and doesn't find one. Once it finds a connection, the bigger task runs which actually uses the resource. 

The problem is, that when the second task fails and retries, the connection may no longer be valid. So essentially I need to retry the whole chain. This doesn't seem possible. Combining them into one task is also difficult because the first task needs to have `max_retries=None`. 

Is this something that doesn't fit well to Celery's model, or have I completely missed a feature that could be very useful here?

**Comment by ask** [comment]
I don't think it's something that doesn't fit into our model, it's more like something that there would be no good solution for in general :)

It would be much faster to use this resource directly after acquiring it, and you can also retry substeps in a task by maintaining a list of remaining items:

```py

@app.task(bind=True, max_retries=3)
def fetch(urls):
    connection = find_valid_connection()
    while urls:
        url = urls.pop()
        try:
            response = requests.get(url)
        except TimeoutError as exc:
            raise self.retry(args=(urls,), countdown=30)
```

The problem here is of course that if the first URL fails, you will also suspend the fetching
of the rest of the urls when they could actually be ok.  But if this is a global semaphore, or something like a global a rate limit then that is exactly what you want.

**Comment by matt-snider** [comment]
Thanks for the response! 

I wasn't aware that I could pass `args` into `retry()` - that's quite neat. That would enable me to do something like the following:
```python
@app.task(bind=True, max_retries=None)
def fetch(url, processing_retries=0):
    # acquire resource
    connection = find_valid_connection()
    if not connection:
         self.retry(countdown=30)

     # use resource/process
    if processing_retries > 3:
         raise MaxRetriesExceededError() 
    try:
         response = requests.get(url)
         # process response
     except TimeoutError as exc:
         self.retry(countdown=30, args=(url, processing_retries+1))
```
But I'm not sure if this is idiomatic or if there's a better way. 

The other problem with a single task is that the `retries` may end up being something like 3000 when I only want to track retries during the processing step. Passing the `processing_retries` via args would take care of this as I could just refer to this figure instead of using celery's retry count.

**Comment by ask** [comment]
Yeah, you can definitely do that.  It's sort of the pattern celery uses already, except it stores the retry count in a message header, with the benefit of any intermediate message proxies or observers being able to read the value without deserializing the message body.

Sometimes people want to do this:

```py
try:
    self.retry(exc=exc)
except MaxRetriesExceededError:
    ...
```

but Celery doesn't actually allow this, since it re-raises the current exception on retry to keep the context (could improve this now that Python 3 keeps a stack of exceptions).  To work around this some people are already doing what you're doing.


Note: You could also pass `headers={'processing_retries': request.headers.get('processing_retries', 0) + 1}` but that's a bit awkward.

**Comment by matt-snider** [comment]
Okay thanks a lot for the advice! I'll give it another shot
