### ISSUE TITLE
ImportError: No module named celery

### ISSUE THREAD

**Issue by jobelenus** [celery/celery#3349]
I'm working in django 1.9. I previously put `import myapp.tasks` in my `myapp/__init__.py` file. Now I need to move it to the `myapp/apps.py` Django AppConfig due to application loading so proper settings and dependencies exist prior to tasks loading. But when I do this I get a very odd error whenever I try to start my celery workers:

```
ImportError: No module named celery
Traceback (most recent call last):
  File "/srv/lenspro/env/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/srv/lenspro/env/local/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/srv/lenspro/env/local/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/srv/lenspro/env/local/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/srv/lenspro/env/local/lib/python2.7/site-packages/celery/bin/base.py", line 309, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/srv/lenspro/env/local/lib/python2.7/site-packages/celery/bin/base.py", line 469, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/srv/lenspro/env/local/lib/python2.7/site-packages/celery/bin/base.py", line 489, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/srv/lenspro/env/local/lib/python2.7/site-packages/celery/app/utils.py", line 248, in find_app
    symbol_by_name=symbol_by_name, imp=imp,
  File "/srv/lenspro/env/local/lib/python2.7/site-packages/celery/app/utils.py", line 232, in find_app
    sym = imp(app)
  File "/srv/lenspro/env/local/lib/python2.7/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
```

What could the cause of this be? If I keep my tasks import in the __init__.py file celery workers start fine. But, as I understand the Django application loading the `default_app_config` in __init__.py is what calls and loads the apps.py file. Which means that I'm actually moving task registration to slightly/barely later in the loading cycle. Why would loading this slightly later cause a problem?

**Comment by ask** [comment]
Make sure you have:

    from __future__ import absolute_import

at the of the module where you import your local celery module.

In Python 2.x if you have a directory layout like this:

```
    app/__init__.py
    app/sys.py
    app/models.py
```

And `app/models.py` does:

```py
# app/models.py

from sys import path
```

Then it will import `path` from the `app/sys.py` module instead of the expected module from the Python standard library.

These are the "implicit relative imports", probably the worst feature of Python ever :)

In Python 3.x they are thankfully gone.

I always add `from __future__ import absolute_import` to every module, and consider it a best practice for code that supports Python 2.

NB: This doesn't affect the "explicit relative imports":

```py
     from .sys import path  # < This is still OK!
```

**Comment by jobelenus** [comment]
Hrmmm this does not appear to be the cause. I have no files called `celery` in either my project or in the celery_haystack project. I've added the future absolute import line to the top of both my `tasks.py` file and the celery_haystack `tasks.py` file. If you take a closer look at the trace it appears that it is *already inside* of the celery app when it says it cannot find it (or I really don't know how to interpret that trace)

**Comment by jobelenus** [comment]
@ask did you see my above comment? I know you've closed the issue -- but it's not resolved

**Comment by ask** [comment]
@jobelenus The `celery` command finds your app, the app loads the `celery.fixups.django` fixup.

The Django fixup won't do anything unless the `DJANGO_SETTINGS_MODULE` environment variable is set, which is why the example `proj/__init__.py` file sets it.  You may omit that if you always
pass the environment variable on the command-line, for example:

```console
$ DJANGO_SETTINGS_MODULE=proj.settings celery -A worker -l info
```

If you set it in `app.apps` the celery command won't know where the setting module is.

**Comment by jobelenus** [comment]
OK -- for posterity the problem is that I didn't have `myapp/celery.py` defined. I still had the Celery app declared in my `myapp/tasks.py` file (as was the old default). Once I moved that it worked as expected.
