### ISSUE TITLE
Rearchitect prefork pool

### ISSUE THREAD

**Issue by thedrow** [celery/celery#3364]
I'm wondering if we can ditch the prefork pool and use subprocesses that communicate using pipes. Possibly even stdin/stdout.
Would that resolve a lot of the limitations of preforking such as running threads inside the master celery process and running other subprocesses?
What are the limitations of such design?

**Comment by ask** [comment]
But this description exactly matches how the current prefork pool works :)

**Comment by thedrow** [comment]
I'm talking about using Popen instead of forking the same process. I don't think it's the same.

**Comment by ask** [comment]
I don't see how that would make things simpler though, the multiprocessing pool already has an option to use fork+execv, but this caused more problems than it solved, and so many complaints.

The aynpool should never have subclassed multiprocessing.Pool as this added way too much complexity, but I'd rather see decoupling that and maybe trying things like shared memory and lock free queues.

Threads in Python are useless, I don't see why we would spend effort to support them when async I/O performs so much better and is deterministic.

As for child processes, the only problem there is that if you `kill -9` the main process, it won't propagate that signal to child processes. On Linux there's a new flag you can set that forces the child processes to be killed with a parent, but I cannot find it right now.  Not sure what to keywords to use on Google, ugh.

**Comment by thedrow** [comment]
Threads are not useless when a C extension releases the GIL. I'd like to be able to provide a way for results backends to be written with less limitations.

We could use a process manager like Circus to keep the child processes alive. That'd a non-issue.

**Comment by malinoff** [comment]
Honestly I see the future of pools in using/defining custom `concurrent.futures` executors.

**Comment by thedrow** [comment]
@malinoff That could work well.

**Comment by ask** [comment]
But, they're just a tiny wrapper around multiprocessing.Pool...

**Comment by ask** [comment]
@thedrow: as soon as someone loads some user code/third party library into the parent process, there will be problems and we will get the blame.  There's very few thread-safe libraries out there.

Supervising processes and starting processes is still only a small portion of the pool, and we want to be fast too.  There's no stable pool implementation in Python, multiprocessing.Pool is out of the question if you want to have long running processes.  Note also that our pool scales well to hundreds of processes, where the multiprocessing pool degrades after N-cpu processes.

I'd much rather investigate shared-memory, etc, and refactor it into a generic async pool, not dependent on multiprocessing.Pool: a separate library.

**Comment by thedrow** [comment]
I had experience with hundreds of processes in Celery and the master seems to work really hard to communicate with them. Sometimes it's not consuming tasks because of that.

I think that @malinoff is right. We should be using the concurrent.futures interface. We don't have to use the default implementation.
That way, we'll get Celery running with a thread pool for free.

If we could avoid forking, we'd be more flexible right?
Say I want a pool of processes, each of them has 2 threads and each thread has a pool of 50 greenlets. 
This will allow me to parallelize I/O and CPU (if I have a C extension which releases the GIL).
Moreover, if and when PyPy STM will reach GA we'd be able to utilize real threads.

**Comment by ask** [comment]
>I had experience with hundreds of processes in Celery and the master seems to work really hard to >communicate with them. Sometimes it's not consuming tasks because of that.

That is not really an argument, multiprocessing.Pool would fall short eons before that happens, and I have no way to know what could be blocking it in your case.

 concurrent.futures is a horrible API, and misguided attempt at fixing the problems with threading in Python, sadly it used multiprocessing which is already broken.  I would like to avoid using it as much as possible, and especially not have users use it directly.  There's also nothing special about the thread pool there, it's like 10 lines of code and wouldn't be any hassle to duplicate.  Rather look at the thread pools in e.g. Akka and you have innovation that we can be inspired from, don't look at concurrent.futures.

I investigated using subprocess, but there was a reason I spent 6 months rewriting the pool.  C extensions don't perform much better when using threads in Python, but we can have a dedicated thread pool, and we may have a execv pool,  but using fork also has advantages: fast, copy on write memory, no pickling necessary to setup processes (a huge source of issues).

Programming dayjobs consists of combining libraries together, while the pool is an exciting opportunity to work on something challenging, and nothing in Python is even close to what could be achieved.  There's a lot of great implementations in other languages, research papers on wait-free algorithms etc.

If we want simple we can just start multiple `celery worker` instances instead of having any pool at all, and forego the concepts of remote control.

**Comment by ask** [comment]
Using threads in a C extension is also possibly safe now, as the GIL ensures the Python interpreter
is not allowed to run in threads.

When we have STM then we can simply provide an STM threads pool, as there's no reason to use multiprocessing if we can have real threads (noting that this pool will only be usable in a future version of PyPy).

We've tried both execv and concurrent.futures (multiprocessing) before.  It's not as simple
as "just use subprocess", or "just use concurrent.futures", if it was we'd be doing it already.

**Comment by thedrow** [comment]
Thanks for the answer :)

**Comment by malinoff** [comment]
@ask, @thedrow I just realized starting from py3.4 `multiprocessing` allows to do fork+exec almost out of the box: https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
