### ISSUE TITLE
Celery cant connect to remote server broker_url

### ISSUE THREAD

**Issue by prafulbagai** [celery/celery#3416]
I'm daemonizing celery following the [docs](http://docs.celeryproject.org/en/latest/tutorials/daemonizing.html). 

My BROKER_URL has been set in the following format:-  `'amqp://<user>:<password>@<ip>/<vhost>'`.

So, when I start celery manually, `celery worker -A app_name`, it connects with the remote server. But when I daemonize it, it connects with the localhost amqp. Any reason why?

Here is how I create my celery object:-

```
app = Celery('c26_search')    
app.config_from_object('django.conf:settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)
app.conf.update(
    CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend'
)
print app.conf.BROKER_URL  # prints remote url
```

My settings.py file:-

```
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
BROKER_URL = `'amqp://<user>:<password>@<ip>/<vhost>'`
```

Why is it acting so weirdly? Even it prints the remote IP url, but still tries to connects with the local amqp?

**Comment by ask** [comment]
How do you daemonize it? From you description it sounds like it's not being configured when you start it as a daemon.

Optimally you shouldn't use `app.conf.update` in 3.1 as this will finalize the app (it's fine in 4.0 since app.conf is lazy).  It's better to add this extra setting to your settings.py when using 3.1

**Comment by auvipy** [comment]
try master and report if it's still the issue
