### ISSUE TITLE
Guidance on Implementing Feature - Heterogeneous Tasks

### ISSUE THREAD

**Issue by costrouc** [celery/celery#3443]
I have become very fascinated with celery and have been using it with my workflows in high performance clusters. However, one major issue that I am having is that I am not able to fill up the workers with tasks that require different numbers of processes. For example:

Suppose I have a task that requires either 8, 16, 32, 64, or 128 cores (number of cores can be determined before running thus can be specified in the task). I would like to be able to start a worker and be able to consume from all these tasks with `celery -A app worker --concurrency=128`. Thus the worker could fill up with [8, 8, 16, 32, 32, 32], [128], [32, 64, 8, 8, 8, 8], etc. If I am correct this feature is not available in Celery. In fact looking around at all the available [workflow frameworks](https://github.com/pditommaso/awesome-pipeline) I have not found any that implement this feature. They all recommend running homogeneous tasks that require the same number of processes and then running multiple workers. This method will not work for me.

I would love to contribute to Celery and this feature would be an enormous help to my scientific workflows. Do you think it is a possible feature for me to implement? I have been using Python for about 4 years now and my knowledge of multiprocessing comes from mpi.

If so I will need some help with direction. I have been reading the source code in detail over the weekend and believe I know where I would need to start. Additionally, I have thoughts of a model that would fit the celery task model without requiring any changes. I would be happy to hear critiques. 

The concurrency implementation would inherit from `celery.concurrency.base.BasePool`. To me it looks like the `on_apply` method would be where most of the logic would be added to start the task.

The simple system for queuing of tasks that require differing processes would be in the configuration

``` python
queue_processes = {
     'queue_1': 8,
     'queue_2': 16,
     'queue_3': 32,
     'queue_4': 64,
     'queue_5': 128
}
```

This would be the simple solution. However, another solution I saw would be to use the amqp header exchange to have a parameter in the header such as processes=15. Thus all tasks could be in the same queue.

I am unsure how scheduling of the tasks would be handled and this looks to be the hardest part. It would be important to have a scheduling method since there are many possible ways to schedule tasks. Where would the modifications to the scheduling be done?

**Edit 1**:
With lots of redirection it looks like `kombu.Consumer` and the `on_message` routine handles the task delegation. Celery sets `on_message` to the `on_task_recieved` function constructed in `celery.worker.consumer.consumer.Consumer.create_task_handler`. Is this correct?

Details...
`Consumer.on_task_request` is how task is accepted and started. `on_task_request` is called by `task_message_handler` from strategy. `consumer.on_message`  calls `on_task_received` which calls `task_message_handler`.

Following further it looks like the scheduling logic is handled by Kombu?

**Comment by ask** [comment]
Hey!  If I understand what you describe correctly, this has been proposed for a while.

That is, the ability to define the number of processes to reserve for each task-type, or queue.

Since 3.1 this is technically achievable when using AMQP/Redis/Qpid/SQS as a broker, but not in 
previous versions or on transport using the fallback prefork pool implementation, as there a single
pipe is shared between all the processes.

When using the new async prefork pool there's one pipe for every process (two actually, input and output), so it would be possible to send one message to specific child process.

The bad news is that the async prefork pool is possibly the trickiest machinery to exist in our universe ;)

>With lots of redirection it looks like kombu.Consumer and the on_message routine handles the task >delegation. Celery sets on_message to the on_task_recieved function constructed in >celery.worker.consumer.consumer.Consumer.create_task_handler. Is this correct?

Celery uses kombu.Consumer to consume messages and kombu.Producer to send messages,
these are the low-level primitives and shouldn't be necessary to touch for this feature.

The worker is built using "bootsteps": http://docs.celeryproject.org/en/master/userguide/extending.html#blueprints

The Worker blueprint starts the pool and supporting services like autoreloading/autoscaling,
then it starts the Consumer blueprint which sets up everything related to sending and receiving messages.

The Tasks bootstep is what sets up the task consumer, including the callback called when
receiving a *task* message (Consumer.create_task_handler).

Execution of tasks is optimized by "precompiling" the steps needed into a closure, this is called
the "task strategy".  The consumer creates one strategy for every task type.

This strategy includes sending the task to the execution pool, from then on the child process
executes the task using `celery.app.trace` (here another closure is generated for every task, which is the "tracer").

1) Task handler creates `celery.worker.request.Request` object for the task
2) executes request using strategy (`Consumer.strategies[task_name]`)
3) Strategy executes task by sending it to the pool
4) Pool executes the task by calling the tracer (`celery.app.trace`)

There's no scheduling logic here, that is a pool implementation detail only.
The worker simply calls `pool.apply_async()`, and the pool is responsible for executing that.

The pool delegates tasks to the child processes by:

1) Without -Ofair:  Sending the job to the first writable process-inqueue, that we didn't recently write to.
2) With -Ofair: Sending the job to the first process that is not already executing a task.
   Note: fair will be default in 4.0

That scheduling happens here:
https://github.com/celery/celery/blob/master/celery/concurrency/asynpool.py#L737-L806

**Comment by ask** [comment]
Btw, I tried to describe at a high level what happens in the worker, but you don't really need to know any of that to implement this feature.

I can imagine we could initialize the pool with configuration similar to what you propose above:

```py
pool = Pool(slots={'hipri': 100, 'lopri': 28})
```

Creating the pool instance happens in the bootstep `celery.worker.components:Pool`::
https://github.com/celery/celery/blob/dacc71526c1b559a6f82acc8317909189b7346c0/celery/worker/components.py#L139-L155

Then `Request.execute_using_pool` could pass the slot to use (based on e.g. `task.slot` or `delivery_info['exchange']`:
https://github.com/celery/celery/blob/dacc71526c1b559a6f82acc8317909189b7346c0/celery/worker/request.py#L166-L196

```py
pool.apply_async(slot=self.task.slot, ...)
```

Then the pool writes the task to one of the file descriptors associated with that slot.

Rather than redirection I'm an optimist and  like to think of these as decoupled black-boxes with purposes that can be reused :)

(excluding strategies and tracers, these are ad-hoc abstractions made to execute tasks
faster and since everything is inlined it's pretty much impossible to reuse).
