### ISSUE TITLE
No error message when using incorrect task name in periodic task

### ISSUE THREAD

**Issue by SMontenez** [celery/celery#3446]
If you use an incorrect task name in the `CELERYBEAT_SCHEDULE` config setting, and start the worker with the `--beat` option, it starts correctly and doesn't even log a message to warn that an invalid task name has been passed to Celery.

It caused me troubles as I didn't know how to correctly pass my periodic task name to the dict (I used `'tasks': 'tasks.my_task'` instead of `'tasks': 'proj.app.tasks.my_task'` (Periodic tasks documentation is quite succinct), but Celery didn't warn me so I coudn't know why my periodic task wasn't called.

Is this "failing silently" behavior implement on purpose ? If so, why ?

**Comment by ask** [comment]
1) `--beat` is a convenience in development.

   For production you should start `celery beat` separately, and optimally
   supervised by something like supervisord, upstart or similar.

2) Beat is really just a service that sends messages at specified intervals.

   It may, or may not have access to the actual task implementation.
   If the task is in the task registry of the app used by beat, then it calls `task.apply_async()`,
   but if there is no implementation it calls `app.send_task(task_name, ...)`

Beat will not give you an error during startup, but the worker receiving the task
with the unregistered name will log an error.

The new periodic task configuration callbacks in Celery 4 will solve your problem though,
since you can refer to tasks directly: http://docs.celeryproject.org/en/master/userguide/periodic-tasks.html#entries

**Comment by ask** [comment]
Marking this is won't-fix, but it's really a non-issue when using the new 4.0 API to define periodic tasks.
