### ISSUE TITLE
Chord body is not respecting the set queue when header errors

### ISSUE THREAD

**Issue by tino** [celery/celery#3461]
I have a setup where there are two code bases. One which is part of the web stack, the other does long running calculations. They are separated because they have very different requirements in both libs and resources. I managed to create a chord of which the header runs in the 'long-running' queue, and the chord in the 'default' queue:

```python
header = [signature('long_running.tasks.calculate', kwargs=item)
                 for item in self.serialize_items()]
# The queue neest to be explicitly set back to the default queue on the
# callback, otherwise it is executed in the long running queue.
callback = signature(
    'systems.tasks.save_calculated_yields',
    kwargs={'system_id': self.id}
).set(queue=settings.CELERY_DEFAULT_QUEUE)
async_result = chord(header)(callback)
```

This works, unless a task in the header fails. Then the header is run in the long-running queue, resulting in:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 296, in trace_task
    on_chord_part_return(task, state, R)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 591, in on_chord_part_return
    self.chord_error_from_stack(callback, ChordError(reason))
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 138, in chord_error_from_stack
    backend = app._tasks[callback.task].backend
  File "/usr/local/lib/python2.7/dist-packages/celery/app/registry.py", line 26, in __missing__
    raise self.NotRegistered(key)
NotRegistered: u'systems.tasks.save_calculated_yields'
```

I am not familiar with the celery code base. Any suggestions on where to start with a patch?

**Comment by ask** [comment]
You're using "anonymous signatures" (in lack of a better term - they don't have any associated task class).

The worker tries to respect tasks having separate backends, so the chord error handler looks up the type of task, and fails.  I changed it so that it can also handle anon signatures, but that is so far only in Celery 4.

A much better way of calling tasks by name is to use header tasks:

```py
@app.task(name='long_running.tasks.calculate')
def calculate(arg1, arg2, **kwargs):
    pass

@app.task(name='systems.tasks.save_calculated_yields')
def save_calculated_yields(result, system_id=None, **kwargs):
    pass

header = [calculate.s(**item) for item in self.serialize_items()]
# The queue neest to be explicitly set back to the default queue on the
# callback, otherwise it is executed in the long running queue.
callback = save_calculated_yields.s(system_id=self.id).set(
    queue=settings.CELERY_DEFAULT_QUEUE)
async_result = chord(header)(callback)

```

Using anon-signatures is more rare, so you're more likely to be the first to encounter a bug in using them.

NOTE: In Celery 4 task signatures are actually checked when you call a task, so make sure the header signatures match.
