### ISSUE TITLE
Allow disable Celery warning on restart

### ISSUE THREAD

**Issue by israel-tk** [celery/celery#3462]
I have Celery configured to send events >= warning to Sentry, but everytime a Celery worker restarts a warning is emitted:

`[2016-06-26 20:30:23,005: WARNING/MainProcess] celery@myhost ready`

This is really annoying since restarting a worker is somewhat expected, and the warning clutters the logs if you want to use warnings in your app to notify other issues.

See http://stackoverflow.com/questions/38041908/celery-worker-remove-warn-message-warning-mainprocess-celerylocalhost-read

Could some kind of runtime flag be activated to avoid emitting this warning?

**Comment by alexkiro** [comment]
FWIW, it seems that this is happening because the messages is dumped to STDOUT, instead of the logger. And celery has an options that redirects the STDOUT/STDERR to the logger with a default level of WARNING. You can change that level in the [config](http://docs.celeryproject.org/en/latest/configuration.html?highlight=redirect_stdouts_level#celery-redirect-stdouts-level), however one might still want _other_ output to be consider warning, so this is not really the best solution:

```
    'CELERY_REDIRECT_STDOUTS_LEVEL': 'INFO',
```

In the worker code:

```
    def on_consumer_ready(self, consumer):
        signals.worker_ready.send(sender=consumer)
        print('{0} ready.'.format(safe_str(self.hostname), ))
```

**Comment by Tmakinde** [comment]
This just solved my problem
