### ISSUE TITLE
result_exchange and result_exchange_type have no effect at 4.0.0rc5

### ISSUE THREAD

**Issue by kogule** [celery/celery#3515]
`result_exchange` and `result_exchange_type` have no effect.

Taking a look at `celery/backends/rpc.py`, they are used at `BasePRCBackend.__init__` but the actual exchange construction is handed over to `self._create_exchange` which doesn't exist at class `BaseRPCBackend`.  The derived class `RPCBackend` has it, but it just returns self.Exchange (= `kombu.Exchange`).

It seems to be weird, although I'm new to Celery and ignorant of it.

**Comment by ask** [comment]
The BaseRPCBackend was used as the parent for both the amqp and rpc backend for a period, but then it was reverted.  I changed it so that there's no BaseRPCBackend, only RPCBackend.

I don't think there's any reason to specify the exchange and exchange type arguments, but if you really wanted to you could subclass and define _create_exchange.   The exchange defaults conf.result_exchange, but the RPC backend doesn't use an exchange by name, it explicitly sets it to None to use the anon-exchange (which is faster by bypassing routing).

**Comment by kogule** [comment]
Hmm, do you mean  [this description](http://docs.celeryproject.org/en/master/userguide/configuration.html#rpc-backend-settings) is wrong?  `result_exchange` and `result_exchange_type` is under "RPC backend settings" in 4.0.0rc5 document while `CELERY_RESULT_EXCHANGE` and `CELERY_RESULT_EXCHANGE_TYPE` is under "AMQP backend settings" in 3.1.2.

**Comment by ask** [comment]
Ah, in the configuration section. Thanks! I just removed those now that the old AMQP result backend is deprected: 4dd775611922bd2db71e5f7ca9869304cd19f6c9
