### ISSUE TITLE
How to stop a workflow in 4.0?

### ISSUE THREAD

**Issue by rsalmei** [celery/celery#3550]
Hello again,

I've always used in 3.1 the following code to stop a workflow:
```
    # if something, stop workflow chain.
    self.request.callbacks = None
```
Self is the `bind=true` task param.

I've noticed that this doesn't work anymore in 4...
How to stop prematurely a chain now?

**Comment by ask** [comment]
Hey!  In the new task message protocol chains don't use the `callbacks` field anymore, instead they have a `dedicated` chain field.

In previous versions there was a limit to the number of tasks in a chain, as the data structure was recursive you'd hit this limit when the stack limit blows up.  With the new `chain` field this is not a problem anymore.

To stop a workflow in 4.0 you'd have to set `self.request.chain = None`, and you could do both for compatibility with all versions:

```
self.request.chain = self.request.callbacks = None
```

**Comment by Eduard-gan** [comment]
That would be cool if this thing was stressed enough in migration guide because it's not just new cool feature(which it is actually!) it's a major change in chains API. It can be very important.


For example in our company we scrape pages from Google for target domains, page by page(up to 10). For this purpose we launch chains. The task itself uses this to terminate the chain if we found our target domain and we don't need more pages.

```
if we_found_what_we_looked_for and self.request.callbacks:
    self.request.callbacks[:] = []
```

Of corse i read the migration guide and thought that everything will be ok, but i broke the production data because tasks lost ability to brake the chains and gathered results were overwritten.
