### ISSUE TITLE
Worker not consuming tasks in v4

### ISSUE THREAD

**Issue by mafrosis** [celery/celery#3603]
## Checklist

- [x] This bug concerns 3.1.25 vs 4.0.0. Redis is my broker.
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce

My celery configuration:

    config['BROKER_URL'] = 'redis://localhost:6379'
    config['CELERY_CREATE_MISSING_QUEUES'] = False

    exchange = Exchange('ogreserver', type='direct')
    config['CELERY_QUEUES'] = (
        Queue('low', exchange, routing_key='low'),
        Queue('high', exchange, routing_key='high'),
    )

    config['CELERY_DEFAULT_QUEUE'] = 'low'
    config['CELERY_DEFAULT_EXCHANGE'] = 'ogreserver'
    config['CELERY_DEFAULT_ROUTING_KEY'] = 'low'

    config['CELERY_ACCEPT_CONTENT'] = ['pickle']
    config['CELERY_TIMEZONE'] = 'Europe/London'

## Expected/Actual behaviour

The tasks are consumed in 3.1.25, but are not consumed in 4.0.0.

Seems to me there is something different around the default exchange? I have read through the docs but didn't find anything specific. However, please take a look at these logs from Redis in 3.1.25 and 4.0.0:

*3.1.25*:

    1479385325.139261 [0 127.0.0.1:33636] "LPUSH" "high" "{\"body\": \"gAJ9cQEoVQdleHBpcmVzcQJOVQN1dGNxA4hVBGFyZ3NxBChYIAA.....cmJhY2tzcQ1OVQd0YXNrc2V0cQ5OVQJpZHEPVSQyOTBkNGYwOC03N2U3LTRjMDktODRiZi00YWI3MDc4ZDNiNTlxEFUHcmV0cmllc3ERSwBVBHRhc2txElUcb2dyZXNlcnZlci50YXNrcy5zdG9yZV9lYm9va3ETVQl0aW1lbGltaXRxFE5OhlUDZXRhcRVOVQZrd2FyZ3NxFn1xF3Uu\", \"headers\": {}, \"content-type\": \"application/x-python-serialize\", \"properties\": {\"body_encoding\": \"base64\", \"correlation_id\": \"290d4f08-77e7-4c09-84bf-4ab7078d3b59\", \"reply_to\": \"2bdb925f-424e-3b23-99ce-8e045c46fc5c\", \"delivery_info\": {\"priority\": 0, \"routing_key\": \"high\", \"exchange\": \"ogreserver\"}, \"delivery_mode\": 2, \"delivery_tag\": \"102efc23-b185-49d6-bc6c-705f4cd6e3c1\"}, \"content-encoding\": \"binary\"}"

*4.0.0*:

    1479385105.604181 [0 127.0.0.1:33624] "LPUSH" "high\x06\x169" "{\"body\": \"W1siYzk4NTBkYzVhMWQwMTY4MTZiYWE4OGFlODZiZTYyN2IiLCAiMDQ4MzZjYjA5ZmEyMDNhZDc0ZW.....NGVkODUyN2EzOWU2Y2EyIiwgImF6dzMiLCAibWFmcm8iXSwge30sIHsiY2hvcmQiOiBudWxsLCAiY2FsbGJhY2tzIjogbnVsbCwgImVycmJhY2tzIjogbnVsbCwgImNoYWluIjogbnVsbH1d\", \"headers\": {\"origin\": \"gen14355@vagrant\", \"root_id\": \"e572494c-fc9f-4b6f-b683-beecc1ff206b\", \"expires\": null, \"id\": \"e572494c-fc9f-4b6f-b683-beecc1ff206b\", \"kwargsrepr\": \"{}\", \"lang\": \"py\", \"retries\": 0, \"task\": \"ogreserver.tasks.store\", \"group\": null, \"timelimit\": [null, null], \"parent_id\": null, \"argsrepr\": \"('mafrosis')\", \"eta\": null}, \"content-type\": \"application/json\", \"properties\": {\"priority\": 0, \"body_encoding\": \"base64\", \"correlation_id\": \"e572494c-fc9f-4b6f-b683-beecc1ff206b\", \"reply_to\": \"01c1be99-f093-3334-bbb6-1a2e75305a58\", \"delivery_info\": {\"routing_key\": \"high\", \"exchange\": \"\"}, \"delivery_mode\": 2, \"delivery_tag\": \"5c006365-a725-4e97-9bff-013844f12232\"}, \"content-encoding\": \"utf-8\"}"

Note the `delivery_info` `exchange` field is blank in the message for v4.

Thanks! I'm huge fan/user of celery. You are awesome @ask

**Comment by ask** [comment]
Thanks for the kind words :)

In Celery 4 the anon-exchange is used by default for direct routing: setting the exchange to the empty string means you can specify the exact queue name in the routing key and it will deliver the message there directly, bypassing the routing stage.

If you set the default queue, you shouldn't need to set the default exchange and routing key, as it will take those defaults from ``CELERY_QUEUES['low']``.

Hard to say otherwise, maybe some other worker is stealing the messages?  Are you sure you have shut down all old workers?

**Comment by andyneff** [comment]
I think I'm having a similar problem

My tasks were set up such that I had a default queue, and I would specify a different routing key (in the decorator, but for the sake of this issue I'll specify it in the apply_asyn call, which has the same behavior)

```
CELERY_TASK_DEFAULT_QUEUE = 'my_queue'
CELERY_TASK_QUEUES = [
Queue('my_queue', Exchange('my_exchange'), routing_key='default'),
Queue('gpu_queue', Exchange('my_exchange'), routing_key='gpu'),
]
```

RabbitMQ is my broker

And all tasks went to `my_queue` by default, and when I wanted a gpu task, I set `routing_key='gpu'`, and it would go to the `gpu_queue`, and this all worked in Celery 3.1.24

Now in celery 4.0.0, if I specify only the routing key

```
run_ocl_info.apply_async(routing_key='gpu')
```

It is ignored, and goes to the `my_queue`

```
[2016-11-30 22:40:59,229: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7fde851462a8> (args:('voxel_globe.tests.tasks.run_ocl_info', '63', {'origin': 'gen62@4811100bc78e', 'lang': 'py', 'task': 'voxel_globe.tests.tasks.run_ocl_info', 'group': None, 'root_id': '63', u'delivery_info': {u'priority': 0, u'redelivered': False, u'routing_key': u'my_queue', u'exchange': u''}, 'expires': None, u'correlation_id': '63', 'retries': 0, 'timelimit': [None, None], 'argsrepr': '()', 'eta': None, 'parent_id': None, u'reply_to': '475b0528-610c-3589-aab5-75976b03799c', 'id': '63', 'kwargsrepr': '{}'}, u'[[], {}, {"chord": null, "callbacks": null, "errbacks": null, "chain": null}]', 'application/json', 'utf-8') kwargs:{})
```

Now if I specify the exchange too, it works.

```
run_ocl_info.apply_async(exchange='my_exchange', routing_key='gpu')
```

```
[2016-11-30 22:44:48,014: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7fa073a922a8> (args:('voxel_globe.tests.tasks.run_ocl_info', '66', {'origin': 'gen62@4811100bc78e', 'lang': 'py', 'task': 'voxel_globe.tests.tasks.run_ocl_info', 'group': None, 'root_id': '66', u'delivery_info': {u'priority': 0, u'redelivered': False, u'routing_key': u'gpu', u'exchange': u'my_exchange'}, 'expires': None, u'correlation_id': '66', 'retries': 0, 'timelimit': [None, None], 'argsrepr': '()', 'eta': None, 'parent_id': None, u'reply_to': '475b0528-610c-3589-aab5-75976b03799c', 'id': '66', 'kwargsrepr': '{}'}, u'[[], {}, {"chord": null, "callbacks": null, "errbacks": null, "chain": null}]', 'application/json', 'utf-8') kwargs:{})
```

I tried adding `CELERY_TASK_DEFAULT_EXCHANGE='my_exchange'` and it made no difference.

**Note**: I can also specify the exact queue name in the queue argument (`run_ocl_info.apply_async(queue='gpu_queue')`) and that works, but I have all my tasks set up to specify the routing key currently. I'm not sure what you mean by

> In Celery 4 the anon-exchange is used by default for direct routing: setting the exchange to the empty string means you can specify **the exact queue name in the routing key** and it will deliver the message there directly, bypassing the routing stage.

So is it expected behavior that specifying the routing_key only does not work, because it did in Celery 3, or is this a bug?

**Comment by ask** [comment]
@andyneff The comment about the anon-exchange is only in relation to using the `queue` argument, since that means "send message to queue x" in Celery.

Using exchange/routing_key pairs, without a queue, means you want to use the low-level AMQP API instead.  Usually that will involve using the topic exchange type, or other more experimental exchanges, not direct exchanges, as for direct queue->queue mapping it's usually better to just use the queue argument.

Note that when you specify the exchange/routing_key only then the Queue won't be declared by the producer, so if no worker has started yet declaring the queues, the messages will be silently dropped by the broker.

**Comment by mafrosis** [comment]
I'm going to close this as I'm now successfully using Celery v4. I'm not sure what was wrong before - I suspect user error. If @andyneff still has a problem, I suggest opening a new and separate issue.
