### ISSUE TITLE
Class Tasks are never acked when `tasks_acks_late=True`

### ISSUE THREAD

**Issue by litwisha** [celery/celery#3645]
## Checklist

-```software -> celery:4.0.0 (latentcall) kombu:4.0.0 py:3.5.0
billiard:3.5.0.2 py-amqp:2.1.1
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled
task_acks_late: True
imports: ['app.tasks']```

-  I have verified that the issue exists against the `master` branch of Celery.
## Steps to reproduce
If I call a task from a module where celery app is defined - it’s ok.
But when I call a task in a different module, it’s always unacked in rabbitmq, even if a task is finished. So it blocks other task to be consumed by worker.
I created a short  project with an example.
https://github.com/litwisha/celery_test
Celery app is defined in app/__init__.py. Also in app/__init__.py I register a task using an import_module to avoid circular imports.

I run a task from main.py. And it remains unacked even after a task is finished.
In celery 3.1.2 it works fine with the same code(just setting's name changed from task_acks_late to CELERY_TASK_LATE)

## Expected behavior
Task is acked when it finishes

## Actual behavior
Task stays unacked when it finishes

**Comment by ask** [comment]
I'm not sure why people insist on using class-based tasks like this :/

I would strongly suggest you use the task decorator instead, it's lazy and enables you to delay configuration of the app, and it solves many strange edge cases were being hacked around using the special metaclass in 3.1:

```py
# celery_test/app/tasks.py

from .app import celery_app  # < note the . in front of app here: never use implicit relative imports

@celery_app.task
def test(data='hello world'):
    from time import sleep
    sleep(5)
    return data
```


If you absolutely insist on using class based tasks there will be a new way to register them
in 4.0.1:

```
from .app import celery_app

class TestCeleryTask(
    celery_app.Task,
):
    def run(self, data='hello world'):
        from time import sleep
        sleep(5)
        print(data)
celery_app.register_task(TestCeleryTask())
```

The above code may not work properly under Windows, this is due to how Python modules can be executed multiple times, so you end up with multiple instances of this task.  The old metaclass handled this case with a super hairy hack, but the app.register_task does not.

The above code will also force finalization of the app early, which is especially bad if you're using Django as it means the settings may be loaded too early and create a recursive loop.

**Comment by cjarv** [comment]
Is there a solution for this on windows?
