### ISSUE TITLE
Specifying app/backend in GroupResult.restore is slightly awkward

### ISSUE THREAD

**Issue by pelme** [celery/celery#3651]
In Celery 3.x I used `GroupResult.restore('some-id')` and it somehow found my app and figured out the backend (not sure how, but it worked).

In Celery 4.x this does not work (it does not find the backend and crashes). That makes sense to me (I like the idea of explicit apps a lot!). `GroupResult.restore()` does not accept a `app` argument which would be convenient. It does however support a `backend` argument, so I changed my code to use `GroupResult.restore('my-id', backend=app.backend)` and everything is fine.

However, to me this is not that super-intuitive, my suggestion is that we should add an `app` kwarg to `restore()` that can be used like:

```py
GroupResult.restore('someid', app=app)
```

Do you think this makes sense? Then I'd be happy to work on a PR to add the argument!

**Comment by ask** [comment]
Yeah, I definitely think that makes sense!  The argument was probably named backend before the concept of apps.

**Comment by pelme** [comment]
I was not aware, but GroupResult is also available on the app, another way to solve this is to use:
```py
app.GroupResult.restore('someid')
```

**Comment by davidt99** [comment]
I'm having an issue with this fix, after upgrading to celery 4. `app` in [result.py#877](https://github.com/celery/celery/blob/master/celery/result.py#L877) is a property, not an instance of app (which make sense since it's accessed by `cls.app`) so it doesn't have backend property.
I'm passing the current app to the method as a workaround but it's still an issue since it breaks working celery 3 code.
