### ISSUE TITLE
Redis Backend has a memory leak with AsyncResult.get()

### ISSUE THREAD

**Issue by jnill** [celery/celery#3813]
## Checklist
- [X] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:3.5.2
            billiard:3.5.0.2 redis:2.10.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://[redacted]
```
### Celery Settings
```
BROKER_BACKEND = 'redis'
BROKER_URL = environ.get('REDIS_URL')
CELERY_RESULT_BACKEND = environ.get('REDIS_URL')
CELERYD_CONCURRENCY = 1
BROKER_POOL_LIMIT = 0
CELERY_TASK_RESULT_EXPIRES = 60
CELERY_MAX_CACHED_RESULTS = 1
CELERY_DISABLE_RATE_LIMITS = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
```
- [X] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
1) Create celery app with Redis as transport and Backend (same cache for both)
2) Create a task within the celery app that returns a result
``` python
@CELERY_APP.task
def add():
    return 1 + 2
```
3) Execute `add.apply_async().get()` somehow (I have a Django app on Heroku so I made an endpoint for it)
4) Use `objgraph.show_growth()` to see that `AsyncResult` objects are leaking

## Expected behavior
`AsyncResult` objects get released after the result is received after the `AsyncResult.get()` call.  The `AsyncResult` is properly released when getting the result from `AsyncResult.result`.

## Actual behavior
`AsyncResult` objects accumulate in the `AsyncResult.backend._pending_results.concrete` dict.  If the `AsyncResult` is popped from the dict, it is released as expected.
Note that the leak does not occur when executing tasks eagerly.

## Code sample
``` python
@CELERY_APP.task
def add():
    return 1 + 2

def add_request():
    response = add.apply_async().get()

    import objgraph
    objgraph.show_growth()
```

**Comment by toorsukhmeet** [comment]
+1 
I'm seeing leaks with AsyncResult on Celery 4.0.2 as well.

```
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.12
            billiard:3.5.0.2 py-amqp:2.1.4
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:rpc://admin:**@localhost/
```

**Comment by vinodc** [comment]
Seeing this behavior as well.
@ask [celery.result.ResultSet._on_ready](https://github.com/celery/celery/blob/master/celery/result.py#L482) no longer appears to be used anywhere, after [this change](https://github.com/celery/celery/commit/072ad1937f7d445a496369f0370033a0ba558ddf#diff-58b5816dbb95159ae9810e56eac54312L440). The promise directly calls `self.on_ready` now Would that contribute to why the pending result is never removed?

**Comment by vinodc** [comment]
The core issue appears to be that `AsyncResult._on_fulfilled` is never called to remove the pending result because the weakref to the function is dead-on-arrival since `_on_fulfilled` is a bound method (https://stackoverflow.com/a/599486/827437). 

Was [the change to use weak references](https://github.com/celery/celery/commit/b52d44f1a2c916ccfebb0d144589ff74ac0079b7) made in response to https://github.com/celery/celery/issues/3436#issuecomment-245995843? The weak-refs in promises appear restricted to just this module. Removing `weak=True` causes the memory leak to disappear since the results are removed as expected. I do not notice any other memory leaks as described in issue #3436, even after 1000+ async task calls.

I've added this change as well as the one related to my previous comment in PR #4131.

**Comment by adrienjt** [comment]
I encountered the same issue, with critical consequences. I'm running 4.1.0, would rather not run master. So while #4131 isn't released yet, I came up with a work-around: call `AsyncResult.forget()` after `AsyncResult.get()`. It's a little extreme, but if you can afford it, it patches the memory leak.

**Comment by auvipy** [comment]
you can try from master

**Comment by adrienjt** [comment]
@auvipy I do not want to run master in production. My message above is just an FYI of the workaround I'm using, in case anybody in my situation stumbles upon this page.

**Comment by mctd** [comment]
I'm using Celery 4.1 with a fire-and-forget logic for hundreds of thousands tasks: chords that ends with saving into a database, returning no results.
Because of that issue, my task producer's memory will grow until the process gets killed by the OS. The quick and dirty workaround I found is to periodically call `app.backend._pending_results[0].clear()`.
Calling `AsyncResult.forget()` will dramatically drop the performances, which is not an option.
Any better suggestion until the next release fix? I won't run master in production either.
