### ISSUE TITLE
Celery stops answering on inspect queries when number of tasks received is greater then the number of workers

### ISSUE THREAD

**Issue by uruz** [celery/celery#3981]
## Checklist
software -> celery:3.1.25 (Cipater) kombu:3.0.37 py:2.7.3 billiard:3.3.0.23 pymongo:3.2.1
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:mongodb results:disabled

I was not able to check the issue against the master or celery 4.x branch, but I've read related code and it was not changed much since 3.x.

## Steps to reproduce
I am using the latest 3.x version of Celery with mongodb broker with results ignored, and a prefork concurrency type. Some of my tasks are very memory-consuming, so I have a dedicated queue and a very limited number of workers. Once this worker-pool got too many tasks (one more then the number of available workers), celery stops answering on `celery inspect active` queries (and any other pidbox requests).

## Expected behavior
Celery answers on the `celery inspect active` queries.

## Actual behavior
Celery does not answer on the `celery inspect active` queries.

## Debugging
I've traced the situation down the `putlock` inside the `billiard`. When celery consumes the message from the mongo, it acquires one slot in the semaphore. Once all slots are exhausted, it blocks. This is the situation when all the workers are busy processing the task and celery reads one more task. When celery/billiards blocks on semaphore, it stops draining messages from the mongodb, even the helper ones – so it stops answering on pidbox events.

## Resolving the issue
I was able to resolve the issue by using custom `Strategy` for my tasks. `default` strategy calls `handle` method, and it's the alias for `consumer.on_task_request`. `consumer.on_task_request` calls (through a chain of calls) `billiard`'s `Pool.apply_async` with a `waitforslot=True` argument and blocks on `self._putlock.acquire()`. I thought that inside the strategy we already know that the pool is busy and call would block, and instead of trying to put the message into internal queue we could check if all the workers are busy, and if they are we, we could wait a bit. There is code that does almost that, but it's about rate limiting. (I should clarify that I don't use rate limiting).
So instead of checking for the number of messages per second, I was able to check if the semaphore is busy with the following code:

```
HOLD_SECONDS = 2
def consumer_has_room(consumer):
    semaphore = consumer.pool._pool._putlock
    cond = semaphore._Semaphore__cond
    with cond:
        value = semaphore._Semaphore__value
        return value > 0


def loop_until_semaphore(consumer, req, callbacks):
    if consumer_has_room(consumer):
        task_reserved(req)
        if callbacks:
            [callback() for callback in callbacks]
        consumer.on_task_request(req)
    else:
        consumer.timer.call_after(
            HOLD_SECONDS, loop_until_semaphore, (consumer, req, callbacks),
        )
```

In my strategy, I call the `loop_until_semaphore` instead of bare `handle` (`consumer.on_task_request` alias). I am not proposing my code as a patch because of two things: first, I'm not sure that I intercepted in the right place: celery is a huge project and it's difficult to understand the place for the changes. And second: my code is surely limited to the concurrency type and eventloopless broker I use, so it's not universal.

I would appreciate any comments – am I doing it right or wrong, are `celery inspect` queries expected to work in the environment I have. I would be happy to submit a good patch, but I am not very experienced with the celery code and it's hard for me to make the patch universal.

**Comment by thedrow** [comment]
We don't support MongoDB as a broker anymore. However, this sounds like a real problem which we need a way to verify on RabbitMQ/Redis. Can you try the same process? Can you provide me with a script that recreates the hang?

**Comment by uruz** [comment]
I cannot reproduce this bug with redis. I believe it is specific for the un-evented brokers, i.e. brokers whose `connection.is_evented` is `False`. Both RabbitMQ and Redis have `supports_ev = True` in their `kombu.transport.*` modules. Amazon SQS, however, has its `supports_ev` equal to `False`, so maybe it's prone to this bug. I haven't tested it yet though. I'll try to provide a script in the next few days.
I haven't seen any announcement that MongoDB is not a supported broker anymore, could you please point me on the docs? Does it mean that any mongodb-related bugs will not be fixed and eventually any MongoDB-related code (when used as a broker) will be gone?

**Comment by thedrow** [comment]
It was removed from the brokers list (http://docs.celeryproject.org/en/latest/getting-started/brokers/index.html#broker-overview) and mentioned in the release notes of 4.0 (http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#features-removed-for-lack-of-funding)

**Comment by pwest09** [comment]
Is there a suggested workaround for this issue?  When I was doing some initial testing with Celery 3.1.25 I found what seems to be a very similar issue with all celery inspect commands using Celery 3.1.25 and RabbitMQ as the broker where inspect would not answer while there were more tasks sent to the worker than its pool size.  I cannot run the master branch since I am using Windows as my operating system so it may not be an issue in 4.x with RabbitMQ.

I started a single worker with --concurrency 3 and then sent it 4 tasks that run for a significant period of time (for loops that add from 1 to 2^32), no celery inspect command would find the worker node, and all would return:
Error: No nodes replied within time constraint
Though Flower will still see all the tasks and list the first three tasks as started and the fourth as received and the log would say they are received (I'm at UTC -4 so there's a 4 hour time difference between Flower and the logs).

From logs:
[2017-05-25 17:49:30,479: INFO/MainProcess] Received task: mccoytasks.add_alot[ac6e5e1c-176a-44ce-abf2-64038e655e34]
[2017-05-25 17:49:31,296: INFO/MainProcess] Received task: mccoytasks.add_alot[6203a831-f92f-4979-bbc0-318b5a8b36d0]
[2017-05-25 17:49:32,048: INFO/MainProcess] Received task: mccoytasks.add_alot[a2439f5d-40d4-4fb2-9d20-817115d697f2]
[2017-05-25 17:49:33,053: INFO/MainProcess] Received task: mccoytasks.add_alot[9ba9c8e8-bb9d-4e9d-b042-50ce593b8d92]

From Flower:
![image](https://cloud.githubusercontent.com/assets/28899555/26472237/2fb17912-4173-11e7-8e9b-3ddd82683baf.png)

I also could not terminate tasks from either the command line or Flower while there were too many tasks.  If I waited for enough tasks to finish such that the number of tasks running was less than the worker pool, celery inspect commands worked again, as well as terminating tasks.  

My setup:
software -> celery:3.1.25 (Cipater) kombu:3.0.37 py:3.5.3
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Windows arch:64bit, WindowsPE imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:pyamqp results:rpc:///

BROKER_URL: 'amqp://test_user:********@127.0.0.1:5672//'
CELERY_RESULT_BACKEND: 'rpc:///'

I also made a post on the Google Groups page, though at the time I thought this was expected based on the worker documentation, since I thought it was due to the tasks blocking the waiting control commands, and was asking about a workaround for what I was actually trying to do.  Find it here, if interested: [https://groups.google.com/forum/#!topic/celery-users/tRgPz_XJvmc](url)

**Comment by mganglb** [comment]
for developer, who have the requirement to work with **python 2.7** I know we have  2021 :/

This problem exists in the following configuration with **redis** as well.
*  redis==2.10.6:  works with "Redis-x64-2.8.2104 server"
*  celery==3.1

best regards
mgangl
