### ISSUE TITLE
Beat task run on-load

### ISSUE THREAD

**Issue by jheld** [celery/celery#3988]
## Checklist

- [x] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
software -> celery:4.0.2 (latentcall) kombu:4.0.2 py:2.7.12
            billiard:3.5.0.2 redis:2.10.5
- [x] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
Load celery beat with a task added to the periodic scheduler for every 30 minutes. It will not run until 30 minutes have passed.
## Expected behavior
I have some tasks that have long-running intervals (30 minutes, 1 day), and I'd like beat to have an option to run the task on-load, and then on the interval. I imagine this would be a setting on the periodic scheduler init for that task.
## Actual behavior
The task does not run until the interval has passed one time.

I wouldn't mind submitting the patch myself, assuming it's something the project is interested in at all.

**Comment by imanhodjaev** [comment]
@jheld you shoul define `crontab` task in this case.

**Comment by imanhodjaev** [comment]
```python
from celery.schedules import crontab

beat_schedule = {
    'run_every_30_minutes': {
        'task': 'collect.me',
        'schedule': crontab(minute='*/30'),
}
```

**Comment by thecardcheat** [comment]
@imanhodjaev use of `crontab` still won't provide run immediately behavior. He would then just end up waiting until the next `crontab` entry, which for a task with a long interval could be undesirable if a problem occurs well shy of its next scheduled run.

There really should be behavior to allow a schedule to be reset and/or run immediately. I can see no method to work a task within a schedule after it is set, which means worst case you could end up waiting the entire interval for the task to run again and realistically you would need to time your code updates if you do not want to interrupt a task because you cannot restart it immediately. Without support to "run now" and reset the interval, how do you prevent a scheduled task from running over itself if you need to run it immediately and the next schedule is within the run time?

**Comment by auvipy** [comment]
let us know the status if you were able to fix

**Comment by WesDowney** [comment]
This functionality of running immediately and then after a certain period of time is available. Instead of `'schedule': crontab(minute='*/30'),`, it would be `'schedule': 1800,` since there are 1800 seconds in 30 minutes. 

The [docs have an example](http://celery.readthedocs.io/en/latest/userguide/periodic-tasks.html#entries) of this: 
```app.conf.beat_schedule = {
    'add-every-30-seconds': {
        'task': 'tasks.add',
        'schedule': 30.0,
        'args': (16, 16)
    },
}```

**Comment by auvipy** [comment]
whats the update on this issue? should we close this? any changes needed?

**Comment by jheld** [comment]
So I've tried the example posed by @WesDowney and by the docs, but I haven't seen it actually work that way.

I specifically specify the schedule in that manner, but it never runs immediately the first time through with a bare schedule.

The only time it approaches the idea of an immediate first run is if the schedule file on startup contains a recent time table for the run.

If there is a way to accomplish this (without the use of cron), I haven't seen any examples of it.
