### ISSUE TITLE
Build task documentation with sphinx fails (error while formatting arguments)

### ISSUE THREAD

**Issue by remileduc** [celery/celery#3993]
## Checklist

this has been tested with both version 4.0.2 and master (8c8354f)

## Steps to reproduce

```bash
$ git clone https://github.com/inveniosoftware/invenio-indexer.git
$ cd invenio-indexer/
$ pip install -e .[all]
$ sphinx-build -qnNW docs docs/_build/html
```

You can see that `invenio-indexer` correctly implements the requirements to document a celery task:
- https://github.com/inveniosoftware/invenio-indexer/blob/master/docs/conf.py#L52
- https://github.com/inveniosoftware/invenio-indexer/blob/master/docs/api.rst#celery-tasks

## Expected behavior

It should build the documentation of the tasks. This is **working** in Celery 3.1.25.

## Actual behavior

I get the following error:

```
invenio-indexer/docs/api.rst:54: WARNING: error while formatting arguments for invenio_indexer.tasks.index_record: 'NoneType' object is not callable
```

Am I missing something? Should it work differently than Celery 3?

**Comment by hachreak** [comment]
It looks like the problem is [format_args()](https://github.com/celery/celery/blob/3.1/celery/contrib/sphinx.py#L54) with python 2.
The [getfullargspec(()](https://github.com/celery/vine/blob/master/vine/five.py#L349) looks not really equivalent to the python 3 version.
This is an example of [task (with at least an argument)](https://github.com/inveniosoftware/invenio-indexer/blob/master/invenio_indexer/tasks.py#L44) that will produce the warning.
