### ISSUE TITLE
 Server closed the connection unexpectedly

### ISSUE THREAD

**Issue by mrgaolei** [celery/celery#4011]
https://github.com/celery/django-celery/issues/46

In my server there is a same exception as above.

Is it a PostgreSQL's bug?

**Comment by cjds** [comment]
I can reproduce this. This is the version of celery I'm using celery[redis]==4.0.2

**Comment by goinnn** [comment]
I had this bug with celery 3 and I have this error with celery 4. 

is it related? https://github.com/psycopg/psycopg2/issues/443 If you read the relative pull request, this bug is not merged still https://github.com/psycopg/psycopg2/pull/446

I have created a fork with the last psycopg2 and these changes: https://github.com/goinnn/psycopg2/tree/2_7_1_extra
