### ISSUE TITLE
Celery homepage shows 0 downloads

### ISSUE THREAD

**Issue by matthiaskoenig** [celery/celery#4040]
## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
go to
http://www.celeryproject.org/
## Expected behavior
Show the actual number of downloads on the homepage.
## Actual behavior
Does only show 0 Downloads (see screenshot attached)
This is a bug, but does look like nobody is downloading the project.

![celery](https://cloud.githubusercontent.com/assets/900538/26247638/1ab91a70-3c9f-11e7-8b90-e134002f745b.png)

**Comment by auvipy** [comment]
you are right

**Comment by fireantology** [comment]
The problem seems related to pypi.
If you look at the json here you will see that is all to 0: https://pypi.python.org/pypi/celery/json

Seems something recurrent linked to pypi redis but I don't think there is something we can do for now. At max we could fetch the total download of last version.
Any suggestion is welcome.

pypa/pypi-legacy#396

**Comment by auvipy** [comment]
I think that could be a sane work around for now

**Comment by auvipy** [comment]
this issue should be tracked on website repo

**Comment by thedrow** [comment]
Yes you are right. Closing this.
Thanks for the report!
