### ISSUE TITLE
Is it possible to get results from broadcast tasks?

### ISSUE THREAD

**Issue by ChillarAnand** [celery/celery#4149]
[Celery docs](https://celery.readthedocs.io/en/latest/userguide/routing.html#broadcast) suggests it’s a good idea to set the task.ignore_result attribute for broadcast.

We have 10 servers with celery workers listening to a broadcast queue. There is a `foo`  task which returns some system stats. This task returns different results on different machines.

I am trying to run that task(foo.apply_async) and get results from all the machines. Unfortunately, tasks sent have same id for all workers and `foo.result` has only 1 result.

Is there a way to broadcast a task to all workers and get results from all of them?

**Comment by georgepsarakis** [comment]
From what I understand from the documentation, I would say that the answer is no, you will just get one of the results. You must probably find an alternative way of recording the statistics, e.g. writing them to a time-series database or RDBMS.

**Comment by ChillarAnand** [comment]
@georgepsarakis Thanks for the clarification. 

What I have described is just a hypothetical use case. I am trying to understand real life use cases of celery broadcasting.

**Comment by morphyno** [comment]
@georgepsarakis, I have the same use case, and I think it is a very practical use case. Here's what I've done thus far. Passing additional unique identifiers inside kwargs of the broadcast task, the works would then write unique results to a separate shared database using those entries. The challenge for me is knowing when the results are complete, since the speed of workers completing their respective tasks vary. My current work around to that is to add an additional worker, whose sole job is to monitor the database. This allows to map a dedicate unicast queue to that one worker (which is basically managing the status of workers on the broadcast queue), I then use flower REST API to interface with one message queue alone. I wish there's a better way though :-)

**Comment by alper** [comment]
Isn't it in general an anti-pattern to expect results back from celery tasks? It's a lot easier to just fire and forget them and have them put their results in some kind of medium (database, etc.).
