### ISSUE TITLE
Order of values returned from chain() is undefined

### ISSUE THREAD

**Issue by lpsinger** [celery/celery#4150]
The order of values that are passed from a chord to the callback function is undefined and perhaps random. However, oddly, the return values of tasks in a group are well-defined.

## Example application: canvastest.py

```python
#!/usr/bin/env python
from celery import Celery

__all__ = ('app', 'ident')

app = Celery('canvastest.py', backend='redis://')

@app.task
def ident(x):
    return x

if __name__ == '__main__':
    app.start()
```

## Start the worker

```
$ ./canvastest.py worker
```

### Undefined ordering with `chord`

```
$ ./canvastest.py shell --python
>>> [chord([ident.s(1), ident.s(2)])(ident.s()).get() for i in range(100)]
[[1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [2, 1], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [2, 1], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [2, 1], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [2, 1], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [2, 1], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [2, 1], [1, 2], [1, 2], [1, 2], [2, 1], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [2, 1], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [2, 1], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2]]
```

### Well-defined ordering with `group`

```
$ ./canvastest.py shell --python
>>> [result.get() for result in [group(ident.s(1), ident.s(2)).delay() for _ in range(10)]]
[[1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2]]
```

**Comment by max-vogler** [comment]
This is actually a **big** issue. Most Celery examples are quite trivial (e.g. 2+2), do not rely on ordering of task results, and thus this issue is non-trivial to discover in the first place. 

I'm having a map-reduce use case where a piece of data is processed by several different workers in parallel and then the collected results are processed by another worker (let's call it _reducer_). It is crucial for the reducer to associate which result came from which worker. Because `chord` does not preserve ordering, and reducer cannot access enough metadata to associate the results to workers, the only solution right now is to embed the worker id in the actual payload.

**Comment by georgepsarakis** [comment]
This depends on the backend implementation, see also this [discussion](https://github.com/celery/celery/issues/3781) on the Redis backend. I do not believe it would be easy to solve this reliably, otherwise it would be implemented. If you happen to find a way to possibly implement this, please share.

**Comment by auvipy** [comment]
let's continue the discussion https://github.com/celery/celery/issues/3781 here
