### ISSUE TITLE
Add an official Docker image

### ISSUE THREAD

**Issue by thedrow** [celery/celery#4214]
In order to complete #4213 we need an official Docker image to use when deploying to Kubernetes or elsewhere.
The official image will provide a base image for all users interested in deploying Celery using Docker.

**Comment by yhvh** [comment]
Re-examining this today.

I found the celery image had been deprecated, with the main argument I think being that the main use case is with django and, since the container shares the application code (for tasks), it makes sense to just use the same container. This is Indeed what I have done this in past projects. 

https://hub.docker.com/r/library/celery/
https://github.com/docker-library/celery/issues/1#issuecomment-287655769
https://github.com/docker-library/celery/issues/12

**Comment by auvipy** [comment]
https://github.com/celery/celery/commit/59d140082f8a826e84256df14610fcf1fba4c2a8
