### ISSUE TITLE
docs/contributing.rst vs CONTRIBUTING.rst

### ISSUE THREAD

**Issue by atombrella** [celery/celery#4218]
These two files overlap quite a bit. Instead of maintaining two files that mostly have equivalent content, maybe converting one of them into a symlink would be an idea?

**Comment by atombrella** [comment]
I see some references in the Makefile to `CONTRIBUTING.rst`. However, I'm not sure what the purpose of this (duplicated) file is.

**Comment by pachewise** [comment]
They should be the same 😆 `docs/contributing.rst` is the source for `CONTRIBUTING.rst`, which is built as part of the `contrib` make command (converted from sphinx syntax to rst by, you guessed it, `sphinx2rst`).

> I'm not sure what the purpose of this (duplicated) file is.

It's [expected](https://github.com/blog/1184-contributing-guidelines) to have a `README` and a `CONTRIBUTING` in the root dir of an open-source repo. Symlinks are rendered as text files on the github viewer, so that strategy wouldn't work.

**Comment by thedrow** [comment]
We can do the same thing we do with the changelog in the documentation.
See https://github.com/celery/celery/blob/master/docs/changelog.rst
PRs are welcome of course :)

**Comment by thedrow** [comment]
Closing as this is fixed with #4272.
