### ISSUE TITLE
Two different tasks from schedule starts simultaneously!

### ISSUE THREAD

**Issue by trianglesis** [celery/celery#4585]
## Checklist

- [X] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

## Steps to reproduce
Create and register two tasks for different time of day using "django_celery_beat_periodictask"

## Expected behavior
Run tasks:
one at 16
second at 17

## Actual behavior
Both started at 16
[2018-03-09 16:00:00,001: INFO/MainProcess] Scheduler: Sending due task addm_cleanup_all 		 (cases.tasks_shelf.routine_tasks.tasks.addm_weekly_cleanup_routine)
[2018-03-09 16:00:00,004: INFO/MainProcess] Scheduler: Sending due task tkn_main_workday_routine (cases.tasks_shelf.routine_tasks.tasks.night_test_executor)

MySQL DB:
Cron:
```
# id, minute, hour, day_of_week, day_of_month, month_of_year
4, 0, 16, 5, *, *
19, 0, 17, 1,2,3,4,5, 1-19,28-31, *

```
Tasks:
```
# id, name, task, args, kwargs, queue, exchange, routing_key, expires, enabled, last_run_at, total_run_count, date_changed, description, crontab_id, interval_id, solar_id
4, addm_cleanup_all, cases.tasks_shelf.routine_tasks.tasks.addm_weekly_cleanup_routine, [], {}, routines, , , , 1, 2018-03-09 16:00:00.001003, 3, 2018-03-09 16:00:20.053235, , 4, , 
5, tkn_main_workday_routine, cases.tasks_shelf.routine_tasks.tasks.night_test_executor, ["tkn_main"], {"send_mail": true, "sync_tku": true, "user_name": "cron_user"}, routines, , , , 1, 2018-03-09 16:00:00.004677, 9, 2018-03-09 16:00:20.048983, , 19, , 
```

Human friendly:
![image](https://user-images.githubusercontent.com/12595699/37217753-08eb1d74-23c7-11e8-86db-f6a2c3fd1a36.png)

**Comment by trianglesis** [comment]
UPD:
Related to: http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#django-users

The question is:
WHY crontab entry with fixed time to execute task 17-00 was executed based on value of "last_run_at" disregarding the actual time it configured to run?

**Comment by fzumstein** [comment]
We see the same issue (two tasks starting at the same time when they are scheduled for different hours) but we haven't managed to replicate that consistently yet.

**Comment by fcostin** [comment]
it is possible but not certain that you are seeing behaviour that is partly caused by https://github.com/celery/celery/issues/4806  --- that issue can cause celery beat crontab schedules to fire at arbitrary times, and happens in scenarios where a crontab schedule entry has a `last_run_at` value that is older than the most recent feasible time with respect to the crontab schedule.

There would need to be something else going on as well, given that you are seeing the schedule fire at an arbitrary time that just so happens to be the time when another crontab schedule. 

Perhaps something to do with celery beat sleeping until the time estimate for the other task indicates it is due , or an issue with stale orm cache state in django-celery-beat ?

**Comment by auvipy** [comment]
whats the current status of this?
