### ISSUE TITLE
Please use `sys.exit()` or flush STDERR if failed on `platform.check_privileges`

### ISSUE THREAD

**Issue by alanjds** [celery/celery#4594]
https://github.com/celery/celery/blob/a3c377474ab1109a26de5169066a4fae0d30524b/celery/platforms.py#L794:24

The way it is now, the message could be lost because `os._exit()` does not flushes STDERR.

Why are we using `os._exit()` instead of the recommended `sys.exit()`? I can provide a PR if asked, but please clarify why the `os._exit()` before the patch is written.

**Comment by alanjds** [comment]
cc: @ask @sbneto

**Comment by georgepsarakis** [comment]
Can you check the history of the file to see if there is a comment in the commit introducing this function?

**Comment by sbneto** [comment]
The commit that introduced this code says `worker/beat: --uid + --gid now works even without --detach`. I could not find anything related to the use of `os._exit()` specifically. Also, this was the first and only version of the code written about 4 years ago. Not sure where else to look for clues on why this is as it is.

**Comment by georgepsarakis** [comment]
This was by design. See [here](https://stackoverflow.com/a/9591397/920374) and if you notice in the [documentation on sys.exit](https://docs.python.org/3.5/library/sys.html#sys.exit), it raises an Exception which could potentially be caught somewhere in the code. On the other hand, [os._exit](https://docs.python.org/3.5/library/os.html#os._exit) causes an immediate shutdown, I believe using a system call.

**Comment by alanjds** [comment]
Alright 👍. I could advocate for sys.exit(), but not strongly.

However, the `sys.stderr` is not being flushed and this is a real problem. When running on Docker I can only see the thing reboot on loop. No sign of why. Because the error message is not flushed.

On dev machine the thing works. On docker it cycles, because I forgot that it runs as `root` by default. Had to exec into the container to discover why by accident.

Could I provide a PR flushing `sys.stderr`?

**Comment by alanjds** [comment]
https://docs.python.org/3.5/library/exceptions.html#SystemExit:
> **exception SystemExit**
> This exception is raised by the sys.exit() function. It inherits from BaseException instead of Exception so that it is not accidentally caught by code that catches Exception.
>...

**Comment by georgepsarakis** [comment]
@alanjds sorry to hear about the issues. I don't see any reason why not to flush output streams before exiting, so please feel free to open a PR.

**Comment by wetneb** [comment]
I had the same issue (celery exiting with error code 1 without printing anything), and it was quite painful to figure out what was happening (basically had to isolate the bug by adding dozens of print() statements in celery to figure out where it was dying, because I had no access to a debugger in that environment).

**Comment by alanjds** [comment]
Thanks @wetneb for the fix that I am lazy enough to let others do for me.

Thanks for searching on other files for this pattern too.

**Comment by wetneb** [comment]
@alanjds thanks for filing the issue, I wouldn't have figured out the fix without it!
