### ISSUE TITLE
celery.chord argument mismatch

### ISSUE THREAD

**Issue by mattmccormick** [celery/celery#4644]
To replicate, call celery.chord with one task that returns a dict and provide additional arguments to the callback.

After `_merge` is called, the dict will be the first argument passed into the callback.  This is a bit of a gotcha as in most cases a list of dicts would be returned when running more than one task.

https://github.com/celery/celery/blob/e3b973d90dd445e0f6299dbd82c50d388aa2e841/celery/canvas.py#L227

**Comment by auvipy** [comment]
I would request you to send a pr with your investigated changes. An integration test with unit test will also be needed against master.

**Comment by danidee10** [comment]
I want to add my voice to this. I noticed this issue recently. @mattmccormick It's not only `dicts`. I can confirm that it's the same behaviour for `int`'s and `str`'s.

If you call a `chord` with just one task, the object is passed (instead of a list containing the object) to the callback.

If you call the `chord` with two or more arguments then a `list` of all the results is passed to the callback.

This behaviour is inconsistent IMO.

**Comment by AlexHill** [comment]
This has been fixed in the upcoming 4.2 release.

**Comment by danidee10** [comment]
Thanks @AlexHill Is there a specific date I can look forward to? I've checked for the release schedule and I didn't find anything here http://docs.celeryproject.org/en/master/changelog.html

**Comment by auvipy** [comment]
he said upcoming 4.2 which is rc2 now on pypi
