### ISSUE TITLE
redis backend does not unsubscribe from celery-task-meta-XXX channels when ignore_result=True

### ISSUE THREAD

**Issue by bartloop** [celery/celery#4707]
This is relevant to using the redis backend.

When I trigger a task, a "pubsub subscribe" command is issued, resulting in a 'celery-task-meta-XXX' entry in the pubsub channels list:
```
(py36) [host]:celery$ sudo redis-cli pubsub channels
1) "celery-task-meta-6e941dbb-006e-4e6e-8cec-2d0e024d6faf"
```
Because there is no return value, and because I don't want to block, I do not call AsyncResult.get(), which normally does the job of unsubscribing.

If the unsubscribe doesn't happen, the list of subscriptions grows without end, causing resource issues after several hundred thousand tasks.

Instead, I've tried two ways to prevent this problem:

1. include **ignore_result=True** in the @app.task annotator
2. to call AsyncResult.forget() on the return value from .delay()

I do not know if this is a bug or if I'm doing things incorrectly. 

This can be reproduced with this code, tasks.py (adapted from a contribution by @mleginus):

```
"""Celery tasks module."""
from celery import Celery
from kombu import Queue
from redis import StrictRedis
from time import sleep

class CeleryConfig(object):
    # celery configurations
    broker_url = 'redis://localhost:6379/1'
    task_default_queue = 'default'
    task_queues = (
        Queue('default', routing_key='parent.#,opbeat'),
    )
    imports = ('tasks',)
    result_backend = 'redis://localhost:6379/2'

def create_app(config):
    """Create a celery app instance."""
    celery_app = Celery("tasks")
    celery_app.config_from_object(config)
    return celery_app

app = create_app(CeleryConfig)

@app.task(ignore_result=True)
def enrich_single_call(data):
    """Single call to task that returns nothing. """
    pass

def run_test_task():
    """Run test task."""
    redis = StrictRedis()
    channels_before = len(redis.execute_command('PUBSUB CHANNELS'))
    print('Redis channels count before task execution {}'.format(channels_before))
    result = enrich_single_call.delay('hello')
    sleep(5)
    channels_after = len(redis.execute_command('PUBSUB CHANNELS'))
    print('Redis channels count after execution {}'.format(channels_after))

```
First, start a worker using tasks.py:
```
celery -A tasks worker -Q default -P solo
```

Then, import tasks.py in an interpreter and run
```
for _ in range(3):
    run_test_task()
```
The output is 
```
Redis channels count before task execution 0
Redis channels count after execution 1
Redis channels count before task execution 1
Redis channels count after execution 2
Redis channels count before task execution 2
Redis channels count after execution 3
```
The output indicates that the number of pubsub channels is growing.

I would expect the count to be 0 on all lines.

If we add 
```
result.get()
```
to the end of the test function, the count decrements.

If we add 
```
result.forget()
```
to the end of the test function, the count does not decrement.

-----
Issue #3812 and #4666 are related, but closed issues.

Based on the fix related to these issues, I tested the code above on the latest release candidate for celery:
```
pip3 freeze | grep celery
celery==4.2.0rc3
```
I'm using redis 4.0.7. I've tried this on Ubuntu 16 and mac os X

Thanks in advance for any help on this!

**Comment by georgepsarakis** [comment]
I think I found the root cause and managed to solve this, but I need to consider my solution once more. I will certainly follow up with a Pull Request probably today or tomorrow.

**Comment by bartloop** [comment]
@georgepsarakis Thank you much for the speedy resolution to this bug.

I do not know this code base very well, so I cannot comment on whether your fix is the right one. At the high level, your choice to avoid the subscription in the first place seems like the right solution to me.

I confirm that the fix works for me locally. If ignore_result=True, channel count stays at 0; if ignore_result=False, it grows as before.

One downside I see is that the current setup requires a fully-informed developer. Had this bug already been fixed, I would have still encountered the same problem: I did not know ignore_result was needed; I did not know that pubsub was subscribing to things in the background; and I did know that pubsub kept resubscribing to old stale channels. In fact, we ran many machines in production for several months before we noticed this. The natural assumption of a developer is "if I want a result, I need to get it; if I don't want a result, do nothing."

I do not have a solution for this downside, but since you know the code, you may have an easy solution in mind. Perhaps it is possible to detect that a task has no return value and set ignore_result automatically.

Second, because ignore_result is a task annotation rather than a parameter to apply_async, the current setup does not allow one task caller to consume a return value and another to ignore it. Of course, there are ways around this, so not a huge deal.

Again, thank you for resolving this!

**Comment by georgepsarakis** [comment]
@bartloop thanks for testing and providing feedback. If results are not ignored, the caller must call `result.get()` in order to unsubscribe. This is expected behavior and concerns the process that creates the tasks and consumes the results, since they must be notified that the task is ready and the result is available. Messages are forwarded only to active channels, so the subscription cannot be performed at any other time. As far as I can see, this would create an issue only if you have very long-running processes that create large numbers of tasks and never consuming the results. Ignoring results that are not going to be used is also recommended in the [documentation](http://docs.celeryproject.org/en/latest/userguide/tasks.html#ignore-results-you-don-t-want).

I noticed that the consumer does not unsubscribe when `AsyncResult.forget` is called or when the `AsyncResult` instance is deleted (using `del`), so we may need to correct this as well. In that case, the caller can simply call `forget()` instead of `get()` when they want to discard the result.

**Comment by georgepsarakis** [comment]
@bartloop if you think that the documentation can be expanded, to help avoid similar issues in the future, please feel free to open a Pull Request.

**Comment by bartloop** [comment]
I have created the pull request for doc changes as you suggested. Do I need to generate another issue for the AsyncResult.forget() issue?

**Comment by georgepsarakis** [comment]
@bartloop According to the changes we introduced in #4709:
- [AsyncResult.forget()](https://github.com/celery/celery/pull/4709/files#diff-accb7090ee45fffb2262cbceeabef002R249) will also unsubscribe
- You can use `ignore_result` as an task execution option directly in [apply_async / delay methods](https://github.com/celery/celery/pull/4709/files#diff-a4622e17daa3bfaf3dc55dbd6b35ced7)

**Comment by mleginus** [comment]
@georgepsarakis and @bartloop thanks for making progress with Redis channels leakage + updating documentation on usage of `get()` and `forget()` - it was not obvious for me. Anyway, I am reaching out since AsyncResult.forget() can unsubscribe. How does this relates to chord behaviour? Currently, I can see when running chord and consuming results with `get()` subscribed channels count is 0 (as expected) but when I use forget() channels are unsubscribed. Is this expected behaviour?

**Comment by georgepsarakis** [comment]
@mleginus this issue has been closed for some time now. Would you mind opening a new issue, so that we can continue the discussion there? Thanks!
