### ISSUE TITLE
Type Object not JSON serializable when inheriting from Task class

### ISSUE THREAD

**Issue by stcrestrada** [celery/celery#4708]
## Checklist
* Confirmed on multiple blogs and docs on how to Inherit from `Task` and register the class as a task; however, this isn't working. Am I missing something here?

## Background:

* Migrating from rq to celery. We inherently use a `run` function from rq that placed everything on the queue, which is why I'd prefer to inherit from `Task`, in order to avoid a painful migration. 

* Also open to other suggestions other than inheriting from `Task`.  :)

## Steps to reproduce

run `celery -A celeryconfig worker --loglevel=info`
run `python main_celery.py`

## Expected behavior
* Job is placed on queue and runs

## Actual behavior
* Fails ` TypeError: Object of type type is not JSON serializable`

`celeryconfig.py`
```from __future__ import absolute_import
from celery import Celery

app = Celery(broker="redis://localhost:6379", backend="redis://localhost:6379")

app.conf.update(
    task_serializer='pickle',
    result_serializer='pickle'
)

if __name__ == '__main__':
    app.start()
```

`main_celery.py`
```
from __future__ import absolute_import

from celeryconfig import app
from datetime import datetime

import logging

logger = logging.getLogger(__name__)

class CeleryBase(app.Task):
    abstract = True

    def run(self, *args, **kwargs):
        pass

    def __call__(self, *args, **kwargs):
        """In celery task this function call the run method, here you can
        set some environment variable before the run of the task"""
        logger.info("Starting Run")
        return super(CeleryBase, self).__call__(*args, **kwargs)

    def after_return(self, status, retval, task_id, args, kwargs, einfo):
        # exit point of the task whatever is the state
        logger.info("Ending run")
        pass


class ScheduleHarvest(CeleryBase):
    ignore_result = False
    name = None

    def run(self, x, y):
        try:
            if x and y:
                result = add(x, y)
                logger.info('result = %d' % result)
                return result
            else:
                logger.error('No x or y in arguments.')
        except KeyError:
            return False


def add(x, y):
    return x + y


ScheduleHarvest.name = ScheduleHarvest
app.register_task(ScheduleHarvest)
ScheduleHarvest().apply_async(args=[1,  5], eta=datetime.utcnow())
```

## Other behavior 

* If, and only if, I remove this line `ScheduleHarvest.name = ScheduleHarvest` then run `main_celery.py` the worker fails and I get the error below. 

```The full contents of the message body was:
'\x80\x02]q\x01(K\x01K\x05e}}q\x02(X\x05\x00\x00\x00chordq\x03NX\t\x00\x00\x00callbacksq\x04NX\x08\x00\x00\x00errbacksq\x05NX\x05\x00\x00\x00chainq\x06Nu\x87q\x07.' (80b)
Traceback (most recent call last):
  File "/Users/stephenestrada/.virtualenvs/divvy/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 561, in on_task_received
    strategy = strategies[type_]
KeyError: '__builtin__.type'
```

**Comment by vladcalin** [comment]
>  ScheduleHarvest.name = ScheduleHarvest

`ScheduleHarvester.name` should be a string and you should set it in the class body (instead of `name = None`). This is causing the `TypeError: Object of type type is not JSON serializable` error.

Secondly, that weird `KeyError: '__builtin__.type'` error is caused by the fact that the worker is does not find the task implementation because it is registered in the `celery_main.py` file and the worker on startup only loads `celeryconfig.py`. You should have the task declaration and register in the celeryconfig.py (or at least in some module the worker will import). As a personal general rule of thumb, I keep the task declarations separate from the scripts/modules that use them.

When registering a task, you must pass the task instance to ``app.register_task``, not the task class iteself, or else it will cause some ``mro`` related issue.

Also, when creating class based tasks, make sure you inherit from ``celery.Task`` not from ``app.Task``.

In order for it to work, you must also add `accept_content=["picke"]` configuration if you REALLY do want to use pickle (why not use the default serialization?).

Here is my version of the scripts that I tried and worked as expected.

- ``celeryconfig.py``

```
from celery import Celery, Task
import celery
from datetime import datetime
import logging

app = Celery(broker="redis://localhost:6379", backend="redis://localhost:6379")

app.conf.update(
    task_serializer='pickle',
    result_serializer='pickle',
    accept_content=['pickle']
)


logger = logging.getLogger(__name__)

class CeleryBase(celery.Task):
    abstract = True

    def __call__(self, *args, **kwargs):
        """In celery task this function call the run method, here you can
        set some environment variable before the run of the task"""
        logger.info("Starting Run")
        return super(CeleryBase, self).__call__(*args, **kwargs)

    def after_return(self, status, retval, task_id, args, kwargs, einfo):
        # exit point of the task whatever is the state
        logger.info("Ending run")
        pass


class ScheduleHarvest(CeleryBase):
    ignore_result = False
    name = 'ScheduleHarvest'

    def run(self, x, y):
        try:
            if x and y:
                result = add(x, y)
                logger.info('result = %d' % result)
                return result
            else:
                logger.error('No x or y in arguments.')
        except KeyError:
            return False


def add(x, y):
    return x + y


app.register_task(ScheduleHarvest())
```

- ``main_celery.py``

```
from datetime import datetime
from celeryconfig import ScheduleHarvest

ScheduleHarvest().apply_async(args=[1,  5], eta=datetime.utcnow())
```

**Comment by nadzhou** [comment]
@vladcalin this worked for me. thanks a million!
