### ISSUE TITLE
Add ReJSON backend support

### ISSUE THREAD

**Issue by badloop** [celery/celery#4816]
Feature request: Results are already being stored as a JSON string.  Adding support for ReJSON as a backend would provide easier parsing and retrieval of results for workflows and tasks.

Given the following result set:
```json
{
  "status": "SUCCESS",
  "result": {
    "uuid": [
      "uuid",
      "9c6c0c0a-12c9-4e65-9d07-faae4223dfde"
    ]
  },
  "traceback": null,
  "children": [
    [
      [
        "cb2561d0-496d-4c4b-85c1-d20e86f0f46a",
        null
      ],
      null
    ]
  ],
  "task_id": "270b1398-2516-4bf1-8c36-3ce53df85328"
}
```
ReJSON provides O(1) access to any element in the tree.  

Example queries and results:
```
10.233.66.182:6379> JSON.GET key .status
"\"SUCCESS\""
```

```
10.233.66.182:6379> JSON.GET key .result.uuid[1]
"\"9c6c0c0a-12c9-4e65-9d07-faae4223dfde\""
```

**Comment by xirdneh** [comment]
@badloop Could you add more specific examples on the use case?
Is this to access results from wherever?
Why not use `AsyncResult` or `GroupResult` to access those attributes?

**Comment by georgepsarakis** [comment]
Adding some context:
- [ReJSON](https://github.com/RedisJSON/RedisJSON) is a JSON data type for Redis.
- [Python client](https://pypi.org/project/rejson/)

I am not sure there is much gain for Celery's use case as the current result backend implementation uses multiple types such as Lists and Pub/Sub channels (in order to provide Canvas workflow support), but I guess it could be used for storing the final task result. I also agree that it should become a separate backend, but I am not sure there is much audience for this feature. I suggest that we close this for the time being.

**Comment by georgepsarakis** [comment]
Adding some context:
- [ReJSON](https://github.com/RedisJSON/RedisJSON) is a JSON data type for Redis.
- [Python client](https://pypi.org/project/rejson/)

I am not sure there is much gain for Celery's use case as the current result backend implementation uses multiple types such as Lists and Pub/Sub channels (in order to provide Canvas workflow support), but I guess it could be used for storing the final task result. I also agree that it should become a separate backend, but perhaps there is not much audience for this feature. 

I suggest that we close this for the time being.
