### ISSUE TITLE
Could not connect, 0 attempts left

### ISSUE THREAD

**Issue by davidmir** [celery/celery#4820]
Hi,

I am periodically seeing the following errors in the logs:

`[2018-06-15 15:01:32,363: ERROR/ForkPoolWorker-5] Connection to 10.0.0.6:5672 failed: timeout
[2018-06-15 15:01:32,363: WARNING/ForkPoolWorker-5] Could not connect, 0 attempts left`

I'm using celery 4.1.0 with RabbitMQ connection (amqp=2.2.2).
What happens to the celery process in these situations (is it killed and the task is lost, or is it able to recover)? What could be causing this situation?

Thanks.

**Comment by xirdneh** [comment]
Is this all you see on the logs? Can you post the rest of the stack trace?
Also, can you post the output of `celery -A proj report`?
And, if possible, could you try to see if the same problem appears using the latest version 4.2?
Thanks.

**Comment by thedrow** [comment]
It seems that the IPC socket failed to connect to the workers. I have no idea why though based on the details you provided me on this issue. 
Please report back when you have some concrete analysis.

**Comment by davidmir** [comment]
I'm using the following versions:

> celery:4.2.0 (windowlicker) kombu:4.2.1 py:2.7.9

I can't see more details running the `celery report` command.

How can I improve the debug for this issue? 

Thanks

**Comment by thedrow** [comment]
I suggest that you'll try to use strace or sysdig to figure out why this is happening.

**Comment by davidmir** [comment]
Using strace:

> epoll_ctl(5, EPOLL_CTL_DEL, 16, 0x7ffe54f25410) = -1 ENOENT (No such file or directory)
epoll_ctl(5, EPOLL_CTL_DEL, 21, 0x7ffe54f25410) = -1 ENOENT (No such file or directory)
fcntl(26, F_GETFL) = 0x2 (flags O_RDWR)
fcntl(26, F_SETFL, O_RDWR|O_NONBLOCK) = 0
recvfrom(26, 0x7f42ca4409e4, 7, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)

**Comment by thedrow** [comment]
The s trace output is not enough as it only presents the same symptoms you are describing. 
We need you to drill down on this.
When debugging code, especially one that behaves inconsistently we need to know what changed between the time Celery worked and the time Celery didn't work.
You either need to provide a test case that reproduces this behavior reliably or attach a debugger and describe the entire state of the mechanism which controls IPC for Celery.
Does this behavior reproduce under stress or even when you schedule one task?
What happens if you increase the concurrency of your pool?
Which OS are you running Celery in?
What does strace show before the symptoms you are describing? Where does the exception occur exactly?
There's simply not enough to analyze the problem and we need to do so in order to provide a solution.

**Comment by davidmir** [comment]
I noticed that when I have the Celery workers turned off and I do an apply_async for the RabbitMQ broker some of the messages are not being queued (or are being discarded or lost). This may explain why I have nothing in the Celery workers' logs. But the RabbitMQ logs are also reporting no errors.

**Comment by thedrow** [comment]
@davidmir ping?
I do want to solve this, but I need something to work with.

**Comment by davidmir** [comment]
@thedrow I can not get more details about the problem because the logs reveal no further details about the problem.

1) The problem occurs the system is not under stress, nor is there any cronjob to run.
2) The problem remains even if it increases or decreases the pool.
3) I'm running the celery worker inside a Docker container with debian:jessie image.

**Comment by thedrow** [comment]
Can you share the docker container with us?

**Comment by davidmir** [comment]
Not sure. But what you specifically want from the container?

**Comment by thedrow** [comment]
I want to see if the environment is causing this somehow.
