### ISSUE TITLE
Clarify documentation on how to use django, regular tasks and periodic tasks

### ISSUE THREAD

**Issue by w-** [celery/celery#5059]
v 4.2.1
There is inadquate information in the documentation regarding how to use periodic tasks with regular tasks in a django app.
http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#entries

Specifically, the issue seems to be around how to add a shared task using `add_periodic_task`

examples of questions on this
https://github.com/celery/celery/issues/3797
https://stackoverflow.com/questions/41119053/connect-new-celery-periodic-task-in-django

Personally the only solution that worked was this approach
https://github.com/celery/celery/issues/3797#issuecomment-355282686
https://stackoverflow.com/a/46965132/167674

I'm happy to help contribute to docs if someone can help authoritatively specify what the correct approach is.

## Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
      (if you are not able to do this, then at least specify the Celery
       version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.

**Comment by ovangle** [comment]
I was banging my head against this for most of today, I ended up fixing it by chaining together my `@shared_tasks` into a top level `group` and then executing that

```
@app.task
def run_shared_tasks():
   from myapp.tasks import shared_task_1, shared_task_2
   return group(shared_task_1, shared_task_2)
```

I think that the documentation related to periodic tasks should mention _something_ about `@shared_task`s being unusable as periodic tasks, but this issue was closed without resolution?
