### ISSUE TITLE
Update our Contributing document

### ISSUE THREAD

**Issue by thedrow** [celery/celery#5096]
Our contribution guide is too old and contains obsolete information.
Furthermore, it does not mention the [Needs Test Coverage](https://github.com/celery/celery/labels/Status%3A%20Needs%20Test%20Coverage%20%E2%9C%98) label which is where most of our PRs are abandoned at.

**Comment by xirdneh** [comment]
We probably should add a section on how to easily setup a local dev environment.
I usually run a standalone app in a docker container and point `$PYTHONPATH` to where I clone the celery project. This way when I do `import celery` in the code I'm importing from the cloned project and i can update it by hand.

Is there any prefer method?
If this is OK with everyone I can update the documentation since I would like it to be updated for next week's DjangoCon sprints.

**Comment by xirdneh** [comment]
Good idea, thanks!
I'll look into Cirlce-CI
