### ISSUE TITLE
SQS - Option for ignoring queue prefix when consuming it

### ISSUE THREAD

**Issue by michaeltcoelho** [celery/celery#5165]
I have a new application `A` producing messages to a queue named `ao-ic-event-submissions` and an already existent application `B` consuming it, this one (`B`) set `queue_name_prefix` in `broker_transport_options` to `production-queue-`. It happens that i define a task in that existing application (`B`) with name `ao-ic-event-submission-task` and a kwarg `queue` with `ao-ic-event-submissions` value. My workers on that existent application (`B`) are not consuming the messages coming from that queue. After hours debugging i've noticed that for every queue i set Kombu SQS transport is going to prefix my queues with that `queue_name_prefix` option. How can i handle this issue?

**Comment by jainraj** [comment]
@michaeltcoelho I think this is not an issue, rather a helpful feature to stop sending tasks to same-named queues of different projects. You can disable the prefix setting using the broker_transport_options by setting the prefix to empty string. 

I personally would suggest you to make the application `A` to consume with the prefix, so that even you can be perfectly sure that the production queues are being consumed by production applications and so on. 

Would love to hear more from you and what strategy you finally accepted.

**Comment by michaeltcoelho** [comment]
Hi @jainraj , i agree with you that prefixing queues is a nice feature, but when integrating two different applications as i commented earlier it's not that good because it is not an option to ignore prefixing individually on queue definition or on the task definition itself.

As you proposed to keep the same queue name in both application i think it's a context issue to me, it will keep both application coupled by the queue name, if someone change its name on our application is not going to consume messages anymore.

As a solution for this i think i can send messages to a SNS Topic from my application `A` and then subscribe a SQS Queue to that SNS Topic, so that i can keep my application `B` not tied to a specific queue or name, that is, not coupled to the application `A`.

**Comment by michaeltcoelho** [comment]
Right @jainraj , thank you!

**Comment by auvipy** [comment]
what is the current concensus of the issue?

**Comment by jainraj** [comment]
@auvipy I believe that this feature is not **required**. It is at a good-to-have stage. Since, coupling on queue names is anyway going to be a dependency between projects. PS: I have not worked with SNS
