### ISSUE TITLE
Sometimes task.get() dose not return while worker shows the task has finished

### ISSUE THREAD

**Issue by WishQi** [celery/celery#5353]
OS: macOS
Celery Version: 4.2.1
Broker: redis
Backend: redis

The task definition is like that:
```
@app.task(bind=True, autoretry_for=(Exception,), max_retries=3, default_retry_delay=180, time_limit=30 * 60)
def my_task():
    # do something
    pass
```

The task will be called in django like that:
```
task = my_task.delay()

result = task.get()
# following code
```

The problem is that sometimes the `task.get()` will never return, and as the result the following code will never run.

How should I solve this problem?

**Comment by auvipy** [comment]
possible to verify this with celery 4.3rc1?

**Comment by WishQi** [comment]
@auvipy Are you sure this issue has been fixed? Actually it may take some work to verify this.

**Comment by auvipy** [comment]
I am not sure that's why asking for try :)

**Comment by thedrow** [comment]
This is an incomplete bug report.
In order to fix it, we have to understand the conditions under which getting the result will block forever.

In any case, setting a timeout to `result.get()` is a good practice.

I'm going to close this as won't fix although I'm sure a bug exists somewhere.
If you have further information, make sure to open an issue about this.
