### ISSUE TITLE
[2019-03-04 11:08:55,583: CRITICAL/MainProcess] Unrecoverable error: VersionMismatch(‘Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.6’,)

### ISSUE THREAD

**Issue by mehtadev17** [celery/celery#5369]
The Kombu update from 4.3.0 to 4.4.0 stopped support for redis-py v2.10.6 and therefore forces us to upgrade redis-py version. 
Celery Version: 4.1.1

https://github.com/celery/celery/blob/v4.1.1/requirements/default.txt#L3

```
kombu.exceptions.VersionMismatch: Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.6
```

**Comment by andonirodriguez** [comment]
If you use pip for install celery I fix the error specifying kombu version in the requirements.txt 

celery==4.1.1
kombu==4.2.0

The error is in kombu dependency: 

https://github.com/celery/kombu/issues/1016

Regards.

**Comment by thedrow** [comment]
This is completely intentional since py-redis<3.20 contains bugs which crash Celery or makes certain features unusable.
This is exactly why I bumped the minor version.
We don't follow SemVer to the letter since we want Celery 5 to contain certain features and signify a new path for the project.

This breakage is declared in both the Celery 4.3.0 RC2 & Kombu 4.4.0 release notes.
The What's New document will contain a fair warning.
If you want to keep using py-redis 2, please downgrade to Kombu 4.3 and keep using Celery 4.2 or Celery 4.3RC1.
Alternatively, try to backport the relevant py-redis 3 patches and contribute them upstream if possible. You can also maintain your own fork. 

I apologize for the inconvenience but we had to do this since any other path would involve heavy monkey patching or breakage for users.

Thank you for noticing and opening an issue about this.
I'm going to close this issue as won't fix.

**Comment by mager** [comment]
Pinning to 4.3 worked for us.

**Comment by fako** [comment]
The following in my requirements.txt solved the issue. 

redis==3.2.1

If I understand @thedrow correctly it's a better approach than fixing Kombu suggested in the answer by @andonirodriguez.

**Comment by darwinyip** [comment]
FYI to future readers: `redis>=3.4.0` will break it again.
