### ISSUE TITLE
Show the scheduled cron to the user - Celery scheduler

### ISSUE THREAD

**Issue by ajaykmr2292** [celery/celery#5438]
1. I have a django app where users can schedule to run their tasks every week/month. I am storing this as a cron pattern in django_celery_beat. Now, I would like to show the user his schedule (like *task will run every saturday at 12AM* -human readable format). How can I do this when the crontab is TZ aware.
2. I have the scheduler running. Suppose I schedule 3000 tasks to run at a time (like 3AM), the scheduler is taking time to schedule tasks. I mean the scheduler does not scale with the number of tasks. How to configure the scheduler which might get around 3k-10k tasks to run at any single point of time?

**Comment by thedrow** [comment]
The first question is more appropriate for StackOverflow. Please post it there. I'm sure someone can help you figure this out.

As for the second question, you are correct. The current scheduler does not scale to thousands of tasks since it's synchronous.

Celery 5 will have a far more sophisticated scheduler which will be able to schedule tasks concurrently.
