### ISSUE TITLE
[Celery 4.3] when result_extended=True task name is always None

### ISSUE THREAD

**Issue by mdawar** [celery/celery#5439]
# Checklist

- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior
When `result_extended` is set to `True`, we expect to get the task name using the `name` attribute. 

# Actual Behavior
The `name` is always `None`, after debugging the `Context` object that is being passed to `BaseKeyValueStoreBackend.store_result` it contains the task name with the attribute `task` and not `task_name` as `BaseKeyValueStoreBackend._store_result` is trying to get from the request object:

```python
if self.app.conf.find_value_for_key('extended', 'result'):
    if request:
        request_meta = {
            'name': getattr(request, 'task_name', None),
            'args': getattr(request, 'args', None),
            'kwargs': getattr(request, 'kwargs', None),
            'worker': getattr(request, 'hostname', None),
            'retries': getattr(request, 'retries', None),
            'queue': request.delivery_info.get('routing_key')
            if hasattr(request, 'delivery_info') and
            request.delivery_info else None
        }

        meta.update(request_meta)
```

Also the unit test `test_result.test_AsyncResult.test_get_request_meta` is using a `Context` object with an explicit `task_name` set.

**Comment by thedrow** [comment]
Hi @johnarnold, I'm pinging you since you contributed the original PR.
It seems like `task_name` is not properly initialized. Do you have an idea why?

**Comment by johnarnold** [comment]
@thedrow Ouch. I swear I tested for task name and had it working with flower. I'll take a look.

**Comment by johnarnold** [comment]
Found:  https://github.com/celery/celery/blob/master/celery/app/task.py#L95

**Comment by svidela** [comment]
Hi,

I'm facing the same issue. I'm not familiarized with the source code but I wanted to share what I found while trying to understand how everything works.

The message sent to the worker has the task name under the key `'task'`. See:

- https://github.com/celery/celery/blob/master/celery/app/amqp.py#L353 (protocol v2)
- https://github.com/celery/celery/blob/master/celery/app/amqp.py#L433 (protocol v1)

In fact, the consumer fails otherwise. See:

- https://github.com/celery/celery/blob/master/celery/worker/consumer/consumer.py#L546 (protocol v2)
- https://github.com/celery/celery/blob/master/celery/worker/consumer/consumer.py#L555 (protocol v1)

Using that same message format, a `Request` object is created. See:

- https://github.com/celery/celery/blob/b2668607c909c61becd151905b4525190c19ff4a/celery/worker/strategy.py#L149

The `Context` class is initialized using that request dict. See:

- https://github.com/celery/celery/blob/b2668607c909c61becd151905b4525190c19ff4a/celery/worker/request.py#L523
- https://github.com/celery/celery/blob/4d4fb3bf04ebf1642428dccdd578f2f244aa158f/celery/app/trace.py#L365

Since the request dict has the task name under the key `'task'` (not `'task_name'`), the `Context` object has the task name in the attribute `'task'` as well. See:

- https://github.com/celery/celery/blob/master/celery/app/task.py#L100
- https://github.com/celery/celery/blob/master/celery/app/task.py#L103

It seems that using `task` instead of `task_name` in `BaseKeyValueStoreBackend._store_result` should fix this. Of course, the attribute in the `Context` class should be changed as well:

- https://github.com/celery/celery/blob/master/celery/app/task.py#L95
- https://github.com/celery/celery/blob/master/celery/app/task.py#L132

I hope it helps!

**Comment by mdawar** [comment]
@svidela thank you for the explanation, that's what I was saying, the request object has a `task` attribute and not a `task_name`,  the tests pass because a `Context` object is explicitly set with `task_name`.

**Comment by johnarnold** [comment]
@svidela  @mdawar You are of course correct.

I went back and looked at my internal subclass of RedisBackend because I knew I tested this and it was working for me.  Sure enough, I was using the 'task' key too, and that's why it works... :(

So, during the process of upstreaming/reviewing, we changed the internal property from task -> task_name.
https://github.com/celery/celery/pull/4490/commits/a5a6226ac5763e445cfbb30de597733fbeb27a2c
https://github.com/celery/celery/pull/4490/commits/3b0e6c6897e5018e308654173a559b73c0ff9516

Obviously I missed that it's not initialized correctly.  That's bad, and I feel bad.

So, for the fix.  #5486

**Comment by auvipy** [comment]
thanks all!!!

**Comment by thomas-mckay** [comment]
Hi everyone, I'm testing this on 4.4.0-rc2. It seems the proposed fix affects only some backends and not others. I'm testing with a database and the task name is always `None`. Looking at the code, it seems to be because the `DatabaseBackend` doesn't call `Base._store_result` but relies only on its own implementation. Same problem as [this other issue](https://github.com/celery/celery/issues/5436)).

**Comment by thedrow** [comment]
There may be, but we haven't had the time to implement it.
PRs are welcome.

**Comment by adamcohenhillel** [comment]
Is there a fix for this issue?

**Comment by thedrow** [comment]
> 
> 
> @svidela @mdawar You are of course correct.
> 
> I went back and looked at my internal subclass of RedisBackend because I knew I tested this and it was working for me. Sure enough, I was using the 'task' key too, and that's why it works... :(
> 
> So, during the process of upstreaming/reviewing, we changed the internal property from task -> task_name.
> [a5a6226](https://github.com/celery/celery/commit/a5a6226ac5763e445cfbb30de597733fbeb27a2c)
> [3b0e6c6](https://github.com/celery/celery/commit/3b0e6c6897e5018e308654173a559b73c0ff9516)
> 
> Obviously I missed that it's not initialized correctly. That's bad, and I feel bad.
> 
> So, for the fix. #5486

Yes, there was.
