### ISSUE TITLE
Replace PyCurl with friendlier alternatives like Request3 or Request-ng

### ISSUE THREAD

**Issue by auvipy** [celery/celery#5520]

**Comment by thedrow** [comment]
We won't need PyCurl or requests since we will be using the async client for AWS.
See [aiobotocore](https://github.com/aio-libs/aiobotocore).
If it matures enough we can use the higher level client [aioboto3](https://github.com/terrycain/aioboto3).

Since we're using trio, we will use trio's asyncio integration to execute one of these tasks.

**Comment by auvipy** [comment]
ok cool

**Comment by Tecktron** [comment]
I would like to throw in another vote for this (removal of pycurl). It's setup is cumbersome and unfriendly even on standard linux (you cannot just install libcurl then pip install pycurl, at least I have never been able to do that). Thanks!
