### ISSUE TITLE
Can celery decorate class methods?

### ISSUE THREAD

**Issue by UnicornSymbol** [celery/celery#5611]
celery 4.3.0
`
class Test(object):
    def __init__(self,msg=""):
        self._msg = msg

    @shared_task
    def test(self):
        return self._msg
`
`
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "E:\pyCharm\venv\lib\site-packages\celery\app\task.py", line 427, in delay
    return self.apply_async(args, kwargs)
  File "E:\pyCharm\venv\lib\site-packages\celery\app\task.py", line 532, in apply_async
    check_arguments(*(args or ()), **(kwargs or {}))
TypeError: test() missing 1 required positional argument: 'self''
`

**Comment by clokep** [comment]
The short answer is not really. This doesn't really make sense to do because (in a normal Celery set-up) the process the task runs in doesn't have access to the same instantiation of the object.

Any state you want to be given to the task needs to be sent as arguments (or stored in some other resources -- like a database, or the file system).

**Comment by UnicornSymbol** [comment]
Thank you. Task_method can do this in version 3.0, but it's removed in version 4.3, so I want to know how to do it in version 4.3.

**Comment by tothegump** [comment]
Can this doc resolve your problem?
[custom-task-classes](http://docs.celeryproject.org/en/latest/userguide/tasks.html#custom-task-classes)
