### ISSUE TITLE
Add elastic search v8.0+ support

### ISSUE THREAD

**Issue by auvipy** [celery/celery#7316]

**Comment by ALAN-WING-1997** [comment]
@auvipy 
Greetings. Im new to this repository. Noticed that this issue was created at Feb. Im quite interested in this new feature development. May I ask what is the process going on? May I join contribute to this feature? Thanks

**Comment by auvipy** [comment]
you can work to contribute this new release compatibility issue. please make sure to create new branch to work before sending a pull request :)

**Comment by Sauraj1234** [comment]
@auvipy can you provide the detail  information regarding this issue

**Comment by auvipy** [comment]
if you don;t have the will to be a little exploratory then this issue is not a good one for you. not even this project.

**Comment by auvipy** [comment]
currently we pinned the elasticsearch version below v8.0, you can try the latest release and see what need to be changed in the elastic search backend codes/API.

**Comment by Nusnus** [comment]
@Sauraj1234 Hello friend, to get started, you need to create a fork of the celery repo and develop your fixes on a branch in your fork. Then, you open a PR from the branch of your fork to `master` of celery. This way your code can be reviewed correctly.
Technicallity aside, basing on the topic of this issue "Add elastic search v8.0+ support”, I’d suggest you investigate what is the DOD (definition of done) for this effort. Understand what is needed to be developed, and plan your work. Develop at your own paste this feature and when it’s ready open the PR. Make sure all tests are running and add new tests for new code.

Generally, the idea is to independently look around and find which issue matches your interest/professional capabilities, and make an effort to push it forward. GitHub offer’s enough access to info/doc/examples etc. of everything you need. Please google on the standards of contributing to open source projects and educate on the process as a whole.

You can start here: https://opensource.guide/how-to-contribute/

**Comment by nogj** [comment]
Dear all,

I’ve just finished my first attempt to update the Elasticsearch backend in order to make it compatible both with v7 and v8 clients. Corresponding unit tests are also updated, all of them execute OK with both versions, and (to the best of my knowledge) everything seems to work well with a “real” v8 environment.

Following aspects described in (https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/release-notes.html#rn-8-0-0) were identified as relevant for this task:

-	Transport layer now uses elastic-transport package
-	Changed exception hierarchy, the major change is a new exception ApiError which differentiates between an error that’s raised from the transport layer (previously elasticsearch.exceptions.TransportError, now elastic_transport.TransportError) and one raised from the API layer
-	The client’s connection to Elasticsearch now must be specified with scheme, host, and port 
-	Removed the doc_type, include_type_name, and copy_settings parameters from many document and index APIs

I would  be glad to share these changes, in the hope that they can be of some interest… Is it ok to create a new branch with the updated code?  If so, is there any naming convention to be followed?

Best regards, and thank you for your time and support!

**Comment by auvipy** [comment]
hey! just fork, create a new branch on you forks local, name it elastic8, and put your codes and send a draft PR. we can look after other things while we review the draft PR :)  and don't forgot to ping me!

**Comment by auvipy** [comment]
it was actually fixed in 5.3.x release
