### ISSUE TITLE
Replace 'optparse' with 'argparse'

### ISSUE THREAD

**Issue by ask** [celery/celery#793]
This issue is open for anyone to work on.

**Comment by azmeuk** [comment]
Hi. optparse is [deprecated since python 2.7](https://docs.python.org/2/library/optparse.html) and a lot of libraries from the python ecosystem are moving from optparse to argparse. For example django 1.10 [no longer supports optparse](https://docs.djangoproject.com/en/1.9/howto/custom-management-commands/).

This can lead to several compatibility issues, for instance with django-celery as you can see below.

Would you consider to re-open this bug?
